package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;

rule "Project"
    ruleflow-group 'SendUserData'
    no-loop true
    when
      $process : WorkflowProcessInstance( ) 
     then
     log.info("Send Project");
 
	QRules rules = (QRules)$process.getVariable("rules"); 
	BaseEntity project = rules.getProject();

        if(project != null) {
            log.info("Sending project - "+project.getCode());
            rules.publishCmd(project, "PROJECT");
        }

end
