package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;

rule "User"
    ruleflow-group 'SendUserData'
    lock-on-active true
    when
      $process : WorkflowProcessInstance( ) 
     then
     	log.info("Send User");
 
		QRules rules = (QRules)$process.getVariable("rules"); 

		BaseEntity user= rules.getUser();


        if(user != null) {
            rules.publishCmd(user, "USER");
        }

end
