package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;

rule "UserCompany"
    ruleflow-group 'SendUserData'
    lock-on-active true
    when
      $process : WorkflowProcessInstance( ) 
     then
     	log.info("Send User Company");
 
		QRules rules = (QRules)$process.getVariable("rules"); 

		if (rules.getUser() != null) {
			String userCode = rules.getUser().getCode();
			log.info("userCode="+userCode);
     		/*  Get Company Code of the current user   */
        	BaseEntity company = rules.baseEntity.getParent(userCode, "LNK_STAFF");

        	if(company != null)
        	{
            	rules.publishCmd(company, "USER_COMPANY");
        	}
		}

end
