package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.utils.OutputParam;
import io.vertx.core.json.JsonObject;

import java.util.List;
import java.util.ArrayList;

rule "SPECIFIC_PLACED"
    ruleflow-group 'SpecificEnter'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		bucketCode : String(bucketCode.equals("Placed"))
	  
     then
    
		JsonObject jsonTemplates = new JsonObject();
		jsonTemplates.put("1", "EMAIL_TEMPLATE_PLACED_STUDENT");
		jsonTemplates.put("2", "EMAIL_TEMPLATE_PLACED_SCHOOL");
		jsonTemplates.put("3", "EMAIL_TEMPLATE_PLACED_SALESTEAM");
		jsonTemplates.put("4", "SMS_TEMPLATE_PLACED_STUDENT");
		System.out.println("Placed Notitifications Template Json: " + jsonTemplates.toString());
		
	/* output.setTypeOfResult("NotificationHubTemplateFound"); */
	/* output.setResultCode(jsonTemplates.toString()); */
	/* retract(output); */
		    
 	/* System.out.println("SUCCESS -> Set notification code to PLACED" );  */
 		
 		retract(bucketCode)
 		
 
end
