package life.genny.rules;

import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.TaskUtils;
import life.genny.model.OutputParam2;

rule "TASK_ITEM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 10000
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_TASK-.*" && (data.parentCode == "QUE_DRAFTS_GRP"))
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		System.out.println("TASK_ITEM_CLICK_EVENT: Parent code :  " + $message.getData().getParentCode());
		

		String code = $message.getData().getCode();
		System.out.println("TASK_ITEM_CLICK_EVENT: code="+code);
		/* remove the preceeding nn taskId text */
		code = code.substring("QUE_TASK-".length());
		System.out.println("TASK_ITEM_CLICK_EVENT: TaskIdStr="+code);
		Long taskId = Long.parseLong(code);
		System.out.println("TASK_ITEM_CLICK_EVENT: TaskId="+taskId);
		output = TaskUtils.getTaskOutputParam(userToken,taskId);
		System.out.println("TASK_ITEM_CLICK_EVENT: output="+output);
		retract( $message);
		update(output); 
		
		
	end
