package life.genny.rules;

import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.TaskUtils;


rule "TASK_ITEM_CLEAR_ITEMS_EVENT"
    ruleflow-group 'EventProcessing'
		salience 10000
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_CLEAR_TASKS" && (data.parentCode == "QUE_DRAFTS_GRP"))
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		System.out.println("TASK_ITEM_CLEAR_ITEMS_EVENT: Parent code :  " + $message.getData().getParentCode());
		
		TaskUtils.clearAllTasks(userToken);
		output.setTypeOfResult("NONE");
		
		
		retract( $message);
		update(output); 
		
		
	end
