package life.genny.rules;



import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Theme;
import life.genny.models.ThemeAttributeType;



rule "THM_TREE_GROUP_BEHAVIOUR"
    ruleflow-group 'GenerateThemes'
    no-loop true

    when
      not  Theme (code == "THM_TREE_GROUP_BEHAVIOUR")
      serviceToken : GennyToken( code == "PER_SERVICE")

    then

     	System.out.println("   Generate THM_TREE_GROUP_BEHAVIOUR Rule ");

			Theme theme = Theme.builder("THM_TREE_GROUP_BEHAVIOUR")
										.addAttribute(ThemeAttributeType.PRI_IS_EXPANDABLE, true).end()
										.addAttribute(ThemeAttributeType.PRI_IS_INHERITABLE, false).end()
										.addAttribute(ThemeAttributeType.PRI_HAS_QUESTION_GRP_LABEL, false).end()
										.addAttribute(ThemeAttributeType.PRI_IS_QUESTION_GRP_LABEL_CLICKABLE, true).end()
										.addAttribute(ThemeAttributeType.PRI_HAS_CHILD_ASKS, false).end()
										.addAttribute(ThemeAttributeType.PRI_HAS_QUESTION_GRP_INPUT, true).end()
										.addAttribute(ThemeAttributeType.PRI_IS_QUESTION_GRP_INPUT_CLICKABLE, true).end()
										.build();

			theme.setRealm(serviceToken.getRealm());

			insert(theme);

			VertxUtils.putObject(serviceToken.getRealm(), "", theme.getCode(), theme, serviceToken.getToken());
end
