package life.genny.rules;



import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Theme;
import life.genny.models.ThemeAttributeType;



rule "THM_TREE_ITEM"
   ruleflow-group 'GenerateThemes'
    no-loop true
    
    when
      not  Theme (code == "THM_TREE_ITEM")
      serviceToken : GennyToken( code == "PER_SERVICE")
      
    then
    
     	System.out.println("   Generate THM_TREE_ITEM Rule ");
 
		Theme theme = Theme.builder("THM_TREE_ITEM")
                                .addAttribute()
                                  .color("white")
                                  .height("auto")
                                  .flexGrow(0)
                                  .flexShrink(0)
                                  .flexBasis("auto")
                                  .paddingLeft(20)
                                  .paddingY(5)
                                .end()
                                .build();
                        
		theme.setRealm(serviceToken.getRealm());
		
		insert(theme);

		VertxUtils.putObject(serviceToken.getRealm(), "", theme.getCode(), theme, serviceToken.getToken());
end
