package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;
import life.genny.qwanda.validation.Validation;
import life.genny.qwanda.validation.ValidationList;
import life.genny.qwanda.datatype.DataType;

rule "FRM_TABLE_FOOTER"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_TABLE_FOOTER")
      serviceToken : GennyToken( code == "PER_SERVICE")
      FRM_TABLE_RESULT_COUNT : Frame3 ( code == "FRM_TABLE_RESULT_COUNT" )
      FRM_TABLE_PAGE_INDEX : Frame3 ( code == "FRM_TABLE_PAGE_INDEX" )
      FRM_TABLE_FOOTER_PAGINATION : Frame3 ( code == "FRM_TABLE_FOOTER_PAGINATION" )
    then
        System.out.println("   Generate FRM_TABLE_FOOTER Rule  "+serviceToken.getUserCode());
        Frame3 frame = Frame3.builder("FRM_TABLE_FOOTER")
                      .addFrame(FRM_TABLE_RESULT_COUNT, FramePosition.WEST).end()
                      .addFrame(FRM_TABLE_PAGE_INDEX, FramePosition.WEST).end()
                      .addFrame(FRM_TABLE_FOOTER_PAGINATION, FramePosition.EAST).end()
                      .build();
        frame.setRealm(serviceToken.getRealm());
        insert (frame);
        FrameUtils2.toMessage(frame, serviceToken);

end