package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;

rule "DETAIL_VIEW_ITEM_CLICK_EVENT"
	ruleflow-group 'EventProcessing'
	salience 2
	no-loop
	when
		$message : QEventMessage(
			(data.code matches "QUE_PRI_EVENT_VIEW_.*" && (data.rootCode == "QUE_TABLE_RESULTS_GRP")) ||
			data.code matches "QUE_VIEW_PROFILE" ||
			data.code matches "QUE_VIEW_APP"
		)
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
	then
		System.out.println("DETAIL_VIEW_ITEM_CLICK_EVENT");
		
		String targetCode = $message.getData().getTargetCode();
		System.out.println("TARGET code ::  " + targetCode);

		BaseEntity baseEntity = new BaseEntityUtils(userToken).getBaseEntityByCode(targetCode);
		
		if(baseEntity!= null){
			QDataBaseEntityMessage msg = new QDataBaseEntityMessage(baseEntity);
			msg.setToken(userToken.getToken());
			msg.setReplace(true);
			
			VertxUtils.writeMsg("webcmds", JsonUtils.toJson(msg));
		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		retract( $message);
	end
