package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;

rule "EDIT_FORM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop true
    when
		$message : QEventMessage(data.code matches "ACT_PRI_EVENT_EDIT")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println("Processing EDIT FORM CLICK EVENT : " + $message );
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		
		
		String workflowSignalCode = "EDIT_FORMS";
		String parentCode = $message.getData().getParentCode(); 	/* get parentcode SBE e.g. SBE_INTERN_XXXXX  */
		
		String[] parentSplit = parentCode.split("_");
        String typeOf = parentSplit[1];
        System.out.println("typeOf: " +typeOf);
        

		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_"+workflowSignalCode);
		output.setTargetCode($message.getData().getTargetCode());
		output.setSuitCase(typeOf);
		
		
		System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$ targetCode: " + output.getTargetCode());
		
		SessionFacts facts = new SessionFacts(serviceToken, userToken, output.getTargetCode());
		
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("STARTING EDIT FORMS PROCEDURE WITH: " +output);



		String targetCode = $message.getData().getTargetCode();

		if(targetCode != null ){

			System.out.println("targetCode   ::   " + targetCode);

			BaseEntity be = beUtils.getBaseEntityByCode(targetCode);
			
			if(be != null){

				System.out.println("be   ::   " + be.getCode());
				
				/* if be has LNK_INDUSTRY attr, we send  LNK_OCCUPATION */
				String industryCode = be.getValue("LNK_INDUSTRY", null);
				if(industryCode != null){

					industryCode = industryCode.replace("\"", "").replace("[", "").replace("]", "");
					System.out.println("industryCode   ::   " + industryCode);
				
					/* dropdown search for occupations */
					DropdownUtils dropdown = new DropdownUtils(serviceToken);
					
					dropdown.setNewSearch("Dropdown", "Fetch Dropdown Items")
									.addColumn("PRI_NAME","Name")
									.setSourceCode(industryCode)
									.setPageStart(0)
									.setPageSize(1000);

					/* Send the dropdown options */
					dropdown.sendSearchResults("GRP_OCCUPATION_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);
				}

				/* if be has LNK_HOST_COMPANY attr, we send  LNK_HOST_COMPANY_REP */
				String hostCompanyCode = be.getValue("LNK_HOST_COMPANY", null);
				if(hostCompanyCode != null){

					hostCompanyCode = hostCompanyCode.replace("\"", "").replace("[", "").replace("]", "");
					System.out.println("hostCompanyCode   ::   " + hostCompanyCode);

					/* dropdown search for companyRep */
					DropdownUtils dropdownHcReps = new DropdownUtils(serviceToken);
					
					dropdownHcReps.setNewSearch("HCR Dropdown", "Fetch HCR Dropdown Items")
														.addFilter("PRI_IS_HOST_CPY_REP", true)
														.setSourceCode(hostCompanyCode)
														.setPageStart(0)
														.setPageSize(1000);

					/* Send the dropdown options */
					dropdownHcReps.sendSearchResults("GRP_HOST_COMPANY_REP_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);

				}
			}
		}
	
		retract( $message);
	end
