package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;

rule "EDIT_FORM_CLICK_EVENT_DROPDOWN"
    /* r */uleflow-group 'EventProcessing'
		salience 1
    no-loop true
    when
		$message : QEventMessage(data.code matches "QUE_EDIT_.*")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String targetCode = $message.getData().getTargetCode();

		if(targetCode != null ){

			System.out.println("targetCode   ::   " + targetCode);

			BaseEntity be = beUtils.getBaseEntityByCode(targetCode);
			
			if(be != null){

				System.out.println("be   ::   " + be.getCode());
				
				String industryCode = be.getValue("LNK_INDUSTRY", null);
				industryCode = industryCode.replace("\"", "").replace("[", "").replace("]", "");

				String hostCompanyCode = be.getValue("LNK_HOST_COMPANY", null);
				hostCompanyCode = hostCompanyCode.replace("\"", "").replace("[", "").replace("]", "");
				
				/* if be has LNK_INDUSTRY attr, we send  LNK_OCCUPATION */
				if(industryCode != null){

					System.out.println("industryCode   ::   " + industryCode);
				
					/* dropdown search here */
					DropdownUtils dropdown = new DropdownUtils(serviceToken);
					
					dropdown.setNewSearch("Dropdown", "Fetch Dropdown Items")
									.addColumn("PRI_NAME","Name")
									.setSourceCode(industryCode)
									.setPageStart(0)
									.setPageSize(1000);

					/* Send the dropdown options */
					dropdown.sendSearchResults("GRP_OCCUPATION_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);

				}

					/* if be has LNK_INDUSTRY attr, we send  LNK_OCCUPATION */
				if(hostCompanyCode != null){

					System.out.println("hostCompanyCode   ::   " + hostCompanyCode);
				
					/* dropdown search here For internship */
					DropdownUtils dropdownInternship = new DropdownUtils(serviceToken);
					
					dropdownInternship.setNewSearch("Internship Dropdown", "Fetch Internship Dropdown Items")
														.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "BEG_%")
														.addFilter("LNK_HOST_COMPANY", SearchEntity.StringFilter.EQUAL, hostCompanyCode)
														.setPageStart(0)
														.setPageSize(1000);
					
					/* Send the dropdown options */
					dropdownInternship.sendSearchResults("GRP_INTERNSHIP_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);

					/* dropdown search here For companyRep */
					DropdownUtils dropdownHcReps = new DropdownUtils(serviceToken);
					
					dropdownHcReps.setNewSearch("HCR Dropdown", "Fetch HCR Dropdown Items")
														.addFilter("PRI_IS_HOST_CPY_REP", true)
														.setSourceCode(hostCompanyCode)
														.setPageStart(0)
														.setPageSize(1000);

					/* Send the dropdown options */
					dropdownHcReps.sendSearchResults("GRP_HOST_COMPANY_REP_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);

				}
			}
		}
		output.setTypeOfResult("NONE");
		output.setResultCode("NONE"); 
		retract( $message);
	end
