package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
rule "USER_PROFILE_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code == "QUE_USER_PROFILE")
		userToken : GennyToken (code != "PER_SERVICE" )
    then
	
		System.out.println("Processing Answer/Data : " + $message );
		String gotoPage = "FRM_QUE_USER_PROFILE_GRP";
		String key = userToken.getSessionCode()+":page";
		VertxUtils.writeCachedJson(userToken.getRealm(), key, gotoPage,userToken.getToken());
		
		System.out.println("sssss :"+ key);
		retract( $message);
end