package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Submit Edit Note"
	when
		rules: QRules(  isState("QUE_EDIT_NOTE_GRP") &&
		 				isState("EVENT_FORM_SUBMIT") &&
						isState("SUBMIT") &&
						!isState("LOOP_TRIGGER_SUBMIT_EDIT_NOTE")) 
	then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_SUBMIT_EDIT_NOTE");
		
		String noteCode = rules.getAsString("targetCode");
		if(noteCode == null){
			rules.println("noteCode is null");
			rules.setState("SEND_TOAST_SOMETHING_WENT_WRONG");
			return;
		}
		
		/* saving the stakeholder of the note, incase of the following workflows demands this */
		List<BaseEntity> stakeHolders = rules.baseEntity.getLinkedBaseEntities(noteCode, "LNK_MESSAGES");
		rules.set("noteStakeholders", stakeHolders);
		
		/* home navigation */
		rules.setState("NAVIGATE_TO_HOME_AFTER_NOTES_EDITED");
		
	 	rules.footer();      
end
