package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;


rule "ADD_ENTITY_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_.*" && (data.parentCode == "QUE_ADD_ITEMS_GRP" || data.parentCode == "QUE_QUICK_ADD_ITEMS_GRP") )
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
 		ruleDetails : RuleDetails()
    then

		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );

		
		String code = $message.getData().getCode();
		String workflowSignalCode = StringUtils.removeEnd(code, "_MENU");
		workflowSignalCode = StringUtils.removeStart(workflowSignalCode,"QUE_");

		output.setTypeOfResult("SIGNAL");
		
		if (workflowSignalCode.equals("HOST_CPY") || workflowSignalCode.equals("HOST_CPY_REP")) {
			output.setResultCode("START_"+workflowSignalCode);
		} 
		
		if (workflowSignalCode.equals("QA_INTERN") || workflowSignalCode.equals("QA_HOST_CPY_REP") || workflowSignalCode.equals("QA_EDU_PRO_REP") || workflowSignalCode.equals("QA_AGENT")) {
			output.setResultCode("START_QUICK_ADD");
		} 
		
		if (workflowSignalCode.equals("QA_HOST_CPY") || workflowSignalCode.equals("QA_EDU_PRO") || workflowSignalCode.equals("QA_INTERNSHIP") || workflowSignalCode.equals("QA_REF_PART")) {
			System.out.println(">>>>> These have not been created yet!! <<<<<");
		} 
		
		else {
		
			workflowSignalCode = workflowSignalCode + "_NO";
			System.out.println("workflowSignalCode: " +workflowSignalCode);
			
			output.setResultCode("START_ADD_ENTITY");
		}
		output.setTargetCode($message.getData().getTargetCode());
		output.setSuitCase(workflowSignalCode);
		
		
		
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("STARTING ADD_ENTITY WORKFLOW WITH: " +output);


		retract( $message);
	end