package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;


rule "ADD_ENTITY_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage((data.code matches "QUE_.*" && data.parentCode == "QUE_ADD_ITEMS_GRP") || data.code matches "SCH_ACT_PRI_EVENT_QUE_.*")
		/*$message : QEventMessage( ((data.code matches "QUE_HOST_CPY_REP_MENU" || data.code matches "QUE_EDU_PRO_REP_MENU" || data.code matches "QUE_INTERNSHIP_MENU" || data.code matches "QUE_INTERN_MENU" || data.code matches "QUE_REF_PART_REP_MENU") 
									&& data.parentCode == "QUE_ADD_ITEMS_GRP") || data.code matches "ACT_PRI_EVENT_QUE_.*")*/	
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
 		ruleDetails : RuleDetails()
    then

		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		/* Get Agent */
		String user = userToken.getUserCode();
		System.out.println("user: " + user);
		
		
		String code = $message.getData().getCode();
		String workflowSignalCode = StringUtils.removeEnd(code, "_MENU");

		if(code.startsWith("SCH_ACT_PRI_EVENT_QUE_")){
			workflowSignalCode = StringUtils.removeStart(workflowSignalCode,"SCH_ACT_PRI_EVENT_");
		}

		workflowSignalCode = StringUtils.removeStart(workflowSignalCode,"QUE_");
		System.out.println("workflowSignalCode: " +workflowSignalCode);
				
		
		if (workflowSignalCode.equals("HOST_CPY") || workflowSignalCode.equals("HOST_CPY_REP")) {
			output.setResultCode("START_"+workflowSignalCode);
		} else {
		
			workflowSignalCode = workflowSignalCode + "_NO";
			System.out.println("workflowSignalCode: " +workflowSignalCode);
			
			output.setResultCode("START_ADD_ENTITY");
		}
		
		output.setAskSourceCode(user);	
		output.setTargetCode($message.getData().getTargetCode());
		output.setTypeOfResult("SIGNAL");
		output.setSuitCase(workflowSignalCode);
		
		
		
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("STARTING ADD_ENTITY WORKFLOW WITH: " +output);


		retract( $message);
	end
