package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;


rule "ADD_ENTITY_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage( 
				(
					data.code matches "QUE_.*" && 
					!(data.code matches "QUE_QA_.*") &&
					data.parentCode == "QUE_ADD_ITEMS_GRP"
				) || 
				(
					data.code matches "SCH_ACT_PRI_EVENT_QUE_.*" &&  
					!(data.code matches "SCH_ACT_PRI_EVENT_QUE_TREE_ITEM_.*") && 
					!(data.code matches "SCH_ACT_PRI_EVENT_QUE_TAB_BUCKET_VIEW") 
				)
			)
		
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
 		ruleDetails : RuleDetails()
    then

		System.out.println(drools.getRule().getName() + " - Rule fired");
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		
		/* Get Agent */
		String user = userToken.getUserCode();
		System.out.println("user: " + user);
		
		
		String code = $message.getData().getCode();
		String key = StringUtils.removeEnd(code, "_MENU");

		if(code.startsWith("SCH_ACT_PRI_EVENT_QUE_")){
			key = StringUtils.removeStart(key,"SCH_ACT_PRI_EVENT_");
		}

		key = StringUtils.removeStart(key,"QUE_");
		System.out.println("key: " +key);
				
		/*
		if (workflowSignalCode.equals("HOST_CPY") || workflowSignalCode.equals("HOST_CPY_REP")) {
			output.setResultCode("START_"+workflowSignalCode);
		} else {
		*/
	
		
		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_ADD_ENTITY");
		
		output.setSuitCase(key);
		output.setAskSourceCode(user);	
		output.setTargetCode("NONE");
		
		
		System.out.println("**************************************************");
		System.out.println("TypeOfResult: "  + output.getTypeOfResult());
		System.out.println("ResultCode: "    + output.getResultCode());
		System.out.println("SuitCase: "      + output.getSuitCase());
		System.out.println("AskSourceCode: " + output.getAskSourceCode());
		System.out.println("TargetCode: "    + output.getTargetCode());
		System.out.println("**************************************************");
		
		retract( $message);
	end
