package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

rule "CLICK_OHS"
    ruleflow-group 'EventProcessing'
		salience 1000
    no-loop
    when
		$message : QEventMessage(data.code == "ACT_PRI_EVENT_OHS")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		ruleDetails : RuleDetails()

    then
		System.out.println("Processing CLICK OHS : " + $message );
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);
		
		
		/* Grab the BE's for the HCR and HC */
		String user = userToken.getUserCode();
		System.out.println("user: " + user);
		
		String hcCode = "";
		String ohsCode = "";
		
		BaseEntity newBe = beUtils.create("temp", "temp");
		
		
		if(user != null) {
				BaseEntity HCRBe = beUtils.getBaseEntityByCode(user);
				System.out.println("HCRBe = " + HCRBe);
				
				if(HCRBe != null) {
						hcCode = HCRBe.getValue("LNK_HOST_COMPANY",null);
						System.out.println("hcCode: " + hcCode);
						
						hcCode = hcCode.replace("\"", "").replace("[", "").replace("]", "");
						System.out.println("hcCode = " +hcCode);	
						
						if(hcCode != null) { 
								BaseEntity HCBe = beUtils.getBaseEntityByCode(hcCode);
								System.out.println("HCBe = " + HCBe);
								
								
								/* Check whether DOC_OHS_CODE exists or not */
								
								ohsCode = HCBe.getValue("DOC_OHS_CODE", null);
								System.out.println("ohsCode = " + ohsCode);
								
								if (ohsCode == null) {
										System.out.println("DOC_OHS_CODE does not exist yet. Creating now!");
										
										String uuid = UUID.randomUUID().toString();
										System.out.println("uuid: " +uuid);
										uuid = uuid.substring(4);
										
										ohsCode = "DOC_OHS_"+uuid;
										ohsCode = ohsCode.toUpperCase();
										System.out.println("OHS: ohsCode = " + ohsCode);
										
										newBe = beUtils.create(ohsCode, ohsCode);
										System.out.println("OHS: newBe = " + newBe);
										System.out.println(">>>>>>>>>>>> " + newBe.getName() + " <<<<<<<<<<<<");

										
								} else {
									System.out.println("DOC_OHS_CODE already exists: ohsCode = " + ohsCode);
									
									newBe = beUtils.getBaseEntityByCode(ohsCode);
									System.out.println("newBe = " + newBe);
									
								}
								
								
								/* Save HC and HCR answers against newBe */
								
								String firstName = getValueSaveAnswer(userToken.getUserCode(), newBe, HCRBe, "PRI_FIRSTNAME", "PRI_FIRSTNAME", "firstName");
								String lastName = getValueSaveAnswer(userToken.getUserCode(), newBe, HCRBe, "PRI_LASTNAME", "PRI_LASTNAME", "lastName");
								String jobTitle = getValueSaveAnswer(userToken.getUserCode(), newBe, HCRBe, "PRI_JOB_TITLE", "PRI_JOB_TITLE", "jobTitle");
								String email = getValueSaveAnswer(userToken.getUserCode(), newBe, HCRBe, "PRI_EMAIL", "PRI_EMAIL", "email");
								
								String legalName = getValueSaveAnswer(userToken.getUserCode(), newBe, HCBe, "PRI_LEGAL_NAME", "PRI_LEGAL_NAME", "legalName");
								String abn = getValueSaveAnswer(userToken.getUserCode(), newBe, HCBe, "PRI_ABN", "PRI_ABN", "abn");
								String addressFull = getValueSaveAnswer(userToken.getUserCode(), newBe, HCBe, "PRI_ADDRESS_FULL", "PRI_ADDRESS_FULL", "addressFull");
								String mobile = getValueSaveAnswer(userToken.getUserCode(), newBe, HCBe, "PRI_MOBILE", "PRI_MOBILE", "mobile");
								String website = getValueSaveAnswer(userToken.getUserCode(), newBe, HCBe, "PRI_COMPANY_WEBSITE_URL", "PRI_COMPANY_WEBSITE_URL", "website");
								String numStaff = getValueSaveAnswer(userToken.getUserCode(), newBe, HCBe, "LNK_NUMBER_STAFF", "LNK_NUMBER_STAFF", "numStaff");
								String cpyINC = getValueSaveAnswer(userToken.getUserCode(), newBe, HCBe, "LNK_COMPANY_INC", "LNK_COMPANY_INC", "cpyINC");
								
								
								/* Save DOC_OHS_CODE against HC */
								beUtils.saveAnswer(new Answer(userToken.getUserCode(), HCBe.getCode(), "DOC_OHS_CODE", ohsCode));
								
								
						} else {
							System.out.println("ERROR: Null hcCode");
						}
				} else {
					System.out.println("ERROR: Null HCRBe");
				}
		} else {
			System.out.println("ERROR: Null user");
		}
		
		/* Set Parameters */
 		
		output.setAskSourceCode(user);
		output.setTargetCode(ohsCode);
		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_OHS");	
		output.setSuitCase(hcCode);


		/* Print Parameters */
		
		System.out.println("**************************************************");
		System.out.println("AskSourceCode: " + output.getAskSourceCode());
		System.out.println("TargetCode: "    + output.getTargetCode());
		System.out.println("TypeOfResult: "  + output.getTypeOfResult());
		System.out.println("ResultCode: "    + output.getResultCode());
		System.out.println("SuitCase: "      + output.getSuitCase());
		System.out.println("**************************************************");
		
	
	
		retract($message);
	end
