package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;

rule "CLICK_MULTI_FORM"
    ruleflow-group 'EventProcessing'
		salience 1000
    no-loop
    when
		$message : QEventMessage(data.code == "ACT_PRI_EVENT_HC_VALIDATION" || data.code == "ACT_PRI_EVENT_OHS")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		ruleDetails : RuleDetails()

    then
		System.out.println("Processing CLICK MULTI FORM : " + $message );

		
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		String user = userToken.getUserCode();
		System.out.println("user: " + user);
		output.setAskSourceCode(user);
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);
		
		String code = $message.getData().getCode();
		code = code.replace("ACT_PRI_EVENT_","");
		
		String workflowSignalCode = "MULTI_FORM";

		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_"+workflowSignalCode);
		output.setSuitCase(code);

	
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("STARTING MULTI FORM WITH: " +output);
	
		retract($message);
	end
