package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;


rule "HELPER_FUNCTION_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "ACT_PRI_HELPER_FUNCTION")
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
 		ruleDetails : RuleDetails()
    then

		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		/* Get User */
		String user = userToken.getUserCode();
		System.out.println("user: " + user);

		output.setResultCode("START_HELPER_FUNCTION");
		output.setAskSourceCode(user);	
		output.setTypeOfResult("SIGNAL");
	
		System.out.println("STARTING HELPER_FUNCTION WORKFLOW ");

		retract( $message);
	end
