package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;


rule "QUICK_ADD_ENTITY_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage( 
			( data.code matches "QUE_.*" && data.parentCode == "QUE_QUICK_ADD_ITEMS_GRP" ) || 
			( data.code matches "QUE_QA_.*"  && data.parentCode == "QUE_ADD_ITEMS_GRP" ) || 
			data.code matches "ACT_PRI_EVENT_QUE_QA_.*"
			)
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
 		ruleDetails : RuleDetails()
    then

		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		System.out.println("QUICK_ADD_ENTITY_CLICK_EVENT: Rule fired" );


		/* Get Agent */
		String user = userToken.getUserCode();
		System.out.println("user: " + user);
		output.setAskSourceCode(user);		
		
		
		String code = $message.getData().getCode();
		String workflowSignalCode = StringUtils.removeEnd(code, "_MENU");

		if(code.startsWith("ACT_PRI_EVENT_QUE_QA_")){
			workflowSignalCode = StringUtils.removeStart(workflowSignalCode,"ACT_PRI_EVENT_");
		}

		workflowSignalCode = StringUtils.removeStart(workflowSignalCode,"QUE_");
		System.out.println("workflowSignalCode: " +workflowSignalCode);

		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_QUICK_ADD");
		
		output.setTargetCode($message.getData().getTargetCode());
		output.setSuitCase(workflowSignalCode);
		
		
		
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("STARTING ADD_ENTITY WORKFLOW WITH: " +output);


		retract( $message);
	end
