package life.genny.rules;



import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Theme;

rule "THM_DUMMY"
    ruleflow-group 'GenerateThemes'
    no-loop true
    when
      $process : WorkflowProcessInstance( ) 
    then
     System.out.println("Generate THM_DUMMY Rule");
     GennyToken serviceToken = (GennyToken)$process.getVariable("serviceToken"); 

	 Theme theme = Theme.builder("THM_DUMMY")
							.addAttribute()
								.height(100)
								.width(90)
								.end()
							.build();

	 VertxUtils.putObject(serviceToken.getRealm(), "", theme.getCode(), theme, serviceToken.getToken());
end
