package life.genny.rules;

global org.apache.logging.log4j.Logger log;

import life.genny.rules.listeners.JbpmInitListener;
import life.genny.models.GennyToken;



rule "eventListenerUserSetup"
salience 10000
    no-loop true
    when
    	userToken: GennyToken(code == "userToken")
     	serviceToken: GennyToken(code == "serviceToken")
    then
     log.info("Setup Listener for userToken!");
    kcontext.getKnowledgeRuntime().addEventListener(new JbpmInitListener(userToken)); 

end



