package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;

rule "FRM_DASHBOARD_INTERNS"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_DASHBOARD_INTERNS")
      serviceToken : GennyToken( code == "PER_SERVICE")
      FRM_DASHBOARD_INTERNS_HEADER : Frame3 ( code == "FRM_DASHBOARD_INTERNS_HEADER" )
      FRM_DASHBOARD_INTERNS_CONTENT  : Frame3 ( code == "FRM_DASHBOARD_INTERNS_CONTENT" )
    then
      System.out.println("   Generate FRM_DASHBOARD_INTERNS Rule  "+serviceToken.getUserCode());

      Frame3 frame = Frame3.builder("FRM_DASHBOARD_INTERNS")
                      .addTheme("THM_DASHBOARD", serviceToken).end()
                      .addTheme("THM_DASHBOARD_WRAPPER", ThemePosition.WRAPPER, serviceToken).end()
                      .addFrame(FRM_DASHBOARD_INTERNS_HEADER, FramePosition.NORTH).end()
                      .addFrame(FRM_DASHBOARD_INTERNS_CONTENT, FramePosition.NORTH).end()
                      .build();

      frame.setRealm(serviceToken.getRealm());

      insert (frame);

      /* Process and save to cache */
      FrameUtils2.toMessage(frame, serviceToken);

end
