package life.genny.rules;










import life.genny.rules.QRules;

rule "Get Roles from Keycloak"
     when
        rules: QRules(  isState("GET_ROLES_FROM_KEYCLOAK") &&
                        !isState("LOOP_GET_ROLES_FROM_KEYCLOAK") )
     then
        rules.header();
		rules.setState("LOOP_GET_ROLES_FROM_KEYCLOAK");

        rules.getRolesFromKeycloak();

        rules.setState("EXIT_ROLE_CHECK");
      	rules.footer();
end
