package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;

rule "DEFAULT_ANSWER"
    ruleflow-group 'AnswerProcessing'
    lock-on-active true
    when
	  userToken : GennyToken ( code != "PER_SERVICE" ) 
	  serviceToken : GennyToken( code == "PER_SERVICE") 
	  rules : QRules()
     then
 		System.out.println("Rule -> DEFAULT_ANSWER Processing Answer/Data :  user=" + userToken.getUserCode()); 
		System.out.println("Rule -> DEFAULT_ANSWER Processing Answer/Data :  qrules realm=" + rules.realm()); 
/*	 QRules rules = (QRules)$process.getVariable("rules");*/  

end
