package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;

rule "DEFAULT_ANSWER"
    ruleflow-group 'AnswerProcessing'
    lock-on-active true
    when
      $dataMessage : QDataAnswerMessage( ) 

     then
     log.info("Processing Answer/Data : " + $dataMessage);
 
		/*
		QRules rules = (QRules)$process.getVariable("rules");  
		BaseEntity project = rules.getProject();
	
	        if(project != null) {
	            log.info("Sending project - "+project.getCode());
	            rules.publishCmd(project, "PROJECT");
	        }
	        */

end
