package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;

import java.util.List;
import java.util.ArrayList;

rule "PRI_ADDRESS_JSON"
    ruleflow-group 'AnswerProcessing'
    lock-on-active true
    when
      beUtils : BaseEntityUtils()
	  serviceToken : GennyToken( code == "PER_SERVICE") 
	  answer : Answer( attributeCode == "PRI_ADDRESS_JSON" )
     then
 		System.out.println("Rule -> PRI_ADDRESS_JSON :  user=" + beUtils.getGennyToken().getUserCode()); 
	
		answer.setChangeEvent(true);
		beUtils.saveAnswer(answer); 


end
