package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "SET_NOTIFICATION_CODE"
    ruleflow-group 'SpecificEnter'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
	  
     then
     
     	
 		System.out.println("SUCCESS -> Set notification code to APPLIED" ); 
 		output.setResultCode("APPLIED");
 		
 		retract(userToken)
 		retract(serviceToken)
 		
 
end
