package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;

import java.util.List;
import java.util.ArrayList;

rule "APPLIED"
    ruleflow-group 'SpecificEnter'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity()
		output : OutputParam()
		bucketCode : String( bucketCode == "APPLIED")
	  
     then
 		System.out.println("APPLIED: Rule fired" ); 
 		System.out.println("APPLIED: newApplication = " + newApplication.getCode());
 		
		output.setResultCode("APPLIED");
		
		//retract(userToken)
		//retract(serviceToken)

end
