package life.genny.rules;

import life.genny.utils.OutputParam;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;

rule "BUCKET_TAB_ITEM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
    	
		$message : QEventMessage(data.code matches "QUE_.*" && (data.parentCode == "QUE_TAB_BUCKET_VIEW" || data.parentCode == "QUE_TAB_DETAIL_VIEW" || data.parentCode == "QUE_TAB_TABLE_VIEW"))	
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
    then
	
		System.out.println("Processing Answer/Data : " + $message );
		System.out.println("Parent code :  " + $message.getData().getParentCode());
		
		output.setFormCode("FRM_"+ $message.getData().getCode(),"FRM_CONTENT");	
		
		retract( $message);
end
