package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;
import life.genny.qwanda.datatype.CapabilityMode;

rule "BUCKET_TAB_ITEM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
    	
		$message : QEventMessage(data.code matches "QUE_TAB.*" && 
							(	data.parentCode == "QUE_TAB_BUCKET_VIEW" || 
								data.parentCode == "QUE_TAB_DETAIL_VIEW" || 
								data.parentCode == "QUE_TAB_TABLE_VIEW") )	
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
		allowed:Allowed()

    then
	
			System.out.println(drools.getRule().getName() + " triggered");

			drools.setFocus("BucketProcessing");

		/* 	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
				Boolean cache = true;
				List<String> codes = new ArrayList<String>();

			
				codes.add("APPLIED_APPLICATIONS");
				codes.add("SHORTLISTED_APPLICATIONS");
				codes.add("INTERVIEWED_APPLICATIONS");
				codes.add("OFFERED_APPLICATIONS");
				codes.add("PLACED_APPLICATIONS");
				codes.add("INPROGRESS_APPLICATIONS");

				for (String code : codes){
					
					System.out.println("SBE_CODE   ::   " +code); 
					long totalTime = TableUtils.searchTable(beUtils,code, cache);
					System.out.println("total took " + (totalTime) + " ms"); 

				}
		*/
		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		
		
		retract( $message);
end
