package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;

rule "BUCKET_TAB_ITEM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
    	
		$message : QEventMessage(data.code matches "QUE_TAB.*" && 
							(	data.parentCode == "QUE_TAB_BUCKET_VIEW" || 
								data.parentCode == "QUE_TAB_DETAIL_VIEW" || 
								data.parentCode == "QUE_TAB_TABLE_VIEW") )	
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )

    then
	
		System.out.println("Processing Answer/Data : " + $message );
		System.out.println("Parent code :  " + $message.getData().getParentCode());
		
		switch($message.getData().getCode()){

			case "QUE_TAB_BUCKET_VIEW" : 

				drools.setFocus("BucketProcessing");
		
				/* Boolean cache = true;
				String[] codes = { 
					"AVAILABLE_INTERNS", 
					"APPLIED_APPLICATIONS",
					"SHORTLISTED_APPLICATIONS",
					"INTERVIEWED_APPLICATIONS",
					"OFFERED_APPLICATIONS",
					"PLACED_APPLICATIONS",
					"INPROGRESS_APPLICATIONS"
				};

				for (String code : codes){
					
					System.out.println("SBE_CODE   ::   " +code); 
					long totalTime = TableUtils.searchTable(beUtils,code, cache);
					System.out.println("total took " + (totalTime) + " ms"); 

				} */

				output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */
				break;

			case "QUE_TAB_DETAIL_VIEW" : 
				output.setFormCode("FRM_DETAIL_VIEW_CONTENT","FRM_TAB_CONTENT"); 
				break;

			case "QUE_TAB_TABLE_VIEW" : output.setFormCode("FRM_TABLE_VIEW","FRM_TAB_CONTENT"); break;

			default : output.setFormCode("FRM_QUE_DASHBOARD_VIEW","FRM_CONTENT");	break;
		}
		
		
		retract( $message);
end
