package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import java.util.UUID;
import life.genny.notifications.EmailHelper;

import java.util.List;
import java.util.ArrayList;

rule "IS_QA_HOST_CPY_REP"
    ruleflow-group 'IsQuickAdd'
    no-loop true
    salience 1000
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("QA_HOST_CPY_REP"))
		newBe : BaseEntity()
	  
     then
 		System.out.println("IS_QA_HOST_CPY_REP: Rule fired" );
 		System.out.println("IS_QA_HOST_CPY_REP: newBe = " + newBe.getCode()); 
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
 		
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_HOST_CPY_REP", "true"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS_COLOR", "#FF9100"));
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode(), "PRI_PROFILE", "InComplete"));


		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		
		String linkedHC = user.getValue("LNK_HOST_COMPANY", null);
		System.out.println("linkedHC = " + linkedHC);
		if (linkedHC != null && !linkedHC.isEmpty()) {
			System.out.println("LNK_HOST_COMPANY present!");
		} else {
			/* CREATE EMPTY CPY FOR THE USER */
			System.out.println("NO HOST COMPANY SELECTED, CREATING ONE...");

			String uuid = UUID.randomUUID().toString().toUpperCase();
			String cpyCode = "CPY_"+uuid;
			beUtils.create(cpyCode, cpyCode);

			beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode(), "LNK_HOST_COMPANY", "[\""+cpyCode+"\"]"));
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), cpyCode, "PRI_IS_HOST_CPY", true));
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), cpyCode, "PRI_PROFILE", "InComplete"));
			/* get the company baseentity */
			BaseEntity companyBe = beUtils.getBaseEntityByCode(cpyCode);
			if(companyBe != null){

				/* get the name attribute of the company */
				String hcName = companyBe.getValue("PRI_NAME", null);	
				System.out.println("hcName  :: " + hcName);	

				/* save the company's name as PRI_ASSOC_HC attribute for person baseentity */
				if(hcName != null){
					Answer answerHC = new Answer(userToken.getUserCode(), newBe.getCode(), "PRI_ASSOC_HC", hcName);
					beUtils.saveAnswer(answerHC);
					VertxUtils.sendToFrontEnd(userToken, answerHC);

				} else {
					System.out.println("hcName is NULL");
				}
			} else {
				System.out.println("companyBe is NULL");
			}
		}
		
		
		/* Set up in Keycloak */
		
		
		
		String userStr = newBe.getCode();
		String[] userSplit = userStr.split("_");
		String userCode = userSplit[1];
		System.out.println("User "+user+" with userCode = "+userCode);
		
		String email = "stephenie.pulis-cassar@outcomelife.com.au";
		
		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					/*String userPassword = UUID.randomUUID().toString().substring(0,10);*/
					/* TODO HACK */
					if (true) {
						String userPassword = "password1";
						String userId = KeycloakUtils.updateUser(userCode,serviceToken.getToken(), serviceToken.getRealm(), email, firstname, lastname,  email, userPassword,"user", "users");
						userId = userId.toUpperCase();
						Answer keycloakId = new Answer(beUtils.getGennyToken().getUserCode(),newBe.getCode(),"PRI_UUID",userId);
						beUtils.saveAnswer(keycloakId);
						System.out.println("Created Quick Add User "+email+" in Keycloak with id = "+userId + " and password:" +userPassword);
					} else {
					     System.out.println("KEYCLOAK QUICK ADD USER CREATION DISABLED IN RULE IS_INTERN");
					}
				}
			}
		}
		


		String endPoint = GennySettings.projectUrl + "/v7/notes";
		/*String endPoint = "https://internmatch-cyrus.gada.io/v7/notes";*/
		
		String tag = "ni";
		
		QwandaUtils.apiPostNote(endPoint, userToken.getUserCode(), tag, userToken.getUserCode(), "Added an Intern: " + firstname, serviceToken.getToken());
		
		System.out.println("I just posted the note");
		System.out.println("Note endPoint: " +endPoint);
		System.out.println("Note userToken.getUserCode(): " +userToken.getUserCode());


		/* Send email to Intern? */
		
		System.out.println("ABOUT TO SEND THE EMAIL OR MAYBE NOT??");
		String rawSendEmail = "";
		
		if (user != null) {
				rawSendEmail = user.getValue("LNK_SEND_EMAIL",null);
				System.out.println("rawSendEmail: " +rawSendEmail);
		}
		
		if (rawSendEmail != null) {
		
				if (rawSendEmail.equals("SEL_YES")) {
		
		
						BaseEntity project = beUtils.getBaseEntityByCode("PRJ_"+ serviceToken.getRealm().toUpperCase());
						
						String token = KeycloakUtils.getImpersonatedToken(serviceToken.getKeycloakUrl(), serviceToken.getRealm(), project, userCode, serviceToken.getToken());
						System.out.println("token: " + token);
						
				
						/*String user_email = "hello@outcome.life";*/
						
						/*String url = "https://internmatch-dev.gada.io/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX0ZJTklTSF9IT1NUX0NQWV9SRVA=";*/
						String url = GennySettings.projectUrl+"/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX0ZJTklTSF9IT1NUX0NQWV9SRVA=";
						System.out.println("url: " + url);
						
						
						url = url +"?token=" + token;
						System.out.println("url: " + url);
						
				
						/*String user_email = "c.pyke85@gmail.com";*/
						String subject = "You have been registered on InternMatch";
						String template_id = "d-6c43211b9b934cb6abaceea171f32e09";
				
						System.out.println("email: " + email);
						System.out.println("subject: " + subject);
						System.out.println("template_id: " + template_id);
						
						
						HashMap<String, String> templateData = new HashMap<String, String>();
				    	templateData.put("HostCompanyRep", firstname);
				    	templateData.put("url", url);
				
						EmailHelper.sendGrid(beUtils, email, subject, template_id, templateData);
				}
		}
		
		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		
		retract(newBe)
	
end
