package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.GennySettings;

import java.util.List;
import java.util.ArrayList;

rule "IS_QA_AGENT"
    ruleflow-group 'IsQuickAdd'
    no-loop true
    salience 1000 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("QA_AGENT"))
		newBe : BaseEntity()

	  
     then
 		System.out.println("IS_QA_AGENT: Rule fired" );
 		System.out.println("IS_QA_AGENT: newBe = " + newBe.getCode()); 
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
 		
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), user.getCode() ,"PRI_IS_AGENT", "true"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS", "PENDING"));

		String linkedAgency = user.getValue("LNK_AGENCY", null);
		System.out.println("linkedAgency = " + linkedAgency);
		if (linkedAgency != null && !linkedAgency.isEmpty()) {
			System.out.println("LNK_AGENCY present!");
		} else {
			/* CREATE EMPTY CPY FOR THE USER */
			System.out.println("NO AGENCY SELECTED, CREATING ONE...");

			String uuid = UUID.randomUUID().toString().toUpperCase();
			String cpyCode = "CPY_"+uuid;
			beUtils.create(cpyCode, cpyCode);

			beUtils.saveAnswer(new Answer(userToken.getUserCode(), user.getCode(), "LNK_AGENCY", "[\""+cpyCode+"\"]"));
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), cpyCode, "PRI_PROFILE", "Incomplete"));
		}
		
		
		/* Set up in Keycloak */
		
		String name = user.getValue("PRI_NAME",null);
		
		String userStr = newBe.getCode();
		String[] userSplit = userStr.split("_");
		String userCode = userSplit[1];
		System.out.println("User "+user+" with userCode = "+userCode);
		
		String email = "stephenie.pulis-cassar@outcomelife.com.au";
		
		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					/*String userPassword = UUID.randomUUID().toString().substring(0,10);*/
					/* TODO HACK */
					if (true) {
						String userPassword = "password1";
						String userId = KeycloakUtils.updateUser(userCode,serviceToken.getToken(), serviceToken.getRealm(), email, firstname, lastname,  email, userPassword,"user", "users");
						userId = userId.toUpperCase();
						Answer keycloakId = new Answer(beUtils.getGennyToken().getUserCode(),newBe.getCode(),"PRI_UUID",userId);
						beUtils.saveAnswer(keycloakId);
						System.out.println("Created User "+email+" in Keycloak with id = "+userId + " and password:" +userPassword);
					} else {
					     System.out.println("KEYCLOAK USER CREATION DISABLED IN RULE IS_AGENT");
					}
				}
			}
		}
	
	
		String endPoint = GennySettings.projectUrl + "/v7/notes";
		/*String endPoint = "https://internmatch-cyrus.gada.io/v7/notes";*/
		
		String tag = "ni";
		
		QwandaUtils.apiPostNote(endPoint, userToken.getUserCode(), tag, userToken.getUserCode(), "Added an Agent: " + name, serviceToken.getToken());
		
		System.out.println("I just posted the note");
		System.out.println("Note endPoint: " +endPoint);
		System.out.println("Note userToken.getUserCode(): " +userToken.getUserCode());
		System.out.println("Note newBe.getCode(): " +newBe.getCode());
		
		
		/* Send email to Intern? */
		
		System.out.println("ABOUT TO SEND THE EMAIL OR MAYBE NOT??");
		String rawSendEmail = "";
		
		if (user != null) {
				rawSendEmail = user.getValue("LNK_SEND_EMAIL",null);
				System.out.println("rawSendEmail: " +rawSendEmail);
		}
		
		if (rawSendEmail != null) {
		
				if (rawSendEmail.equals("SEL_YES")) {
		
						BaseEntity project = beUtils.getBaseEntityByCode("PRJ_"+ serviceToken.getRealm().toUpperCase());
						
						String token = KeycloakUtils.getImpersonatedToken(serviceToken.getKeycloakUrl(), serviceToken.getRealm(), project, userCode, serviceToken.getToken());
						System.out.println("token: " + token);
					
				
						/*String user_email = "hello@outcome.life";*/
						
						/*String url = "https://internmatch-dev.gada.io/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX0ZJTklTSF9BR0VOVA==";*/
						String url = GennySettings.projectUrl+"/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX0ZJTklTSF9BR0VOVA==";
						System.out.println("url: " + url);
						
						
						url = url +"?token=" + token;
						System.out.println("url: " + url);
						
				
						/*String user_email = "c.pyke85@gmail.com";*/
						String subject = "You have been registered on InternMatch";
						String template_id = "d-8212002ccd994d8c91da80d638cc71ba";
				
				
						System.out.println("email: " + email);
						System.out.println("subject: " + subject);
						System.out.println("template_id: " + template_id);
						
						HashMap<String, String> templateData = new HashMap<String, String>();
				    	templateData.put("intern", firstname);
				    	templateData.put("url", url);
				
						EmailHelper.sendGrid(beUtils, email, subject, template_id, templateData);
					}
		}
		
		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		
		retract(newBe)
	
end
