package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.UUID;
import life.genny.qwandautils.GennySettings;

import java.util.List;
import java.util.ArrayList;

rule "IS_QA_EDU_PRO_REP"
    ruleflow-group 'IsQuickAdd'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("QA_EDU_PRO_REP"))
		newBe : BaseEntity()

	  
     then
 		System.out.println("IS_QA_EDU_PRO_REP: Rule fired" );
 		System.out.println("IS_QA_EDU_PRO_REP: newBe = " + newBe.getCode()); 
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
    
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_EDU_PRO_REP", "true"));

		
		newBe = beUtils.getBaseEntityByCode(newBe.getCode());
		
		String linkedEP = newBe.getValue("LNK_EDU_PROVIDER", null);
		System.out.println("linkedEP = " +linkedEP);
		if (linkedEP != null) {
				String assocEPCode = linkedEP.replace("\"", "").replace("[", "").replace("]", "");
				System.out.println("assocEPCode = " +assocEPCode);
				
				BaseEntity assocEPBe = beUtils.getBaseEntityByCode(assocEPCode);
				System.out.println("assocEPBe: " + assocEPBe);
				
				String assocEP = assocEPBe.getValue("PRI_NAME", null);
				System.out.println("assocEP: " + assocEP);
				
				if (assocEP != null) {
 						beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_ASSOC_EP", assocEP));
						beUtils.createLink(assocEPBe.getCode(), newBe.getCode(), "LNK_CPY", "EDU_PRO_REP", 1.0);
 				}
		}
		
		/* Set up in Keycloak */
		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		String userStr = newBe.getCode();
		String[] userSplit = userStr.split("_");
		String userCode = userSplit[1];
		System.out.println("User "+user+" with userCode = "+userCode);
		
		
		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				String email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					/*String userPassword = UUID.randomUUID().toString().substring(0,10);*/
					String userPassword = "password1";
						String userId = KeycloakUtils.updateUser(userCode,serviceToken.getToken(), serviceToken.getRealm(), email, firstname, lastname,  email, userPassword,"user", "users");
					userId = userId.toUpperCase();
					Answer keycloakId = new Answer(beUtils.getGennyToken().getUserCode(),newBe.getCode(),"PRI_UUID",userId);
					beUtils.saveAnswer(keycloakId);
					System.out.println("Created User "+email+" in Keycloak with id = "+userId + " and password:" +userPassword);
				}
			}
		}
		
		String endPoint = GennySettings.projectUrl + "/v7/notes";
		/*String endPoint = "https://internmatch-cyrus.gada.io/v7/notes";*/
		
		String tag = "ni";
		
		QwandaUtils.apiPostNote(endPoint, userToken.getUserCode(), tag, userToken.getUserCode(), "Added an Education Provider Rep: " + firstname , serviceToken.getToken());
		
		System.out.println("I just posted the note");
		System.out.println("Note endPoint: " +endPoint);
		System.out.println("Note userToken.getUserCode(): " +userToken.getUserCode());

		
		/* Send email to EPR */
		
		
		BaseEntity project = beUtils.getBaseEntityByCode("PRJ_"+ serviceToken.getRealm().toUpperCase());
		
		String token = KeycloakUtils.getImpersonatedToken(serviceToken.getKeycloakUrl(), serviceToken.getRealm(), project, userCode, serviceToken.getToken());
		System.out.println("token: " + token);
		

		/*String user_email = "hello@outcome.life";*/
		
		/*String url = "https://internmatch-dev.gada.io/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX0ZJTklTSF9FRFVfUFJPX1JFUA==";*/
		String url = GennySettings.projectUrl+"/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX0ZJTklTSF9FRFVfUFJPX1JFUA==
";
		System.out.println("url: " + url);
		
		
		url = url +"?token=" + token;
		System.out.println("url: " + url);
		

		String user_email = "c.pyke85@gmail.com";
		String subject = "You have been registered on InternMatch";
		String template_id = "d-b569cb15814e4f34b5a57c760b9f38f8";


		System.out.println("user_email: " + user_email);
		System.out.println("subject: " + subject);
		System.out.println("template_id: " + template_id);
		
		
		HashMap<String, String> templateData = new HashMap<String, String>();
    	templateData.put("EduProRep", firstname);
    	templateData.put("url", url);

		EmailHelper.sendGrid(beUtils,user_email, subject, template_id, templateData);
	
		
		
		output.setTypeOfResult("NONE");
  		output.setResultCode("NONE");  /* dont display anything new */
		
		retract(newBe)
	
end
