package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;
import life.genny.qwanda.VisualControlType;

rule "FRM_CARD_BOTTOM"
  ruleflow-group 'GenerateFrames'

  when
    not  Frame3(code == "FRM_CARD_BOTTOM")
    serviceToken : GennyToken( code == "PER_SERVICE")

  then
    System.out.println(" Generate FRM_CARD_BOTTOM Rule  "+serviceToken.getUserCode());

    Frame3 frame = Frame3.builder("FRM_CARD_BOTTOM")
                  .addTheme("THM_PANEL_ALIGN_TOP_LEFT", ThemePosition.CENTRE, serviceToken).end()
                  .question("QUE_TEST_CARD_BOTTOM_GRP")
                    .addTheme("THM_WIDTH_DYNAMIC", serviceToken).vcl(VisualControlType.VCL_INPUT).end()
                    .addTheme("THM_WIDTH_100_PERCENT", serviceToken).vcl(VisualControlType.GROUP).end()
                    .addTheme("THM_JUSTIFY_CONTENT_CENTRE", serviceToken).vcl(VisualControlType.GROUP_CLICKABLE_WRAPPER).end()
                    .addTheme("THM_EXPANDABLE", serviceToken).end()
                  .end()
                  .build();
    frame.setRealm(serviceToken.getRealm());
    insert (frame);

    /* Process and save to cache */
    FrameUtils2.toMessage(frame, serviceToken);
end