package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.Layout.LayoutPosition;

rule "Ask User Role"
    when
        rules: QRules( 	isState("ASK_USER_ROLE") &&
						!isState("LOOP_ASK_USER_ROLE")	)
     then
     	rules.header();
        rules.setState("LOOP_ASK_USER_ROLE");
        
        String rolesSelectionUri = "pages/registration/role/";
        
        BaseEntity layout = rules.getLayout(rolesSelectionUri);
        
        /* creating a link between the main-frame and the layout */
        if(layout != null) {
        		rules.baseEntity.createLink("FRM_MAIN", layout.getCode(), "LNK_LAYOUT", "CENTRE", 1.0);
        }
        
        /* ask the role group questions */                    
        rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_BUYER_GRP", false, "FRM_CONTENT", LayoutPosition.CENTRE); 
        
    	rules.footer();
end
