package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.Layout.LayoutPosition;

rule "Ask User Role"
    when
        rules: QRules( 	isState("ASK_USER_ROLE") &&
						!isState("LOOP_ASK_USER_ROLE")	)
     then
     	rules.header();
        rules.setState("LOOP_ASK_USER_ROLE");

        /* Send Sublayout Role Selection */
		rules.sendSublayout("ROLE_SELECTION", "registration/role_selection.json", null, false);

        /* TODO: to remove. test for the guys */
        /* rules.sendQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_BUYER_GRP"); */
        rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_BUYER_GRP", false, "FRM_CONTENT", LayoutPosition.CENTRE);
        /* rules.navigateTo("/registration/role"); */

    	rules.footer();
end
