package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwandautils.GennySettings;

import java.security.SecureRandom;
import java.util.stream.Collectors;

import java.util.List;
import java.util.ArrayList;
import life.genny.message.QMessageGennyMSG;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.KeycloakUtils;

rule "IS_ADMIN"
    ruleflow-group 'IsBaseEntity'
    no-loop true
    salience 1000 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("ADMIN"))
		newBe : BaseEntity()
		beUtils : BaseEntityUtils()
    then
 		System.out.println("IS_ADMIN: Rule fired" );
 		System.out.println("IS_ADMIN: newBe = " + newBe.getCode());

 		List<Answer> answers = new ArrayList<>();

 		/* answers.add(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_ADMIN", "true")); */
 		/* answers.add(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS", "REGISTERED")); */
 		/* answers.add(new Answer(userToken.getUserCode(), newBe.getCode(), "PRI_STATUS_COLOR","#5cb85c")); */

		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		String userCode = newBe.getCode().split("_")[1];
		System.out.println("User "+user+" with userCode = "+userCode);

		String userId = "";

		/* Set up in Keycloak */
		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				String email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					/* TODO HACK */
					if (true) {
                        /* Update Email and Name, and set Random Password in Keycloak */
                        KeycloakUtils.updateUserDetails(beUtils, newBe);
                        String password = KeycloakUtils.generateRandomPassword(beUtils, newBe);

                        QMessageGennyMSG tempPasswordMsg = new QMessageGennyMSG.Builder("MSG_TEMP_PASSWORD")
                            .addRecipient(newBe)
                            .addContext("PASSWORD", password)
                            .addContext("URL:ENCODE", "")   /* URL: projectUrl/home */
                            .addContext("BCC", "PRJ_INTERNMATCH")
                            .setUtils(beUtils)
                            .send();

                        System.out.println("Sendgrid msg: "+ JsonUtils.toJson(tempPasswordMsg));
                        System.out.println("Sendgrid email sent to Admin!!");
					} else {
					     System.out.println("KEYCLOAK USER CREATION DISABLED IN RULE IS_ADMIN");
					}
				}
			}
		}

		output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */

  	    beUtils.saveAnswers(answers);

		retract(newBe)
end
