package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.GennySettings;

import java.util.List;
import java.util.ArrayList;

rule "IS_ADMIN"
    ruleflow-group 'IsBaseEntity'
    no-loop true
    salience 1000 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("ADMIN"))
		newBe : BaseEntity()
		beUtils : BaseEntityUtils()
	  
     then
 		System.out.println("IS_ADMIN: Rule fired" );
 		System.out.println("IS_ADMIN: newBe = " + newBe.getCode());

 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_ADMIN", "true"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS", "REGISTERED"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode(), "PRI_STATUS_COLOR","#5cb85c"));

		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		String userCode = newBe.getCode().split("_")[1];
		System.out.println("User "+user+" with userCode = "+userCode);

		/* Set up in Keycloak */
		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				String email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					/*String userPassword = UUID.randomUUID().toString().substring(0,10);*/
					/* TODO HACK */
					if (true) {
						String userPassword = "password1";
						String userId = KeycloakUtils.updateUser(userCode,serviceToken.getToken(), serviceToken.getRealm(), email, firstname, lastname,  email, userPassword,"user", "users");
						userId = userId.toUpperCase();
						beUtils.saveAnswer(new Answer(beUtils.getGennyToken().getUserCode(),newBe.getCode(),"PRI_UUID",userId));
						System.out.println("Created User "+email+" in Keycloak with id = "+userId + " and password:" +userPassword);
					} else {
					     System.out.println("KEYCLOAK USER CREATION DISABLED IN RULE IS_ADMIN");
					}
				}
			}
		}

		TableUtils.searchTable(beUtils,"ADMIN", true, "PRI_CODE", newBe.getCode());

		output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */

		retract(newBe)
end
