package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.UUID;
import life.genny.qwandautils.GennySettings;

import java.util.List;
import java.util.ArrayList;

rule "IS_EDU_PRO_REP"
    ruleflow-group 'IsBaseEntity'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("EDU_PRO_REP"))
		newBe : BaseEntity()

	  
     then
 		System.out.println("IS_EDU_PRO_REP: Rule fired" );
 		System.out.println("IS_EDU_PRO_REP: newBe = " + newBe.getCode()); 
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
    
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_EDU_PRO_REP", "true"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS", "ACTIVE"));
		
		newBe = beUtils.getBaseEntityByCode(newBe.getCode());
		
		String linkedEP = newBe.getValue("LNK_EDU_PROVIDER", null);
		System.out.println("linkedEP = " +linkedEP);
		if (linkedEP != null) {
				String assocEPCode = linkedEP.replace("\"", "").replace("[", "").replace("]", "");
				System.out.println("assocEPCode = " +assocEPCode);
				
				BaseEntity assocEPBe = beUtils.getBaseEntityByCode(assocEPCode);
				System.out.println("assocEPBe: " + assocEPBe);
				
				String assocEP = assocEPBe.getValue("PRI_NAME", null);
				System.out.println("assocEP: " + assocEP);
				
				if (assocEP != null) {
 						beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_ASSOC_EP", assocEP));
 				}
		}
		
		/* Set up in Keycloak */
		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		String userStr = newBe.getCode();
		String[] userSplit = userStr.split("_");
		String userCode = userSplit[1];
		System.out.println("User "+user+" with userCode = "+userCode);
		
		
		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				String email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					/*String userPassword = UUID.randomUUID().toString().substring(0,10);*/
					String userPassword = "password1";
						String userId = KeycloakUtils.updateUser(userCode,serviceToken.getToken(), serviceToken.getRealm(), email, firstname, lastname,  email, userPassword,"user", "users");
					userId = userId.toUpperCase();
					Answer keycloakId = new Answer(beUtils.getGennyToken().getUserCode(),newBe.getCode(),"PRI_UUID",userId);
					beUtils.saveAnswer(keycloakId);
					System.out.println("Created User "+email+" in Keycloak with id = "+userId + " and password:" +userPassword);
				}
			}
		}
		
		String endPoint = GennySettings.projectUrl + "/v7/notes";
		/*String endPoint = "https://internmatch-cyrus.gada.io/v7/notes";*/
		
		String tag = "ni";
		
		QwandaUtils.apiPostNote(endPoint, userToken.getUserCode(), tag, userToken.getUserCode(), "Added an Education Provider Rep: " + firstname , serviceToken.getToken());
		
		System.out.println("I just posted the note");
		System.out.println("Note endPoint: " +endPoint);
		System.out.println("Note userToken.getUserCode(): " +userToken.getUserCode());


		/* send the detail sbe */
		long totalTime = TableUtils.searchTable(beUtils,"EDU_PRO_REP", true, "PRI_CODE", newBe.getCode());
		System.out.println("total took " + (totalTime) + " ms"); 
		
		output.setTypeOfResult("NONE");
  	output.setResultCode("NONE");  /* dont display anything new */
		
		retract(newBe)
	
end
