package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.UUID;
import life.genny.qwandautils.GennySettings;

import java.security.SecureRandom;
import java.util.stream.Collectors;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.message.QMessageGennyMSG;

rule "IS_HOST_CPY_REP"
    ruleflow-group 'IsBaseEntity'
    no-loop true
    salience 1
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("HOST_CPY_REP"))
		newBe : BaseEntity()
    then
 		System.out.println("IS_HOST_CPY_REP: Rule fired" );
 		System.out.println("IS_HOST_CPY_REP: newBe = " + newBe.getCode());

 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

 		List<Answer> answers = new ArrayList<>();

 		/* answers.add(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_HOST_CPY_REP", "true")); */
 		/* answers.add(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS", "ACTIVE")); */


		/* Refresh the BaseEntity because reasons... */
 		newBe = beUtils.getBaseEntityByCode(newBe.getCode());

 		String assocHC = newBe.getValue("LNK_INTERN_SUPERVISOR", null);
		System.out.println("assocHC = " + assocHC);
		if (assocHC != null) {
			assocHC = assocHC.replace("\"", "").replace("[", "").replace("]", "");
			System.out.println("assocHC = " +assocHC);

			/* ========== Add the HCR to the HC ========== */
			beUtils.quantumLink(userToken.getUserCode(), assocHC, newBe.getCode(), "LNK_HCRS");
		}


		/* Set up in Keycloak */
		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		String userStr = newBe.getCode();
		String[] userSplit = userStr.split("_");
		String userCode = userSplit[1];
		System.out.println("User "+user+" with userCode = "+userCode);

		String userId = "";

		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				String email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					String profile = user.getValue("PRI_PROFILE", null);
					if (profile != null && profile.equals("Incomplete")) {
						System.out.println("User was already Quick added, not setting new Password!");
					} else {
                        /* Update Email and Name, and set Random Password in Keycloak */
                        KeycloakUtils.updateUserDetails(beUtils, newBe);
                        String password = KeycloakUtils.generateRandomPassword(beUtils, newBe);

                        QMessageGennyMSG tempPasswordMsg = new QMessageGennyMSG.Builder("MSG_TEMP_PASSWORD")
                            .addRecipient(newBe)
                            .addContext("PASSWORD", password)
                            .addContext("URL:ENCODE", "")   /* URL: projectUrl/home */
                            .addContext("BCC", "PRJ_INTERNMATCH")
                            .setUtils(beUtils)
                            .send();

                        System.out.println("Sendgrid msg: "+ JsonUtils.toJson(tempPasswordMsg));
                        System.out.println("Sendgrid email sent to Host Company Rep!!");
					}
				}
			}
		}



		String endPoint = GennySettings.projectUrl + "/v7/notes";
		/*String endPoint = "https://internmatch-cyrus.gada.io/v7/notes";*/

		String tag = "System";
		String userName = "System";
		String userImage = "";

		QwandaUtils.apiPostNote(endPoint, userToken.getUserCode(), newBe.getCode(), "Completed profile for Host Company Rep account", tag, userName, userImage, serviceToken.getToken());

		System.out.println("I just posted the note");
		System.out.println("Note endPoint: " +endPoint);
		System.out.println("Note userToken.getUserCode(): " +userToken.getUserCode());
		System.out.println("Note newBe.getCode(): " +newBe.getCode());

		BaseEntity cpyRepBe = beUtils.getBaseEntityByCode(newBe.getCode());
		
		if(cpyRepBe != null){
			
			QDataBaseEntityMessage cpyRepBeMsg = new QDataBaseEntityMessage(cpyRepBe);
			cpyRepBeMsg.setToken(userToken.getToken());
			VertxUtils.writeMsg("webcmds", JsonUtils.toJson(cpyRepBeMsg));
		}


		/* send the detail sbe */
		/* long totalTime = TableUtils.searchTable(beUtils,"HOST_CPY_REP", true, "PRI_CODE", newBe.getCode());
		System.out.println("total took " + (totalTime) + " ms");  */
		
		if(cpyRepBe != null){
			
			QDataBaseEntityMessage cpyRepBeMsg = new QDataBaseEntityMessage(cpyRepBe);
			cpyRepBeMsg.setToken(userToken.getToken());
			VertxUtils.writeMsg("webcmds", JsonUtils.toJson(cpyRepBeMsg));
		}

		beUtils.saveAnswers(answers);	
		
		retract(newBe);
	
end
