package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "IS_REF_PART"
    ruleflow-group 'IsBaseEntity'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("RefPartner"))
		newBe : BaseEntity()

	  
     then
 		System.out.println("IS_REF_PART: Rule fired" );
 		System.out.println("IS_REF_PART: newBe = " + newBe.getCode()); 
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		Answer answer = new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_REF_PART", "true");
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);
 		beUtils.saveAnswer(answer);

		System.out.println("IS_REF_PART: Answer = " + answer); 
		
		
		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		String name = user.getValue("PRI_NAME",null);
	
		/*String endPoint = GennySettings.bridgeUrl + "/v7/notes";*/
		String endPoint =  "https://internmatch-chris1.gada.io/v7/notes";
		
		System.out.println("Note endPoint: " +endPoint);
		String tag = "ni";
		
		QwandaUtils.apiPostNote(endPoint, userToken.getUserCode(), tag, newBe.getCode(), name + " has been created as a Referral Partner with Base Entity Code: " + newBe.getCode(), serviceToken.getToken());
		System.out.println("I just posted the note");
		
		output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */
		
		retract(newBe)
	
end
