package life.genny.rules;



global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;

rule "FRM_DETAIL_VIEW_PICTURE"
    ruleflow-group 'GenerateFrames'

    when
		not  Frame3(code == "FRM_DETAIL_VIEW_PICTURE")
		serviceToken : GennyToken( code == "PER_SERVICE")
		
    then
    	System.out.println("   Generate FRM_DETAIL_VIEW_PICTURE Rule  "+serviceToken.getUserCode());

 	  	Frame3 frame = Frame3.builder("FRM_DETAIL_VIEW_PICTURE")
						.addTheme("THM_PADDING_RIGHT_10", ThemePosition.WRAPPER, serviceToken).end()
						.question("QUE_DETAIL_VIEW_IMAGE_GRP")
						.targetAlias("PER_USER1")
							/*.addTheme(THM_DETAIL_VIEW_INPUT_FIELD).vcl(VisualControlType.INPUT_FIELD).dataType(dtt_image).end()*/
							.addTheme("THM_FORM_IMAGE_RESTRICTIONS",serviceToken).vcl(VisualControlType.VCL_INPUT).end()
							.addTheme("THM_DETAIL_VIEW_IMAGE_SIZE",serviceToken).vcl(VisualControlType.INPUT_SELECTED).end()
							/* NEW THEMES */
							.addTheme("THM_BORDER_RADIUS_50", serviceToken).vcl(VisualControlType.INPUT_FIELD).weight(1.0).end()
							.addTheme("THM_HEADER_PROFILE_PICTURE", serviceToken).vcl(VisualControlType.INPUT_SELECTED).weight(1.0).end()
							.addTheme("THM_PROFILE_IMAGE", serviceToken).vcl(VisualControlType.INPUT_SELECTED).weight(1.0).end()
							.addTheme("THM_IMAGE_PLACEHOLDER_PERSON", serviceToken).vcl(VisualControlType.INPUT_PLACEHOLDER).weight(1.0).end()
						.end()
						
						.build();

			frame.setRealm(serviceToken.getRealm());
			insert (frame);
			/* Process and save to cache */
			/*FrameUtils2.toMessage(frame, serviceToken);*/
	end
