package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;
import life.genny.qwanda.VisualControlType;


rule "FRM_CARD_COMPANY"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_CARD_COMPANY")
      serviceToken : GennyToken( code == "PER_SERVICE")
      FRM_DUMMY : Frame3 ( code == "FRM_DUMMY" )
      FRM_COMPANY_ABN : Frame3 ( code == "FRM_COMPANY_ABN" )
      FRM_COMPANY_ACN : Frame3 ( code == "FRM_COMPANY_ACN" )
      FRM_COMPANY_LOGO : Frame3 ( code == "FRM_COMPANY_LOGO" )
      FRM_COMPANY_WEBSITE : Frame3 ( code == "FRM_COMPANY_WEBSITE" )
      FRM_LEGAL_NAME : Frame3 ( code == "FRM_LEGAL_NAME" )
      FRM_TRADING_NAME : Frame3 ( code == "FRM_TRADING_NAME" )

    then
     System.out.println("   Generate FRM_CARD_COMPANY Rule  "+serviceToken.getUserCode());

 	 Frame3 frame = Frame3.builder("FRM_CARD_COMPANY")
                                .addTheme("THM_CARD", ThemePosition.WRAPPER, serviceToken).end()
                                .addFrame(FRM_COMPANY_LOGO, FramePosition.NORTH).end()
                                .addFrame(FRM_LEGAL_NAME, FramePosition.NORTH).end()
                                .addFrame(FRM_TRADING_NAME, FramePosition.NORTH).end()
                                .addFrame(FRM_COMPANY_ABN, FramePosition.NORTH).end()
                                .addFrame(FRM_COMPANY_ACN, FramePosition.NORTH).end()
                                .addFrame(FRM_COMPANY_WEBSITE, FramePosition.NORTH).end()
                                .build();
                
	frame.setRealm(serviceToken.getRealm());
						
	insert (frame);
	
	/* Process and save to cache */
	FrameUtils2.toMessage(frame, serviceToken);

end
