package life.genny.rules;



global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;
import life.genny.qwanda.VisualControlType;


rule "FRM_CARD_PRODUCT"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_CARD_PRODUCT")
      serviceToken : GennyToken( code == "PER_SERVICE")
      FRM_DUMMY : Frame3 ( code == "FRM_DUMMY" )
      FRM_INTERNSHIP_TITLE : Frame3 ( code == "FRM_INTERNSHIP_TITLE" )
      FRM_INTERNSHIP_DESCRIPTION : Frame3 ( code == "FRM_INTERNSHIP_DESCRIPTION" )
      FRM_INTERNSHIP_START_DATE : Frame3 ( code == "FRM_INTERNSHIP_START_DATE" )
      FRM_INTERNSHIP_START_DURATION : Frame3 ( code == "FRM_INTERNSHIP_START_DURATION" )
      FRM_INTERNSHIP_INDUSTRY_AND_OCCUPATION : Frame3 ( code == "FRM_INTERNSHIP_INDUSTRY_AND_OCCUPATION" )

    then
     System.out.println("   Generate FRM_CARD_PRODUCT Rule  "+serviceToken.getUserCode());

 	 Frame3 frame = Frame3.builder("FRM_CARD_PRODUCT")
                                .addTheme("THM_CARD", ThemePosition.WRAPPER, serviceToken).end()
                              /*   .question("QUE_NAME_TWO")
                                        .addTheme("THM_FORM_LABEL_DEFAULT",serviceToken)
                                        .vcl(VisualControlType.VCL_WRAPPER)
                                        .end()
                                .end() */
                                .addFrame(FRM_INTERNSHIP_TITLE, FramePosition.NORTH).end()
                                .addFrame(FRM_INTERNSHIP_DESCRIPTION, FramePosition.NORTH).end()
                                .addFrame(FRM_INTERNSHIP_START_DATE, FramePosition.NORTH).end()
                                .addFrame(FRM_INTERNSHIP_START_DURATION, FramePosition.NORTH).end()
                                .addFrame(FRM_INTERNSHIP_INDUSTRY_AND_OCCUPATION, FramePosition.NORTH).end()
                                .build();
                
	frame.setRealm(serviceToken.getRealm());
						
	insert (frame);
	
	/* Process and save to cache */
	FrameUtils2.toMessage(frame, serviceToken);

end
