package life.genny.rules;

import life.genny.utils.OutputParam;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Answer;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.TableUtils;
import life.genny.utils.CacheSearchUtils;
import life.genny.qwandautils.GennySettings;
import life.genny.jbpm.customworkitemhandlers.ShowFrame;
import life.genny.qwanda.rule.RuleDetails;


rule "ATTRIBUTE_CHANGE_EVENT"
    ruleflow-group 'EventProcessing'
	salience 2
    no-loop
    when
			$message : QEventMessage(data.code matches "EVT_ATTRIBUTE_VALUE_CHANGE" )	
			userToken : GennyToken ( code != "PER_SERVICE" ) 
			serviceToken : GennyToken( code == "PER_SERVICE") 
			output : OutputParam( )
			ruleDetails : RuleDetails()
			beUtils : BaseEntityUtils()
    then
			System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing Event : " + $message );
			
  	       output.setTypeOfResult("NONE");
  	       output.setResultCode("NONE");  /* dont display anything new */
  	     
  	       retract( $message);
  	     /*  update(output); */
end
