package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;

rule "SBE_INTERNSHIP_DETAIL_VIEW"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
	
       not  SearchEntity (code == "SBE_INTERNSHIP_DETAIL_VIEW")
        serviceToken : GennyToken( code == "PER_SERVICE")
        
     then
     	System.out.println("   Generate SBE_INTERNSHIP_DETAIL_VIEW ");
		
		SearchEntity searchBE = new SearchEntity("SBE_INTERNSHIP_DETAIL_VIEW", "Search")
				.addFilter("PRI_CODE", SearchEntity.StringFilter.EQUAL, "BEG_INTERNSHIP_ONE")
				.addSort("PRI_CREATED", "Created", SearchEntity.Sort.DESC)
				.addColumn("PRI_ADDRESS_FULL", "Address")
				.addColumn("PRI_START_DATE", "Starts")
				.addColumn("LNK_INTERNSHIP_DURATION", "Duration")
				.addColumn("PRI_INTERNSHIP_DESCRIPTION", "Internship Description")
				.addColumn("PRI_POSITION_DESCRIPTION", "Position Description")
				.addColumn("PRI_INTERNSHIP_SKILLS", "Prefered Skills")
				.addColumn("PRI_INTERNSHIP_LEARNING_OUTCOMES", "Learning Outcome")
				.addColumn("PRI_SOFTWARE", "Software")
				.addColumn("PRI_CREATOR_NAME", "Representative")
				.addColumn("PRI_EMAIL", "Representative Email")
				.addColumn("PRI_MOBILE", "Representative Mobile")
				.setPageStart(0).setPageSize(10);
   	     
  	     searchBE.setRealm(serviceToken.getRealm());
  	     
 		 insert(searchBE);
  		 VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());
end
