package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "REJECT"
    ruleflow-group 'CardStatus'
    no-loop true
    salience 1 
    when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity()
		output : OutputParam()
		statusCode : String(statusCode.equals("Reject"))

	  
     then
 		System.out.println("REJECT: Rule fired" ); 
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		Answer answer = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_CARD_STATUS","REJECT");
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);
 		beUtils.saveAnswer(answer);
 		
		
		System.out.println("REJECT: Answer = " + answer);	
		System.out.println("REJECT: newApplication = " + newApplication);
		
		
	/*  Set the attribute code and value to output */
		output.setResultCode(answer.getAttributeCode());
		output.setTargetCode(answer.getValue());


		retract(newApplication)
		retract(statusCode)
		
end
