package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "TEMP_RULE"
    ruleflow-group 'CardStatus'
    no-loop true
    salience 1 
    when

	  
     then
 		System.out.println("TEMP_RULE: This would trigger the Journal to appear" ); 
 	
end
