package life.genny.rules;

rule "USR_SESSION_PROCESS_DATA"
    ruleflow-group 'Process Data'
    lock-on-active true
    when
      $process : WorkflowProcessInstance( ) 

     then
     log.info("Send Project");
 
	QRules rules = (QRules)$process.getVariable("rules");  
	BaseEntity project = rules.getProject();

        if(project != null) {
            log.info("Sending project - "+project.getCode());
            rules.publishCmd(project, "PROJECT");
        }

end
