package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;

rule "DEFAULT 1"
    ruleflow-group 'RulesActionCacheDefault'
    lock-on-active
    salience -10000
    no-loop true
    when
		userToken : GennyToken ( )
		//serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		qMessage : QEventMessage( data.code == "actionCacheLayoutMessage" )
    then
		System.out.println("RulesActionCache - DEFAULT 1 - Triggerred : " + userToken.getUserCode());
		System.out.println("Signal Content: " + qMessage);
		output.setTypeOfResult("NONE");
		output.setResultCode("InstructFrontendToggleFrame");
		output.setTargetCode("");
end