package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;

rule "FORM_1"
    ruleflow-group 'GenerateForms'
    no-loop true
    when
      $process : WorkflowProcessInstance( ) 
     then
     log.info("Generate Form 1 Rule");
 
	GennyToken serviceToken = (GennyToken)$process.getVariable("serviceToken"); 
	log.info("Genny Token Service Code2 = "+serviceToken.getCode());
/*	$process.setVariable( "dynamicGroupId","analyst" ); 
	retract($process); */

end
