package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;

rule "TREE_ITEM_FORM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_.*" && data.parentCode == "QUE_FORM_VIEW_GRP" )
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
    then
	
		System.out.println("Processing Answer/Data : " + $message );
		System.out.println("Parent code :  " + $message.getData().getParentCode());
		output.setFormCode("FRM_"+ $message.getData().getCode(),"FRM_CONTENT");
		retract( $message);
end