package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Cards Tree Item - Step 1"
    when
        rules: QRules( isState("EVENT_BTN_CLICK") &&
                        isState("ROOT_QUE_GRP_ROOT_GRP") &&
                        isState("PARENT_QUE_GRP_ROOT_GRP") &&
                        isState("QUE_GRP_CARDS") &&
                        isState("TARGET_GRP_CARDS") &&
                        !isState("LOOP_TV_SELECT_GRP_CARDS"))
    then
        rules.header();
		rules.setState("LOOP_TV_SELECT_GRP_CARDS");

        rules.setState("TRIGGER_SEND_CARD");
        rules.footer();
    end