package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;

rule "Send Buckets For HC Rep"
	ruleflow-group 'BucketProcessing'
	salience 6
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
		beUtils : BaseEntityUtils()
		allowed : Allowed(code == "HOST_CPY_REP")

	then
		System.out.println("Send Buckets For HC Rep triggered");
		Boolean cache = true;

		BaseEntity userBe = beUtils.getBaseEntityByCode(userToken.getCode());
		if(userBe == null){
			System.out.println("userBe is null");
			return;
		}

		String companyCode = userBe.getValue("LNK_HOST_COMPANY", null);		
		if(companyCode == null){
			System.out.println("companyBe is null");
			return;
		}
		
    String[] codes = { 
      "APPLIED_APPLICATIONS",
      "SHORTLISTED_APPLICATIONS",
      "INTERVIEWED_APPLICATIONS",
      "OFFERED_APPLICATIONS",
      "PLACED_APPLICATIONS",
      "INPROGRESS_APPLICATIONS"
    };

    for (String code : codes){
      
      System.out.println("SBE_CODE   ::   " +code); 
			long totalTime = TableUtils.searchTable(beUtils,code, cache, "LNK_HOST_COMPANY", companyCode);
			System.out.println("total took " + (totalTime) + " ms"); 

    } 

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
end
