package life.genny.rules;

global org.apache.logging.log4j.Logger log;
import java.util.Map;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import life.genny.qwanda.ContextList;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;

rule "FRM_APPLICATION_DETAIL_VIEW"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_APPLICATION_DETAIL_VIEW")
      serviceToken : GennyToken( code == "PER_SERVICE")
      FRM_DETAIL_VIEW_TOP_CARD : Frame3 ( code == "FRM_DETAIL_VIEW_TOP_CARD" )
      FRM_DETAIL_VIEW_CARD : Frame3 ( code == "FRM_DETAIL_VIEW_CARD" )
      FRM_DETAIL_VIEW_TIMELINE : Frame3 (code == "FRM_DETAIL_VIEW_TIMELINE")
      
    then
        System.out.println("   Generates FRM_APPLICATION_DETAIL_VIEW Rule  "+serviceToken.getUserCode());
		
		/*
			Setting appropriate question code !!!!	
			For top FRM_DETAIL_VIEW_TOP_CARD send questions with groupCode QUE_DETAIL_VIEW_TOP_SUMMARY_GRP
			For FRM_DETAIL_VIEW_CARD send questions with groupCode QUE_INTERNSHIP_DETAIL_SUMMARY_GRP or change to desire question group code
		*/
		
		Frame3 appInternshipDetails =  Frame3.clone(FRM_DETAIL_VIEW_CARD) ;
		appInternshipDetails.setCode("FRM_APPLICATION_INTERNSHIP_DETAIL");
		
		/*Question code should be exactly same as the SBE questiongroup code*/
		appInternshipDetails.setQuestionCode("QUE_APP_INTERNSHIP_DETAIL_GRP");
		appInternshipDetails.getQuestionGroup().setCode("QUE_APP_INTERNSHIP_DETAIL_GRP");
		appInternshipDetails.getQuestionGroup().setTargetAlias("APP_APPLICATION_THREE");
		
		Frame3 appStudentDetails =  Frame3.clone(FRM_DETAIL_VIEW_CARD) ;
		appStudentDetails.setCode("FRM_APPLICATION_INTERN_DETAIL");
		appStudentDetails.setQuestionCode("QUE_APP_INTERN_DETAIL_GRP");
		appStudentDetails.getQuestionGroup().setCode("QUE_APP_INTERN_DETAIL_GRP");
		appStudentDetails.getQuestionGroup().setTargetAlias("APP_APPLICATION_THREE");
		
 	  	Frame3 FRM_APPLICATION_DETAIL_VIEW = Frame3.builder("FRM_APPLICATION_DETAIL_VIEW_CONTENT")
						.addTheme("THM_SCROLL_VERTICAL", ThemePosition.WRAPPER, serviceToken).end()
						.addTheme("THM_DETAIL_VIEW_BODY", ThemePosition.WRAPPER, serviceToken).end()
						.addTheme("THM_JUSTIFY_CONTENT_FLEX_START", ThemePosition.CENTRE, serviceToken).end()
						.addFrame(FRM_DETAIL_VIEW_TOP_CARD,FramePosition.CENTRE).end()
						.addFrame(appInternshipDetails, FramePosition.CENTRE).end()
						.addFrame(appStudentDetails, FramePosition.CENTRE).end()
						.addFrame(FRM_DETAIL_VIEW_TIMELINE, FramePosition.CENTRE).end()
						.build();
						
		Frame3 frame = Frame3.builder("FRM_APPLICATION_DETAIL_VIEW")
				.addFrame(FRM_APPLICATION_DETAIL_VIEW).end()
				.build();
				
		frame.setRealm(serviceToken.getRealm());
		insert (frame);
		
		/* Process and save to cache */
		SearchEntity searchBE = VertxUtils.getObject(serviceToken.getRealm(), "", "SBE_APPLICATION_INTERNSHIP_DETAIL",SearchEntity.class, serviceToken.getToken());	
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);
		TableUtils tableUtils = new TableUtils(beUtils);
		Set<QDataAskMessage> askSet = new HashSet<QDataAskMessage>();
		Map<String, ContextList> contextListMap = new HashMap<String, ContextList>();
		Map<String, QDataAskMessage> virtualAskMap = new HashMap<String, QDataAskMessage>();
		
		/* Fetching searh resutls and labels for internship detail */
		QDataBaseEntityMessage fetchResultMsg = tableUtils.fetchSearchResults(searchBE, serviceToken);
		Map<String, String> askLabels = tableUtils.getTableColumns(searchBE);
		List<Object> belist = new ArrayList<>(Arrays.asList(fetchResultMsg.getItems()));
		List<BaseEntity> results = (List<BaseEntity>) (List) belist;
		List<Ask> asks = TableUtils.generateQuestions(serviceToken, beUtils, results, askLabels, "PRJ_INTERNMATCH");

		/*  Ask Question code should be similar to the frame question code */
		Ask askInternshipDetail = asks.get(0);
		askInternshipDetail.setQuestionCode("QUE_APP_INTERNSHIP_DETAIL_GRP");
		askInternshipDetail.setName("Internship Details");
		
		/* Process and save to cache */
		virtualAskMap.put(askInternshipDetail.getQuestionCode(), new QDataAskMessage(askInternshipDetail));
		
		/* Fetching searh resutls and labels for intern detail*/
		searchBE = VertxUtils.getObject(serviceToken.getRealm(), "", "SBE_APPLICATION_INTERN_DETAIL",SearchEntity.class, serviceToken.getToken());
		fetchResultMsg = tableUtils.fetchSearchResults(searchBE, serviceToken);
		askLabels = tableUtils.getTableColumns(searchBE);
		belist = new ArrayList<>(Arrays.asList(fetchResultMsg.getItems()));
		results = (List<BaseEntity>) (List) belist;
		asks = TableUtils.generateQuestions(serviceToken, beUtils, results, askLabels, "PRJ_INTERNMATCH");
		
		/*  Ask Question code should be similar to the frame question code */
		Ask askInternDetail = asks.get(0);
		askInternDetail.setQuestionCode("QUE_APP_INTERN_DETAIL_GRP");
		askInternDetail.setName("Intern Details");
		
		/* Process and save to cache */
		virtualAskMap.put(askInternDetail.getQuestionCode(), new QDataAskMessage(askInternDetail));
		
		/* generating frame msg and saving to cache */
		FrameUtils2.toMessage(frame, serviceToken,askSet,contextListMap,virtualAskMap);
		
		VertxUtils.putObject(serviceToken.getRealm(), "", frame.getCode(), frame, serviceToken.getToken());
		System.out.println("Writing to cache");
		VertxUtils.writeCachedJson(serviceToken.getRealm(),"ASK_" + frame.getCode(), JsonUtils.toJson(askSet.toArray()),serviceToken.getToken());
		
	end
