package life.genny.rules;

import life.genny.utils.OutputParam;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Answer;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.TableUtils;
import life.genny.utils.CacheSearchUtils;
import life.genny.qwandautils.GennySettings;
import life.genny.jbpm.customworkitemhandlers.ShowFrame;
import life.genny.qwanda.rule.RuleDetails;


rule "ATTRIBUTE_CHANGE_EVENT"
    ruleflow-group 'ChangeProcessing'
	salience 2
    no-loop
    when
			message : QEventMessage(event_type matches "EVT_ATTRIBUTE_VALUE_CHANGE" )	
			ruleDetails : RuleDetails()
    then
			System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing Change Event : " + message );
			 	     
  	       retract( message);
  	    
end
