package life.genny.rules;

import java.io.IOException;

global life.genny.qwanda.message.QBulkMessage payload;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.CapabilityUtils;
import life.genny.qwanda.Answer;
import java.util.List;
import java.util.ArrayList;
import life.genny.model.OutputParamTreeSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.utils.TableUtils;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import org.drools.core.spi.KnowledgeHelper;

rule "FILTER_INTERNS_HOST_CPY_REP"
	ruleflow-group 'SearchFilters'
	salience 10000
	no-loop true
	when
		userToken : GennyToken ( code != "PER_SERVICE" ) 
		searchBE: SearchEntity( code matches "SBE_INTERNS.*" || 
														code matches "SBE_AVAILABLE_INTERNS.*" ||
														code matches "SBE_INTERNS_AVAILABLE.*" ||
														code matches "SBE_COUNT_INTERN_.*" )
		allowed: Allowed(code == "VIEW_INTERNS" && mode == CapabilityMode.VIEW)
		beUtils : BaseEntityUtils( )

	
	then
		System.out.println(drools.getRule().getName() + " triggered");
		
		System.out.println("userCode     :: " + userToken.getUserCode());
		System.out.println("searchCode   :: " + searchBE.getCode());

		BaseEntity userBe = beUtils.getBaseEntityByCode(userToken.getUserCode());
		if(userBe == null){
			System.out.println("userBe is null");
			return;
		}

		String eduProviderCode = userBe.getValue("LNK_EDU_PROVIDER", null);		
		if(eduProviderCode == null){
			System.out.println("eduProviderCode is null");
			return;
		}

		searchBE.addFilter("LNK_EDU_PROVIDER", SearchEntity.StringFilter.LIKE, eduProviderCode);

		/* Create  QDataBaseEntityMessage for SearchEntity */
		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(searchBE);
		msg.setAliasCode("SBE");	
		payload.add(msg); 

		drools.getKnowledgeRuntime().setGlobal("payload", payload); 
		retract(allowed); 
end
