package life.genny.rules;

import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.TaskUtils;
import java.util.List;
import java.util.ArrayList;
import life.genny.utils.QuestionUtils;

rule "BUCKET_QUICK_SEARCH"
	ruleflow-group 'DataProcessing'
	salience 500
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		answer : Answer( attributeCode == "LNK_PERSON" && value != "[]" )
		output : OutputParam()
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName()+": Rule fired");

		/* Ensure frontend has updated dropdown value */
		VertxUtils.sendToFrontEnd(userToken, answer);

		TableUtils tableUtils = new TableUtils(beUtils);
		tableUtils.performQuickSearch(answer.getValue());
 		
		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");
		retract(answer);
end
