package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import java.util.List;
import java.util.ArrayList;

rule "DEFAULT_ANSWER"
    ruleflow-group 'DataProcessing'
    salience -10000 
    no-loop true
    when
 	  answer : Answer() /* (targetCode == beUtils.getGennyToken().getUserCode()) ) */
	  output : OutputParam( )
	  answersToSave : Answers()
     then
 		System.out.println("Rule -> DEFAULT_ANSWER : "+answer); 
	
	
		answer.setChangeEvent(false);
		answersToSave.add(answer);
				
		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
  	    
		retract(answer);
		update(output);
		update(answersToSave);

end
