package life.genny.rules;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import java.util.List;
import java.util.ArrayList;

rule "DEV_ANSWER"
	ruleflow-group 'DataProcessing'
	salience 10000 
	no-loop
	when
		beUtils : BaseEntityUtils()
		serviceToken : GennyToken( code == "PER_SERVICE") 
		userToken : GennyToken( code != "PER_SERVICE")
		answer : Answer( attributeCode matches "QUE_DEV_EDIT_.*" )

	then
 		System.out.println("Rule -> "+drools.getRule().getName()+" :  user=" + beUtils.getGennyToken().getUserCode()+" : "+answer); 

		List<Answer> answers = new ArrayList<>();
		answers.add(answer);	
		beUtils.saveAnswers(answers);
			
		retract(answer); 
end
