package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import java.util.List;
import java.util.ArrayList;

rule "PRI_FILTER_VALUE"
    ruleflow-group 'DataProcessing'
    salience -10000 
    no-loop true
    when
 	  answer : Answer( attributeCode matches "PRI_FILTER_VALUE_.*" && targetCode matches "SBE_.*" )
	  output : OutputParam( )
	  answersToSave : Answers()
     then
 		System.out.println("Rule -> PRI_FILTER_VALUE, discarding: "+answer); 

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
  	    
		retract(answer);
		update(output);

end
