package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;


import java.util.List;
import java.util.ArrayList;

rule "PRI_ADDRESS_JSON"
    ruleflow-group 'AnswerProcessing'
        salience 500 
    when
      beUtils : BaseEntityUtils()
	  serviceToken : GennyToken( code == "PER_SERVICE") 
	  answer : Answer( attributeCode == "PRI_ADDRESS_JSON" )
     then
 		System.out.println("Rule -> PRI_ADDRESS_JSON :  user=" + beUtils.getGennyToken().getUserCode()+" : "+answer); 
		String sourceCode = beUtils.getGennyToken().getUserCode();
		String targetCode = answer.getTargetCode();
		
		/* Parse json answer and save the individual answers */
					
			JsonObject addressDataJson = new JsonObject(answer.getValue());

			List<Answer> answers = new ArrayList<Answer>();
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_COUNTRY", addressDataJson.getString("country")));
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_POSTCODE", addressDataJson.getString("postal_code")));
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_SUBURB", addressDataJson.getString("suburb")));
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_CITY", addressDataJson.getString("suburb")));
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_STATE", addressDataJson.getString("state")));
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_ADDRESS1", addressDataJson.getString("street_address")));
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_FULL", addressDataJson.getString("full_address")));
		
			Double latitude = addressDataJson.getDouble("latitude");
			Double longitude = addressDataJson.getDouble("longitude");
			
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_LATITUDE", latitude));
			answers.add(new Answer(sourceCode, targetCode, "PRI_ADDRESS_LONGITUDE", longitude));
	
		beUtils.saveAnswers(answers,true); 

		retract(answer);
	
end
