package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import com.google.gson.reflect.TypeToken;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.VertxUtils;
import life.genny.utils.TableUtils;
import life.genny.models.TableData;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Ask;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.OutputParam;
import life.genny.jbpm.customworkitemhandlers.ShowFrame;
import life.genny.qwanda.message.QCmdMessage;



rule "PRI_SEARCH_TEXT"
	ruleflow-group 'DataProcessing'
	salience 450
	no-loop true
    when
    	$message : QEventMessage(data.code matches "ACT_SEARCH_DASHBOARD")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()

     then
  		System.out.println("Rule -> "+drools.getRule().getName()+" :  user=" + beUtils.getGennyToken().getUserCode());

		/* get current search */
		TableUtils tableUtils = new TableUtils(beUtils);
		
		String value = $message.getData().getValue();
		System.out.println("value :: " + value);
		
		SearchEntity searchBE = null;
		List<SearchEntity> searchBeList = new ArrayList<SearchEntity>();

		System.out.println("Rule -> "+drools.getRule().getName()+" LAST-SEARCH");
		searchBeList.add(VertxUtils.getObject(beUtils.getGennyToken().getRealm(), "LAST-SEARCH", beUtils.getGennyToken().getSessionCode(), SearchEntity.class));
		
		
		for (SearchEntity sbe : searchBeList) {
			System.out.println(drools.getRule().getName()+" ASSIST for "+sbe.getCode()); 

			/* Reset the pageNumber to 1 */
			Answer pageNumberAnswer = new Answer(beUtils.getGennyToken().getUserCode(), sbe.getCode(), "PRI_INDEX", "1");

			/* update the sbe object */
			sbe = beUtils.updateBaseEntity(sbe, pageNumberAnswer,SearchEntity.class);
			sbe.setWildcard(value);
			sbe.setPageStart(0);
			
			/* cache the updated sbe  */
			VertxUtils.putObject(beUtils.getGennyToken().getRealm(), "", sbe.getCode(), sbe, beUtils.getGennyToken().getToken());

			/* send the data */
			TableUtils.searchTable(beUtils,sbe, true);
		}
		
				
 		/* send the table display message out  */
			QCmdMessage msg = new QCmdMessage("DISPLAY", "PROCESS");
			msg.setToken(beUtils.getGennyToken().getToken());
			msg.setSend(true);  	
			VertxUtils.writeMsg("webcmds",msg);
			
			
			System.out.println("total took " + (totalTime) + " ms"); 
		retract($message);

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		update(output);
end
