package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.text.WordUtils;

import java.util.List;
import java.util.ArrayList;
import org.apache.commons.lang3.StringUtils;



rule "PRI_LASTNAME"
    ruleflow-group 'DataProcessing'
        salience 50 
    when
      beUtils : BaseEntityUtils()
	  answer : Answer( attributeCode == "PRI_LASTNAME" )
	  answersToSave : Answers()
	  output : OutputParam( )
     then
 		System.out.println("Rule -> PRI_LASTNAME :  user=" + beUtils.getGennyToken().getUserCode()+" : "+answer); 
		String sourceCode = beUtils.getGennyToken().getUserCode();
		String targetCode = answer.getTargetCode();
		
		/* Parse json answer and save the individual answers */
		String lastname = answer.getValue();
		lastname = lastname.toLowerCase().trim();
		lastname = StringUtils.capitalize(lastname);
		BaseEntity person = beUtils.getBaseEntityByCode(targetCode);
		String firstname = person.getValue("PRI_FIRSTNAME","");
		System.out.println("Rule -> PRI_LASTNAME 1 lastname="+lastname);	
		answersToSave.add(new Answer(sourceCode, targetCode, "PRI_LASTNAME", lastname,false,true));	
			
		String name = firstname + " "+lastname;
		name = name.trim();	
		name = WordUtils.capitalize(name);
		System.out.println("Rule -> PRI_LASTNAME 2 Name="+name);
	
			
		String initials = 	WordUtils.initials(name).toUpperCase();
		System.out.println("Rule -> PRI_LASTNAME 3 initials="+initials);
		
		Answer answerName = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_NAME",name);
 		beUtils.saveAnswer(answerName);
		Answer answerInitials = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_INITIALS",initials);
 		beUtils.saveAnswer(answerInitials);
		
			
		output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */
		
		

		retract(answer);
		update(answersToSave);
	
end
