package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import com.google.gson.reflect.TypeToken;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.VertxUtils;
import life.genny.utils.TableUtils;
import life.genny.models.TableData;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Ask;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.utils.OutputParam;
import life.genny.jbpm.customworkitemhandlers.ShowFrame;
import life.genny.qwanda.message.QCmdMessage;



rule "PRI_SEARCH_TEXT"
	ruleflow-group 'DataProcessing'
	salience 450
	no-loop true
    when
      beUtils : BaseEntityUtils()
	  serviceToken : GennyToken( code == "PER_SERVICE")
	  answer : Answer( attributeCode == "PRI_SEARCH_TEXT" && (!value.contains(":")) )   /* this is a pure search */
	  output : OutputParam( )

     then
  		System.out.println("Rule -> "+drools.getRule().getName()+" :  user=" + beUtils.getGennyToken().getUserCode()+" : "+answer);

			/* send the table display message out  */
			QCmdMessage msg = new QCmdMessage("DISPLAY", "TABLE");
			msg.setToken(beUtils.getGennyToken().getToken());
			msg.setSend(true);  	
			VertxUtils.writeMsg("webcmds",msg);

 	    /* get current search */
 	    TableUtils tableUtils = new TableUtils(beUtils);

		SearchEntity searchBE = tableUtils.getSessionSearch("SBE_SEARCHBAR");
		searchBE.setWildcard(answer.getValue());
 			VertxUtils.putObject(beUtils.getGennyToken().getRealm(), "", searchBE.getCode(), searchBE,
				beUtils.getGennyToken().getToken());
 
 	    /* Reset page to start */
  	    
  	    	long totalTime = TableUtils.searchTable(beUtils,searchBE, true);

			retract(answer);
			System.out.println("total took " + (totalTime) + " ms"); 
			output.setTypeOfResult("NONE");
			output.setResultCode("NONE");  /* dont display anything new */
  	    

end
