package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;

import life.genny.rules.RulesLoader;

rule "ASKTASK"
    ruleflow-group 'SignalProcessing'
    no-loop
    salience 1000
    when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		msg : QEventMessage (data.code == "TASK")
		ruleDetails : RuleDetails()
		output : OutputParam()
    then	
		System.out.println("$$$$$$$$ ASk TASK $$$$$$$$$$$");
		/* So we need to get the Task from the taskId and display it */
		output = RulesLoader.loadOutputFromTask(userToken,Long.parseLong(msg.getData().getValue())); 
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" " + userToken.getUserCode()+"  TaskId = "+msg.getData().getValue()+": generating "+output);

		retract(msg);

end