package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;

rule "DEFAULTPAGE"
    ruleflow-group 'SignalProcessing'
    no-loop
    salience 2
    when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		msg : QEventMessage (data.code == "DEFAULTPAGE")
    then
	
		System.out.println(drools.getRule().getName()+" Processing Internal Signal - DEFAULTPAGE " + userToken.getUserCode());
		output.setTypeOfResult("FORMCODE");
		output.setTargetCode("FRM_ROOT");
		output.setResultCode("FRM_APP");
		
		retract(serviceToken)
end