package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;

rule "DEFAULT_SIGNAL"
    ruleflow-group 'SignalProcessing'
    no-loop
    salience -10000
    when
		serviceToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
    then
	
		System.out.println("Processing Internal Signal ");
		output.setTypeOfResult("NONE");
		output.setResultCode("");
		
end