package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;

rule "SBE_APPLICATION_INTERN_DETAIL"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
	
       not  SearchEntity (code == "SBE_APPLICATION_INTERN_DETAIL")
        serviceToken : GennyToken( code == "PER_SERVICE")
        
     then
     	System.out.println("   Generate SBE_APPLICATION_INTERN_DETAIL ");
		
		SearchEntity searchBE = new SearchEntity("SBE_APPLICATION_INTERN_DETAIL", "Search")
				.addFilter("PRI_CODE", SearchEntity.StringFilter.EQUAL, "APP_APPLICATION_THREE")
				.addSort("PRI_CREATED", "Created", SearchEntity.Sort.DESC)
				.addColumn("PRI_INTERN_NAME", "Student Name")
				.addColumn("PRI_EDU_PROVIDER_NAME", "Edu Provider")
				.addColumn("PRI_INTERN_STUDENT_ID", "Student ID")
				.addColumn("PRI_INTERN_EMAIL", "Email")
				.addColumn("PRI_INTERN_MOBILE", "Mobile")
				.addColumn("PRI_INDUSTRY", "Industry")
				.addColumn("PRI_OCCUPATION", "Occupation")
				.setPageStart(0).setPageSize(10);
   	     
  	     searchBE.setRealm(serviceToken.getRealm());
  	     
 		 insert(searchBE);
  		 VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());
end
