package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;

rule "SEND_COUNT_ALL_INTERNS"
	ruleflow-group 'CountProcessing'
	salience 6
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )

	then
		System.out.println(drools.getRule().getName() + " triggered");
		Boolean cache = true;
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		TableUtils tableUtils = new TableUtils(beUtils);

		SearchEntity SBE_COUNT_INTERN_ALL = VertxUtils.getObject(serviceToken.getRealm(), "",
						"SBE_COUNT_INTERN_ALL", SearchEntity.class, serviceToken.getToken());
  
		tableUtils.performAndSendCount(serviceToken, SBE_COUNT_INTERN_ALL);
		System.out.println(drools.getRule().getName() + ": finishing rule"); 

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
end
