package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
rule "TREE_FORM_VIEW_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code == "QUE_TREE_FORM_VIEW")
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )		
    then
	
		System.out.println("Processing Answer/Data : " + $message );
		output.setResult("FRM_QUE_TREE_FORM_VIEW");
		retract( $message);
end