package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;
import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_INTERN_SUPERVISOR"
	ruleflow-group 'DataProcessing'
	salience 5000
	no-loop
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_INTERN_SUPERVISOR" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println(drools.getRule().getName() + " fired");

		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);

		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);

		String value = answer.getValue();
		System.out.println("value :: " + value);

		if(targetCode != null){
			if (targetCode.startsWith("APP_")) {
				BaseEntity appInternshipBe = beUtils.getBaseEntityFromLNKAttr(targetCode, "LNK_INTERNSHIP");
				System.out.println("appInternshipBe code :: " + appInternshipBe.getCode());
				if (appInternshipBe != null) {
					Answer ans = new Answer(sourceCode, appInternshipBe.getCode(), "LNK_INTERN_SUPERVISOR", value);
					beUtils.saveAnswer(ans);
					VertxUtils.sendToFrontEnd(userToken, ans);
				} else {
					System.out.println("appInternshipBe is null!");
				}
			} else {
				System.out.println("targetCode is not an application.");
			}
		} else {
			System.out.println("be is null!");
		}
end
