package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.utils.OutputParam;
import io.vertx.core.json.JsonObject;

import java.util.List;
import java.util.ArrayList;

rule "RED_REMINDER_PROGRESS"
    ruleflow-group 'SpecificReminder'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		bucketCode : String(bucketCode.equals("Progress"))
		colourCode : String(colourCode.equals("Red"))
	  
     then
    
		JsonObject jsonTemplates = new JsonObject();
		jsonTemplates.put("1", "RED_PROGRESS_REMINDER_EMAIL_TEMPLATE_APPLIED_STUDENT");
		jsonTemplates.put("2", "RED_PROGRESS_REMINDER_EMAIL_TEMPLATE_APPLIED_SCHOOL");
		jsonTemplates.put("3", "RED_PROGRESS_REMINDER_EMAIL_TEMPLATE_APPLIED_SALESTEAM");
		jsonTemplates.put("4", "RED_PROGRESS_REMINDER_SMS_TEMPLATE_APPLIED_STUDENT");
		System.out.println("Progress Red Reminder Notitificaitons Template Json: " + jsonTemplates.toString());
		
	/* output.setTypeOfResult("NotificationHubTemplateFound"); */
	/* output.setResultCode(jsonTemplates.toString()); */
	/* retract(output); */
		    
 	/* System.out.println("SUCCESS -> Set notification code to APPLIED" );  */
 		
 		retract(bucketCode)
 		retract(colourCode)
 		
 
end
