package life.genny.test;
//
//import java.io.File;
//import java.io.FileNotFoundException;
//import java.io.PrintWriter;
//import java.text.SimpleDateFormat;
//import java.util.Calendar;
//import java.util.Locale;
//
//import org.junit.Test;
//
//import com.github.javafaker.Faker;
//
//public class LinTestFaker {
//
//    /*
//     * This test case will create fake user sql file under genny/prj_genny
//     * 
//     * Sample of faker output https://java-faker.herokuapp.com/
//     * 
//     * Faker package repo https://github.com/DiUS/java-faker
//     * 
//     */
//    @Test
//    public void testCreateNewUser() {
//	Faker faker = new Faker(new Locale("en-AU"));
//
//	String insertBaseEntity = String.format(
//		"INSERT INTO `baseentity` (`dtype`, `id`, `created`, `name`, `realm`, `updated`, `code`) VALUES");
//
//	String insertBaseEntityAttribute = String.format("INSERT INTO `baseentity_attribute` ("
//		+ "`attributeCode`, `baseEntityCode`, `created`, `inferred`, `privacyFlag`, "
//		+ "`readonly`, `realm`, `updated`, `valueBoolean`, `valueDate`, "
//		+ "`valueDateRange`, `valueDateTime`, `valueDouble`, `valueInteger`, `valueLong`, "
//		+ "`money`, `valueString`, `valueTime`, `weight`, `ATTRIBUTE_ID`, " + "`BASEENTITY_ID`)\n" + "VALUES");
//
//	/*
//	 * IMPORTANT !!!
//	 * 
//	 * startKey is the baseEntity primary key numOfRows is how many rows of data
//	 * being generated by the function
//	 * 
//	 */
//
//	Integer startKey = 100000;
//	Integer numOfRows = 3;
//	String outputFileLocation = String.format("user-%s-%s.sql", startKey, startKey + numOfRows);
//
//	try (PrintWriter writer = new PrintWriter(new File(outputFileLocation))) {
//	    StringBuilder sb = new StringBuilder();
//	    writer.write(sb.toString()); //This will clear the SQL file.
//	    
//	    for (int i = startKey; i < startKey + numOfRows; i++) {
//
//		Integer priBaseEntity = i;
//
//		String fakeDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S000").format(Calendar.getInstance().getTime());
//		String fakeFirstname = faker.name().firstName().replaceAll("'", "");
//		String fakeLastname = faker.name().lastName().replaceAll("'", "");
//		String fakePreferredName = faker.name().firstName().replaceAll("'", "");
//		String fakeMobile = faker.numerify("614########"); //E.164 format phone number
//		String fakeDOB = new SimpleDateFormat("yyyy-MM-dd").format(faker.date().birthday(21, 50));
//
//		String fakeAddress1 = faker.address().streetAddressNumber() + " " + faker.address().streetName();
//		String fakeState = faker.address().stateAbbr();
//		String fakePostcode = faker.address().zipCode();
//		String fakeCity = faker.address().cityName();
//		String fakeCountry = "Australia";
//		String fakeAddressFull = String.format("%s, %s, %s %s, %s", fakeAddress1, fakeCity, fakeState,
//			fakePostcode, fakeCountry);
//
//		String fakeEmail = fakeFirstname + priBaseEntity + "@email.commmmm";
//		String fakeUUID = "PER_" + (fakeFirstname + priBaseEntity).toUpperCase() + "_AT_EMAILCOMM";
//
//		sb = new StringBuilder();
//
//		sb.append('\n');
//		sb.append(insertBaseEntity);
//		sb.append('\n');
//		sb.append(String.format("('BaseEntity', %s, '%s', '%s', 'internmatch', NULL, '%s');", priBaseEntity,
//			fakeDate, fakeUUID, fakeUUID));
//		sb.append('\n');
//
//		sb.append(insertBaseEntityAttribute);
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_PREFERRED_NAME', '%s', '%s', 0, 0, 0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL, 'null', '%s', NULL, 1, 856," + "%s),",
//			fakeUUID, fakeDate, fakePreferredName, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_LASTNAME', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 256," + "%s),",
//			fakeUUID, fakeDate, fakeLastname, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_FIRSTNAME', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 371," + "%s),",
//			fakeUUID, fakeDate, fakeFirstname, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_MOBILE', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 82," + "%s),",
//			fakeUUID, fakeDate, fakeMobile, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_EMAIL', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 594," + "%s),",
//			fakeUUID, fakeDate, fakeEmail, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_ADDRESS_ADDRESS1', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 555," + "%s),",
//			fakeUUID, fakeDate, fakeAddress1, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_ADDRESS_STATE', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 914," + "%s),",
//			fakeUUID, fakeDate, fakeState, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_ADDRESS_POSTCODE', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 727," + "%s),",
//			fakeUUID, fakeDate, fakePostcode, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_ADDRESS_CITY', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 248," + "%s),",
//			fakeUUID, fakeDate, fakeCity, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_ADDRESS_COUNTRY', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 765," + "%s),",
//			fakeUUID, fakeDate, fakeCountry, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_ADDRESS_FULL', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, NULL,"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', '%s', NULL, 1, 319," + "%s),",
//			fakeUUID, fakeDate, fakeAddressFull, priBaseEntity));
//		sb.append('\n');
//
//		sb.append(String.format(
//			"('PRI_DOB', '%s', '%s', 0, 0," + "0, 'internmatch', NULL, NULL, '%s',"
//				+ "NULL, NULL, NULL, NULL, NULL," + "'null', NULL, NULL, 1, 415," + "%s);",
//			fakeUUID, fakeDate, fakeDOB, priBaseEntity));
//		sb.append('\n');
//
//		writer.append(sb.toString());
//	    }
//	    
//	    System.out.println();
//	} catch (FileNotFoundException e) {
//	    System.out.println(e.getMessage());
//	}
//
//	/*
//	 * 
//	 * 
//	 * 
//	 * INSERT INTO `baseentity` (`dtype`, `id`, `created`, `name`, `realm`,
//	 * `updated`, `code`) VALUES ('BaseEntity', 100000, '2019-09-30
//	 * 04:20:44.549000', 'PER_DOMEMAIL_AT_EMAILCOMM', 'internmatch', NULL,
//	 * 'PER_DOMEMAIL_AT_EMAILCOMM');
//	 * 
//	 * 
//	 * INSERT INTO `baseentity_attribute` ( `attributeCode`, `baseEntityCode`,
//	 * `created`, `inferred`, `privacyFlag`, `readonly`, `realm`, `updated`,
//	 * `valueBoolean`, `valueDate`, `valueDateRange`, `valueDateTime`,
//	 * `valueDouble`, `valueInteger`, `valueLong`, `money`, `valueString`,
//	 * `valueTime`, `weight`, `ATTRIBUTE_ID`, `BASEENTITY_ID`) VALUES
//	 * 
//	 * ('PRI_PREFERRED_NAME', 'PER_DOM1EMAIL_AT_EMAILCOMM', '2019-09-30
//	 * 04:34:18.495000', 0, 0, 0, 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL,
//	 * NULL, NULL, 'null', 'DomPre', NULL, 1, 856, 2623),
//	 * 
//	 * ('PRI_LASTNAME', 'PER_DOM1EMAIL_AT_EMAILCOMM', '2019-09-30 04:34:07.820000',
//	 * 0, 0, 0, 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
//	 * 'null', 'Lin', NULL, 1, 256, 2623),
//	 * 
//	 * ('PRI_FIRSTNAME', 'PER_DOM1EMAIL_AT_EMAILCOMM', '2019-09-30 04:30:57.621000',
//	 * 0, 0, 0, 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
//	 * 'null', 'DominicDominic', NULL, 1, 371, 2623),
//	 * 
//	 * ('PRI_MOBILE', 'PER_DOM1EMAIL_AT_EMAILCOMM', '2019-09-30 04:21:50.080000', 0,
//	 * 0, 0, 'internmatch', '2019-09-30 04:40:14.340000', NULL, NULL, NULL, NULL,
//	 * NULL, NULL, NULL, 'null', '0412345678', NULL, 1, 82, 2623),
//	 * 
//	 * ('PRI_EMAIL', 'PER_DOM1EMAIL_AT_EMAILCOMM', '2019-09-30 04:21:42.354000', 0,
//	 * 0, 0, 'internmatch', '2019-09-30 04:30:07.265000', NULL, NULL, NULL, NULL,
//	 * NULL, NULL, NULL, 'null', 'email1236@email.comm', NULL, 1, 594, 2623),
//	 * 
//	 * ('PRI_DOB', 'PER_DOM1EMAIL_AT_EMAILCOMM', '2019-09-30 04:21:29.133000', 0, 0,
//	 * 0, 'internmatch', NULL, NULL, '2000-01-01', NULL, NULL, NULL, NULL, NULL,
//	 * 'null', NULL, NULL, 1, 415, 2623);
//	 * 
//	 * ('PRI_ADDRESS_ADDRESS1', 'CPY_COMPANY1', '2019-09-26 00:17:39.460000', 0, 0,
//	 * 0, 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null',
//	 * '121 Cardigan Street', NULL, 1, 555, 629),
//	 * 
//	 * ('PRI_ADDRESS_FULL', 'CPY_COMPANY1', '2019-09-26 00:18:59.379000', 0, 0, 0,
//	 * 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null', '121
//	 * Cardigan Street, Carlton VIC 3053, Australia', NULL, 1, 319, 629),
//	 * 
//	 * ('PRI_ADDRESS_STATE', 'CPY_COMPANY1', '2019-09-26 00:18:50.633000', 0, 0, 0,
//	 * 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null', 'VIC',
//	 * NULL, 1, 914, 629),
//	 * 
//	 * ('PRI_ADDRESS_POSTCODE', 'CPY_COMPANY1', '2019-09-26 00:17:51.080000', 0, 0,
//	 * 0, 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null',
//	 * '3053', NULL, 1, 727, 629),
//	 * 
//	 * ('PRI_CPY_NAME', 'CPY_COMPANY1', '2019-09-26 00:19:04.077000', 0, 0, 0,
//	 * 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null', 'GADA
//	 * Technology', NULL, 1, 495, 629),
//	 * 
//	 * ('PRI_ABN', 'CPY_COMPANY1', '2019-09-26 00:19:07.200000', 0, 0, 0,
//	 * 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null',
//	 * '51824753556', NULL, 1, 752, 629),
//	 * 
//	 * ('PRI_ADDRESS_CITY', 'CPY_COMPANY1', '2019-09-26 00:18:03.463000', 0, 0, 0,
//	 * 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null',
//	 * 'Carlton', NULL, 1, 248, 629),
//	 * 
//	 * ('PRI_ADDRESS_COUNTRY', 'CPY_COMPANY1', '2019-09-26 00:18:41.117000', 0, 0,
//	 * 0, 'internmatch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null',
//	 * 'AU', NULL, 1, 765, 629);
//	 * 
//	 */
//    }
//
//};