package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "APPLIED_TO_APPLIED"
    ruleflow-group 'MoveBucket'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity()
		output : OutputParam()
		bucketCode : String(bucketCode.equals("Applied"))
		controlSignalCode : String(controlSignalCode.equals("First"))

	  
     then
 		System.out.println("APPLIED_TO_APPLIED: Rule fired" ); 
 		System.out.println("APPLIED_TO_APPLIED: newApplication = " + newApplication.getCode());
 		
 		System.out.println("APPLIED_TO_APPLIED: bucketCode = " + bucketCode);
		
		output.setTargetCode(bucketCode);
		
	
		retract(userToken)
		retract(serviceToken)
		retract(newApplication)
		retract(bucketCode)
		retract(controlSignalCode)
		
end
