package life.genny.rules;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "SHORTLIST_TO_INTERVIEW"
    ruleflow-group 'MoveBucket'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity()
		output : OutputParam()
		bucketCode : String(bucketCode.equals("Shortlist"))
		controlSignalCode : String(controlSignalCode.equals("FORWARD"))

	  
     then
 		System.out.println("SHORTLIST_TO_INTERVIEW: Rule fired" ); 
 		System.out.println("SHORTLIST_TO_INTERVIEW: newApplication = " + newApplication.getCode());
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		Answer answer = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_STATUS","Interview");
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);
 		beUtils.saveAnswer(answer);

	/* insert(answer); */
		
		System.out.println("SHORTLIST_TO_INTERVIEW: Answer = " + answer);
		System.out.println("SHORTLIST_TO_INTERVIEW: newApplication = " + newApplication); 
		
		
	/*  Set the attribute code and value to output */
		output.setResultCode(answer.getAttributeCode());
		output.setTargetCode(answer.getValue());
	
		retract(newApplication)
		retract(bucketCode)
		retract(controlSignalCode)
		
end
