package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.utils.OutputParam;


import java.util.List;
import java.util.ArrayList;

rule "ROUTE_TASK"
    ruleflow-group 'TaskRouting'
    salience 1 
    when
      userToken : GennyToken ( code != "PER_SERVICE" )
	  serviceToken : GennyToken( code == "PER_SERVICE") 
	  output : OutputParam (  )
	  
	  
     then
 		System.out.println("ROUTE_TASK -> Rule fired"); 
 		
 		System.out.println("userToken: " + userToken); 
 		System.out.println("serviceToken: " + serviceToken);
 		
 		output.setResultCode("Dude");

end
