package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.qwanda.llama.Frame;

rule "DASHBOARD_1"
    ruleflow-group 'GenerateFrames'
    no-loop true
    when
      $process : WorkflowProcessInstance( ) 
     then
     log.info("Generate Llama 1 Rule");
 
	GennyToken serviceToken = (GennyToken)$process.getVariable("serviceToken"); 
	log.info("Genny Token Service Code2 = "+serviceToken.getCode());
	
/*	Llama desktop = Llama.Builder.newInstance("FRM_DASHBOARD") 
                              .addTheme("THM_BACKGROUND_GRAY","backgroundColor","gray") 
                              .addTheme("THM_BACKGROUND_INTERNMATCH","backgroundColor","#233a4e") 
                              .addTheme("THM_COLOR_WHITE","backgroundColor","white") 
                              .addTheme("THM_COLOR_BLACK","backgroundColor","black") 
                              .addFrame(Frame.Builder.newInstance("FRM_MAIN").addTheme("THM_COLOR_WHITE")
                              	.addFrame(Frame.Builder.newInstance("NORTH","FRM_HEADER")
                              		.addFrame(Frame.Builder.newInstance("EAST","FRM_PROFILE")
                              			.addTheme("THM_DISPLAY_HORIZONTAL","flexDirection","row")
                              		)
                              	)
                              	.addFrame(Frame.Builder.newInstance("SOUTH","FRM_FOOTER"))
                              	.addFrame(Frame.Builder.newInstance("WEST","FRM_SIDEBAR")
                              		.addTheme("THM_WIDTH_300","width",300)
                              		.addTheme("THM_DISPLAY_VERTICAL","flexDirection": "column")
                              		.addTheme("THM_DISPLAY_VERTICAL","justifyContent","flex-start")
                              		)
                              	.addFrame(Frame.Builder.newInstance("CENTRE","FRM_CONTENT"))
                              	)
                                    
                              .build(); 
	*/
/*	$process.setVariable( "dynamicGroupId","analyst" ); 
	retract($process); */

end
