package life.genny.rules;





global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;

rule "FRM_TABLE_APP"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_TABLE_APP")
      serviceToken : GennyToken( code == "PER_SERVICE")
      FRM_HEADER : Frame3 ( code == "FRM_HEADER" )
      FRM_SIDEBAR : Frame3 ( code == "FRM_SIDEBAR" )
      FRM_TABLE : Frame3 ( code == "FRM_TABLE" )
      FRM_FOOTER : Frame3 ( code == "FRM_FOOTER" )
      
    then
        System.out.println("   Generate FRM_TABLE_APP Rule  "+serviceToken.getUserCode());

        Theme THM_TABLE = VertxUtils.getObject(serviceToken.getRealm(), "", "THM_TABLE",
        				Theme.class, serviceToken.getToken());

 
 
        Frame3 frame = Frame3.builder("FRM_TABLE_APP")
                                .addTheme("THM_PROJECT", ThemePosition.FRAME, serviceToken).end()
                                .addFrame(FRM_HEADER, FramePosition.NORTH).end()
                                .addFrame(FRM_SIDEBAR, FramePosition.WEST).end()

                                /* .addFrame(FRM_CONTENT, FramePosition.CENTRE).end() */
                                .addFrame(FRM_TABLE, FramePosition.CENTRE).end()
                                .addFrame(FRM_FOOTER, FramePosition.SOUTH).end() 
                                /*.addFrame(FRM_TABS, FramePosition.CENTRE).end() */
                                .build();
    
        frame.setRealm(serviceToken.getRealm());
        insert (frame);
        FrameUtils2.toMessage(frame, serviceToken);
			
end
