package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.QwandaUtils;

rule "ACCESS_NOTES_APPLICATION"
	ruleflow-group 'NoteEvent'
	salience 2
	no-loop
	when
		targetBe : BaseEntity()
		type : String(type.equals("APPLICATION"))
		
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		ruleDetails : RuleDetails()
	then

		System.out.println(drools.getRule().getName() + " triggered");
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		
		targetBe = beUtils.getBaseEntityByCode(targetBe.getCode());

		if(targetBe != null){
			/* Application Details */
			String appCode = targetBe.getCode();
			System.out.println("appCode: " +appCode);

			String appName = targetBe.getValue("PRI_TITLE", null);
			System.out.println("appName: " +appName);
			
			String appImage = targetBe.getValue("PRI_IMAGE_URL", null);
			System.out.println("appImage: " +appImage);
			
			
			/* Intern Details */
			String internCode = targetBe.getValue("PRI_INTERN_CODE", null);
			System.out.println("internCode: " +internCode);
			
			BaseEntity internBe = beUtils.getBaseEntityByCode(internCode);
			
			String internName = internBe.getValue("PRI_NAME", null);
			System.out.println("internName: " +internName);
			
			String internImage = internBe.getValue("PRI_IMAGE_URL", null);
			System.out.println("internImage: " +internImage);
	
	
			/* Internship Details */
			String internshipCode = targetBe.getValue("LNK_INTERNSHIP", null);
			internshipCode = internshipCode.replace("\"", "").replace("[", "").replace("]", "");
			System.out.println("internshipCode: " +internshipCode);
			
			BaseEntity internshipBe = beUtils.getBaseEntityByCode(internshipCode);
			
			String internshipName = internshipBe.getValue("PRI_NAME", null);
			System.out.println("internshipName: " +internshipName);
			
			String internshipImage = internshipBe.getValue("PRI_IMAGE_URL", null);
			System.out.println("internshipImage: " +internshipImage);
			
			
			/* Host Company Details */
			String hcCode = targetBe.getValue("LNK_HOST_COMPANY", null);
			hcCode = hcCode.replace("\"", "").replace("[", "").replace("]", "");
			System.out.println("hcCode: " +hcCode);
			
			BaseEntity hcBe = beUtils.getBaseEntityByCode(hcCode);
			
			String hcName = hcBe.getValue("PRI_NAME", null);
			System.out.println("hcName: " +hcName);
			
			String hcImage = hcBe.getValue("PRI_IMAGE_URL", null);
			System.out.println("hcImage: " +hcImage);
			
			
			/* Supervisor Details */
			String superCode = targetBe.getValue("LNK_INTERN_SUPERVISOR", null);
			superCode = superCode.replace("\"", "").replace("[", "").replace("]", "");
			System.out.println("superCode: " +superCode);
			
			BaseEntity superBe = beUtils.getBaseEntityByCode(superCode);
			
			String superName = superBe.getValue("PRI_NAME", null);
			System.out.println("superName: " +superName);
			
			String superImage = superBe.getValue("PRI_IMAGE_URL", null);
			System.out.println("superImage: " +superImage);
			
			
			/* Get all notes for Application Set */
			String endPoint = GennySettings.projectUrl + "/v7/notes";
			System.out.println("endPoint :: " + endPoint);

			String urlApp = endPoint + "/"+appCode + "?tags=&pageIndex=0&pageSize=100";
			String urlIntern = endPoint + "/"+internCode + "?tags=&pageIndex=0&pageSize=100";
			String urlInternship = endPoint + "/"+internshipCode + "?tags=&pageIndex=0&pageSize=100";
			String urlHC = endPoint + "/"+hcCode + "?tags=&pageIndex=0&pageSize=100";
			String urlSuper = endPoint + "/"+superCode + "?tags=&pageIndex=0&pageSize=100";

			System.out.println("urlApp :: " + urlApp);
			System.out.println("urlIntern :: " + urlIntern);
			System.out.println("urlInternship :: " + urlInternship);
			System.out.println("urlHC :: " + urlHC);
			System.out.println("urlSuper :: " + urlSuper);

			String appNotes = QwandaUtils.sendGET(urlApp, serviceToken.getToken());
			String internNotes = QwandaUtils.sendGET(urlIntern, serviceToken.getToken());
			String internshipNotes = QwandaUtils.sendGET(urlInternship, serviceToken.getToken());
			String hcNotes = QwandaUtils.sendGET(urlHC, serviceToken.getToken());
			String superNotes = QwandaUtils.sendGET(urlSuper, serviceToken.getToken());

			System.out.println("appNotes :: " + appNotes);
			System.out.println("internNotes :: " + internNotes);
			System.out.println("internshipNotes :: " + internshipNotes);
			System.out.println("hcNotes :: " + hcNotes);
			System.out.println("superNotes :: " + superNotes);
			
			String codes = "[\"" + appCode + "\",\"" + internCode + "\",\"" + internshipCode + "\",\"" + hcCode + "\",\"" + superCode + "\"]";
			System.out.println("codes :: " + codes);
			/*setCode(“[PER_,APP_,BEG_…]“)*/

			QCmdMessage notesMsg = new QCmdMessage("NOTES", "TABS");
			notesMsg.setCode("\"[" +appCode + ",");
			notesMsg.setToken(beUtils.getGennyToken().getToken());
			notesMsg.setSend(true);
			VertxUtils.writeMsg("webcmds", notesMsg);

			
			/* Send notes to FE */
			JsonObject jsonApplication = new JsonObject(appNotes);
			JsonObject jsonIntern = new JsonObject(internNotes);
			JsonObject jsonInternship = new JsonObject(internshipNotes);
			JsonObject jsonHC = new JsonObject(hcNotes);
			JsonObject jsonSuper = new JsonObject(superNotes);

			if(appNotes != null){
				jsonApplication.put("token", userToken.getToken());
				jsonApplication.put("code", appCode);
				jsonApplication.put("title", appName);
				jsonApplication.put("image", appImage);
			} else {
				System.out.println("ERROR: Application Notes failed to send");
		
				QCmdMessage msg = new QCmdMessage("TOAST", "ERROR");
				msg.setMessage("ERROR: Application Notes failed to send");
				msg.setToken(beUtils.getGennyToken().getToken());
				msg.setSend(true);
				VertxUtils.writeMsg("webcmds", msg);
			}	

			if(internNotes != null){
				jsonIntern.put("token", userToken.getToken());
				jsonIntern.put("code", internCode);
				jsonIntern.put("title", internName);
				jsonIntern.put("image", internImage);
			} else {
				System.out.println("ERROR: Intern Notes failed to send");
		
				QCmdMessage msg = new QCmdMessage("TOAST", "ERROR");
				msg.setMessage("ERROR: Intern Notes failed to send");
				msg.setToken(beUtils.getGennyToken().getToken());
				msg.setSend(true);
				VertxUtils.writeMsg("webcmds", msg);
			}	

			if(internshipNotes != null){
				jsonInternship.put("token", userToken.getToken());
				jsonInternship.put("code", internshipCode);
				jsonInternship.put("title", internshipName);
				jsonInternship.put("image", internshipImage);
			} else {
				System.out.println("ERROR: Internship Notes failed to send");
		
				QCmdMessage msg = new QCmdMessage("TOAST", "ERROR");
				msg.setMessage("ERROR: Internship Notes failed to send");
				msg.setToken(beUtils.getGennyToken().getToken());
				msg.setSend(true);
				VertxUtils.writeMsg("webcmds", msg);
			}	

			if(hcNotes != null){
				jsonHC.put("token", userToken.getToken());
				jsonHC.put("code", hcCode);
				jsonHC.put("title", hcName);
				jsonHC.put("image", hcImage);
			} else {
				System.out.println("ERROR: HC Notes failed to send");
		
				QCmdMessage msg = new QCmdMessage("TOAST", "ERROR");
				msg.setMessage("ERROR: HC Notes failed to send");
				msg.setToken(beUtils.getGennyToken().getToken());
				msg.setSend(true);
				VertxUtils.writeMsg("webcmds", msg);
			}	

			if(superNotes != null){
				jsonSuper.put("token", userToken.getToken());
				jsonSuper.put("code", superCode);
				jsonSuper.put("title", superName);
				jsonSuper.put("image", superImage);
			} else {
				System.out.println("ERROR: Supervisor Notes failed to send");
		
				QCmdMessage msg = new QCmdMessage("TOAST", "ERROR");
				msg.setMessage("ERROR: Supervisor Notes failed to send");
				msg.setToken(beUtils.getGennyToken().getToken());
				msg.setSend(true);
				VertxUtils.writeMsg("webcmds", msg);
			}	

			
			VertxUtils.writeMsg("webcmds", jsonApplication.toString());
			VertxUtils.writeMsg("webcmds", jsonIntern.toString());
			VertxUtils.writeMsg("webcmds", jsonInternship.toString());
			VertxUtils.writeMsg("webcmds", jsonHC.toString());
			VertxUtils.writeMsg("webcmds", jsonSuper.toString());
			System.out.println("Successfully navigated ApplicationAccess Notes");
			
		} else {
			System.out.println("ERROR: Failed to retrieve Application Base Entity");
			
			QCmdMessage msg = new QCmdMessage("TOAST", "ERROR");
			msg.setMessage("ERROR: Failed to retrieve Application Base Entity");
			msg.setToken(beUtils.getGennyToken().getToken());
			msg.setSend(true);
			VertxUtils.writeMsg("webcmds", msg);
		}

		retract(targetBe);
		retract(type);
	end


