package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.QwandaUtils;

rule "NOTE_EVENT_INTERN"
	ruleflow-group 'EventProcessing'
	salience 2
	no-loop
	when
		$message : QEventMessage(data.code matches "ACT_PRI_EVENT_ACCESS_NOTES_INTERN")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
	then
		System.out.println(drools.getRule().getName() + " triggered");
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String targetCode = $message.getData().getTargetCode();
		System.out.println("targetCode :: " + targetCode);

		if(targetCode != null){
			try {
				String endPoint = GennySettings.projectUrl + "/v7/notes";
				System.out.println("endPoint :: " + endPoint);

				String url = endPoint + "/"+targetCode + "?tags=&pageIndex=0&pageSize=100";
				System.out.println("url :: " + url);

				String notes = QwandaUtils.sendGET(url, serviceToken.getToken());
				System.out.println("notes :: " + notes);
				
				
				/* Internship Details */
				BaseEntity internshipBE = beUtils.getBaseEntityByCode(targetCode);
				
				String internshipName = internshipBE.getValue("PRI_NAME", null);
				System.out.println("internshipName: " +internshipName);
				
				String internshipImage = internshipBE.getValue("PRI_IMAGE_URL", null);
				System.out.println("internshipImage: " +internshipImage);


				/* Search for Applications */
				String linkedAPPs = internshipBE.getValue("LNK_APPLICATIONS", null);
				
				if (linkedAPPs != null){
					System.out.println("linkedAPPs: " +linkedAPPs);									/*["APP_AA3FEB35-FD12-49B9-A595-AA315773A37F","APP_41484401-7C82-4CD0-9B75-AA9E224B23ED"]*/
					linkedAPPs = linkedAPPs.replace("\"", "").replace("[", "").replace("]", "");	
					System.out.println("linkedAPPs: " +linkedAPPs);									/*APP_AA3FEB35-FD12-49B9-A595-AA315773A37F,APP_41484401-7C82-4CD0-9B75-AA9E224B23ED*/
					
					String[] splitAPPs = linkedAPPs.split(",");
					int length = splitAPPs.length;
					System.out.println("length: " +length);	
					
					BaseEntity[] beCodez = new BaseEntity[length];
					BaseEntity appBe = null;
					
					
					for (int i = 0; i < length; i++) {
						appBe = beUtils.getBaseEntityByCode(splitAPPs[i]);
						beCodez[i] = appBe;
						System.out.println("beCodez: " +beCodez[i]);
					}
					
					QDataBaseEntityMessage msgMatches = new QDataBaseEntityMessage(beCodez);
					msgMatches.setToken(userToken.getToken());
					msgMatches.setReplace(true);
					VertxUtils.writeMsg("webcmds", JsonUtils.toJson(msgMatches));
				}
				/*String[] tagList = {"Business Development", "Placement", "Outcome Life", "Miscellaneous"};*/
				
				
				if(notes != null){
					JsonObject json = new JsonObject(notes);
					json.put("token", userToken.getToken());
					
					JsonObject jsonIntern = new JsonObject();
					jsonIntern.put("code", targetCode);
					jsonIntern.put("title", internshipName);
					jsonIntern.put("image", internshipImage);
					jsonIntern.put("linkedAPPs", linkedAPPs);
					/*jsonIntern.put("tagList", tagList);*/
					
					json.put("Tab_Intern", jsonIntern);
					
					System.out.println("json :: " + json.toString());
					VertxUtils.writeMsg("webcmds", json.toString());
				}
				
				
				
			} catch (Exception e) {
				System.out.println("Exception :: " + e);
			}
		}

		retract( $message);
	end


