package life.genny.rules;

global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import java.util.Map;
import life.genny.models.FrameTuple3;
import life.genny.utils.TableUtils;
import life.genny.qwanda.Context;
import life.genny.qwanda.ContextList;
import life.genny.qwanda.ContextType;

rule "FRM_BUCKET_VIEW"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_BUCKET_VIEW")
      FRM_BUCKET_WRAPPER : Frame3 ( code == "FRM_BUCKET_WRAPPER" )
      FRM_BUCKETS : Frame3 ( code == "FRM_BUCKETS" )
      FRM_BUCKET_HEADER : Frame3 ( code == "FRM_BUCKET_HEADER" )
      FRM_BUCKET_CONTENT : Frame3 ( code == "FRM_BUCKET_CONTENT" )
      FRM_BUCKET_FOOTER : Frame3 ( code == "FRM_BUCKET_FOOTER" )
      serviceToken : GennyToken( code == "PER_SERVICE")

      
    then
			System.out.println(" Generating FRM_BUCKET_VIEW Ruless  "+serviceToken.getUserCode());

			/* initialize  beUtils */
			BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);
			
			/* initialize  tableUtils */
			TableUtils tableUtils = new TableUtils(beUtils);
			
			/* initialize  virtualAskMap */
      Map<String, QDataAskMessage> virtualAskMap = new HashMap<String, QDataAskMessage>();
      
      /*  initialize ask set */
      Set<QDataAskMessage> askSet = new HashSet<QDataAskMessage>();
      
      /* initialize  contextListMap */
      Map<String, ContextList> contextListMap = new HashMap<String, ContextList>();

			/* get the searchBeList from cache */
			List<SearchEntity> searchBeList = new ArrayList<SearchEntity>();
			SearchEntity SBE_APPLIED_APPLICATIONS = VertxUtils.getObject(serviceToken.getRealm(), "",
							"SBE_APPLIED_APPLICATIONS", SearchEntity.class, serviceToken.getToken());
			SearchEntity SBE_SHORTLISTED_APPLICATIONS = VertxUtils.getObject(serviceToken.getRealm(), "",
							"SBE_SHORTLISTED_APPLICATIONS", SearchEntity.class, serviceToken.getToken());
			SearchEntity SBE_INTERVIEWED_APPLICATIONS = VertxUtils.getObject(serviceToken.getRealm(), "",
							"SBE_INTERVIEWED_APPLICATIONS", SearchEntity.class, serviceToken.getToken());
			SearchEntity SBE_OFFERED_APPLICATIONS = VertxUtils.getObject(serviceToken.getRealm(), "",
							"SBE_OFFERED_APPLICATIONS", SearchEntity.class, serviceToken.getToken());
			SearchEntity SBE_PLACED_APPLICATIONS = VertxUtils.getObject(serviceToken.getRealm(), "",
							"SBE_PLACED_APPLICATIONS", SearchEntity.class, serviceToken.getToken());
			SearchEntity SBE_INPROGRESS_APPLICATIONS = VertxUtils.getObject(serviceToken.getRealm(), "",
							"SBE_INPROGRESS_APPLICATIONS", SearchEntity.class, serviceToken.getToken());

			searchBeList.add(SBE_APPLIED_APPLICATIONS);
			searchBeList.add(SBE_SHORTLISTED_APPLICATIONS);
			searchBeList.add(SBE_INTERVIEWED_APPLICATIONS);
			searchBeList.add(SBE_OFFERED_APPLICATIONS);
			searchBeList.add(SBE_PLACED_APPLICATIONS);
			searchBeList.add(SBE_INPROGRESS_APPLICATIONS);

			/* print the searchBE List size */
			System.out.println("size   ::    " + searchBeList.size());

			/* prepare themes */
			Theme THM_DISPLAY_VERTICAL = Theme.builder("THM_DISPLAY_VERTICAL")
			 						.addAttribute().flexDirection("column").end()
									.build();

			Theme THM_BH_GROUP_WRAPPER = Theme.builder("THM_BH_GROUP_WRAPPER")
                    .addAttribute()
                      .width("100%")
                      .padding(10)
                    .end()
                    .build();

			Theme THM_QUESTION_GRP_LABEL = Theme.builder("THM_QUESTION_GRP_LABEL")
                  .addAttribute(ThemeAttributeType.PRI_HAS_QUESTION_GRP_LABEL, true).end()
                  .build();   
			
			/* get sort icon */
			BaseEntity ICN_SORT = beUtils.getBaseEntityByCode("ICN_SORT");
                
			/* bucket-header label context  */
			Context bucketHeaderLabelContext = new Context(ContextType.THEME, tableUtils.getThemeBe(THM_QUESTION_GRP_LABEL), VisualControlType.GROUP, 1.0);
			bucketHeaderLabelContext.setDataType("Form Submit");
      
			/* bucket-header  context  */
      List<Context> bucketHeaderContext = new ArrayList<>();
      bucketHeaderContext.add(new Context(ContextType.THEME, tableUtils.getThemeBe(THM_DISPLAY_VERTICAL), VisualControlType.GROUP_CONTENT_WRAPPER, 1.0));
      bucketHeaderContext.add(new Context(ContextType.THEME, tableUtils.getThemeBe(THM_BH_GROUP_WRAPPER), VisualControlType.GROUP_WRAPPER, 1.0));
      bucketHeaderContext.add(bucketHeaderLabelContext);


			/* get all the bucket related asks group */
			Ask FRM_BUCKET_HEADER_ASK = tableUtils.getBucketHeaderAsk(contextListMap, serviceToken);
      Ask FRM_BUCKET_CONTENT_ASK = tableUtils.getBucketContentAsk(contextListMap, serviceToken);
      Ask FRM_BUCKET_FOOTER_ASK = tableUtils.getBucketFooterAsk(contextListMap, serviceToken);
			
			/* loop through the searchList */
			for (SearchEntity searchBe : searchBeList) {
    	   
				String code = searchBe.getCode().split("SBE_")[1];
				System.out.println("Current Code   ::    " + code);

				contextListMap.put("QUE_BUCKET_HEADER_" + code + "_GRP", new ContextList(bucketHeaderContext));

				Frame3 bucketHeader = Frame3.clone(FRM_BUCKET_HEADER);
				bucketHeader.setCode("FRM_BUCKET_HEADER_" + code);
				bucketHeader.setQuestionCode("QUE_BUCKET_HEADER_" + code + "_GRP");

				Frame3 bucketContent = Frame3.clone(FRM_BUCKET_CONTENT);
				bucketContent.setCode("FRM_BUCKET_CONTENT_" + code);
				bucketContent.setQuestionCode("QUE_BUCKET_CONTENT_" + code + "_GRP");

				Frame3 bucketFooter = Frame3.clone(FRM_BUCKET_FOOTER);
				bucketFooter.setCode("FRM_BUCKET_FOOTER_" + code);
				bucketFooter.setQuestionCode("QUE_BUCKET_FOOTER_" + code + "_GRP");

				Frame3 bucket = Frame3.clone(FRM_BUCKETS);
				bucket.setCode("FRM_BUCKET_"+code);
				bucket.getFrames().add(new FrameTuple3(bucketHeader, FramePosition.NORTH, 1.0));
				bucket.getFrames().add(new FrameTuple3(bucketContent, FramePosition.CENTRE, 1.0));
				bucket.getFrames().add(new FrameTuple3(bucketFooter, FramePosition.SOUTH, 1.0));

				/* add the cloned bucket to wrapper */
				FRM_BUCKET_WRAPPER.getFrames().add(new FrameTuple3(bucket, FramePosition.WEST, 1.0));

				/* bucketHeader asks */
				Ask bucketHeaderAsk = Ask.clone(FRM_BUCKET_HEADER_ASK);
				bucketHeaderAsk.setQuestionCode("QUE_BUCKET_HEADER_" + code + "_GRP");
				bucketHeaderAsk.setName(searchBe.getName());

        /* bucketContent asks */
        Ask bucketContentAsk = Ask.clone(FRM_BUCKET_CONTENT_ASK);
        bucketContentAsk.setQuestionCode("QUE_BUCKET_CONTENT_" + code + "_GRP");
        bucketContentAsk.setName(searchBe.getName());

				/* bucketFooter asks */
				Ask bucketFooterAsk = Ask.clone(FRM_BUCKET_FOOTER_ASK);
				bucketFooterAsk.setQuestionCode("QUE_BUCKET_FOOTER_" + code + "_GRP");
				bucketFooterAsk.setName(searchBe.getName());

				System.out.println("bucketHeaderAsk Code   ::    " + bucketHeaderAsk.getQuestionCode());
				System.out.println("bucketContentAsk Code   ::    " + bucketContentAsk.getQuestionCode());
				System.out.println("bucketFooterAsk Code   ::    " + bucketFooterAsk.getQuestionCode());

				/* add the ask to virtualAskMap */
				virtualAskMap.put(bucketHeaderAsk.getQuestionCode(), new QDataAskMessage(bucketHeaderAsk));
				virtualAskMap.put(bucketContentAsk.getQuestionCode(), new QDataAskMessage(bucketContentAsk));
        virtualAskMap.put(bucketFooterAsk.getQuestionCode(), new QDataAskMessage(bucketFooterAsk));
			}

			Frame3 FRM_BUCKET_VIEW_CONTENT = Frame3.builder("FRM_BUCKET_VIEW_CONTENT")
                    .addFrame(FRM_BUCKET_WRAPPER, FramePosition.CENTRE).end()
										.build();

			Frame3 frame = Frame3.builder("FRM_BUCKET_VIEW")
                    .addFrame(FRM_BUCKET_VIEW_CONTENT, FramePosition.CENTRE).end()
										.build();
							
			frame.setRealm(serviceToken.getRealm());
								
			insert (frame);
	
			/* generating frame msg and saving to cache */
			QDataBaseEntityMessage frameMsg = FrameUtils2.toMessage(frame, serviceToken, askSet, contextListMap, virtualAskMap);

			/* cache the frame */
			VertxUtils.putObject(serviceToken.getRealm(), "", frame.getCode(), frame, serviceToken.getToken());

			/* cache the QDataBaseEntityMessage */
			VertxUtils.putObject(serviceToken.getRealm(), "", frame.getCode() + "_MSG", frameMsg, serviceToken.getToken());
			
			/* cache the ask */
			VertxUtils.writeCachedJson(serviceToken.getRealm(),"ASK_" + frame.getCode(), JsonUtils.toJson(askSet.toArray()),serviceToken.getToken());

end
