package life.genny.rules;

global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;

rule "FRM_BUCKETS"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_BUCKETS")
      serviceToken : GennyToken( code == "PER_SERVICE")
      
    then
     System.out.println(" Generate FRM_BUCKETS Rule  "+serviceToken.getUserCode());

			Frame3 frame = Frame3.builder("FRM_BUCKETS")
										.addTheme("THM_BACKGROUND_NONE", serviceToken).end()
										.addTheme("THM_BACKGROUND_E4E4E4", ThemePosition.WRAPPER, serviceToken).end()
										.addTheme("THM_BUCKET_COLUMN", ThemePosition.WRAPPER, serviceToken).end()
										.addTheme("THM_BUCKET_COLUMN_PADDING", ThemePosition.CENTRE, serviceToken).end()
										.addTheme("THM_SCROLL_VERTICAL", ThemePosition.CENTRE, serviceToken).end()
										.build();
							
			frame.setRealm(serviceToken.getRealm());
								
			insert (frame);
			
			/* Process and save to cache */
			FrameUtils2.toMessage(frame, serviceToken);

	end
