package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;


rule "SEND_SIDEBAR"
	ruleflow-group 'SendAsks'
	salience 8
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )

	then
		System.out.println(drools.getRule().getName() + " triggered");

		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		CapabilityUtils capabilityUtils = new CapabilityUtils(beUtils);
  
		System.out.println("userCode   ::   " + userToken.getUserCode());

		/* get the addItems ask from cache */
		Ask sidebarAsk = VertxUtils.getObject(serviceToken.getRealm(), "", "SIDEBAR", Ask.class, serviceToken.getToken());
		List<Ask> sendCodes = new ArrayList<>();

		if (sidebarAsk == null) {
			System.out.println("sidebarAsk is not in cache");

		} else {

			for (Ask childAsk : sidebarAsk.getChildAsks()) {
				String code = childAsk.getQuestionCode().replace("QUE_", "");

				if (capabilityUtils.hasCapabilityThroughPriIs(code, CapabilityMode.ADD)) {
					/* System.out.println("Has Permission for " + code); */
					sendCodes.add(childAsk);
				}
			}

			Ask[] items = sendCodes.toArray(new Ask[sendCodes.size()]);
			sidebarAsk.setChildAsks(items);
			
			String json = JsonUtils.toJson(sidebarAsk);
			json = json.replaceAll("PER_SERVICE", userToken.getUserCode());

			sidebarAsk = JsonUtils.fromJson(json, Ask.class);
			/* send the addItems asks */
			QDataAskMessage askMsg = new QDataAskMessage(sidebarAsk);
			askMsg.setToken(userToken.getToken());
			VertxUtils.writeMsg("webcmds", askMsg);
		}

end
