package life.genny.rules;

import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.utils.OutputParam;

rule "SEND_SIDEBAR"
	ruleflow-group 'SendAsks'
	salience 8
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )

	then
		System.out.println(drools.getRule().getName() + " triggered");

		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		CapabilityUtils capabilityUtils = new CapabilityUtils(beUtils);
  
		System.out.println("userCode   ::   " + userToken.getUserCode());

		QDataAskMessage sidebarAsk = QuestionUtils.getAsks("PER_SOURCE", "PER_TARGET", "QUE_PROJECT_SIDEBAR_GRP", serviceToken.getToken());

		if (sidebarAsk == null) {
			System.out.println("sidebarAsk is not in cache");

		} else {

			/* TODO: Make this recursive through all levels of childAsks */

			ArrayList<Ask> askList = new ArrayList<>();

			for (Ask childAsk : sidebarAsk.getChildAsks()) {
				String code = "SIDEBAR_" + childAsk.getQuestionCode();

				if (capabilityUtils.hasCapabilityThroughPriIs(code, CapabilityMode.VIEW)) {
					/* System.out.println("Has Permission for " + code); */
					askList.add(childAsk);
				}
			}

			Ask[] items = askList.toArray(new Ask[askList.size()]);
			sidebarAsk.setChildAsks(items);
			
			String json = JsonUtils.toJson(sidebarAsk);
			json = json.replaceAll("PER_SERVICE", userToken.getUserCode());
			json = json.replaceAll("PER_SOURCE", userToken.getUserCode());
			json = json.replaceAll("PER_TARGET", userToken.getUserCode());

			sidebarAsk = JsonUtils.fromJson(json, Ask.class);
			/* send the addItems asks */
			QDataAskMessage askMsg = new QDataAskMessage(sidebarAsk);
			askMsg.setToken(userToken.getToken());
			VertxUtils.writeMsg("webcmds", askMsg);
		}

end
