package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAttributeMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.RulesUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.rule.RuleDetails;
import life.genny.model.OutputParamTreeSet;


rule "AUTH_INIT_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "AUTH_INIT")
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
		dom : OutputParamTreeSet()
    then
	
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );

		if (dom == null) {
		
			output.setFormCode("FRM_APP","FRM_ROOT");
		} else {
			output = dom.getLast();
		}

		retract( $message);
end




	