package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;

rule "DEFAULT_EVENT"
    ruleflow-group 'EventProcessing'
    no-loop
    salience -10000
    when 
		$message : QEventMessage( (data.code != "QUE_LOGOUT") && (data.code != "LOGOUT") && (event_type != "WF") )
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()   
    then
		System.out.println( ruleDetails + " " + drools.getRule().getName() + " Processing DEFAULT 2: " + $message );
		output.setTypeOfResult("SIGNAL");
		output.setResultCode($message.getData().getCode()); 
		output.setAskTargetCode($message.getData().getTargetCode()); 
		output.setAskSourceCode($message.getData().getSourceCode()); 
		output.setSuitCase($message.getData().getParentCode()); 

		update(output);
		retract($message); 
end
