package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QEventDropdownMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;

rule "FILTER_EVENT"
    ruleflow-group 'EventProcessing'
		salience 200
    no-loop
    when
		message : QEventMessage( 
					data.parentCode matches "QUE_FILTER_GRP_.*" &&
					( 
						data.code matches "PRI_.*" || 
						data.code matches "LNK_.*" || 
						data.code matches "AND_.*" 
					) 
				)
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		beUtils : BaseEntityUtils()
    then
		System.out.println(drools.getRule().getName()+" Processing : " + message );

		String attributeCode = message.getData().getCode();
		String searchCode = message.getData().getParentCode().split("QUE_FILTER_GRP_")[1];

		SearchEntity searchBE = VertxUtils.getObject(beUtils.getGennyToken().getRealm(), "", searchCode, SearchEntity.class,
				beUtils.getGennyToken().getToken());

		searchBE.removeAttribute(attributeCode)

		System.out.println("Performing search...");

		long totalTime = TableUtils.searchTable(beUtils, searchBE, true);
		System.out.println("total took " + (totalTime) + " ms"); 

		TableUtils.sendFilterQuestions(beUtils, searchBE);
			
		retract(message);
end
