package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;
import java.util.HashMap;
import java.util.Map;

rule "INIT_EVENT"
	ruleflow-group 'EventProcessing'
	no-loop
	salience 10000
	when
		$message : QEventMessage()
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
		displayCodes : HashMap(displayCodes["DISPLAY"] matches "DISPLAY" )
	
	then
		System.out.println(drools.getRule().getName() + " triggered");
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		
		QCmdMessage msg = new QCmdMessage("DISPLAY", "NONE");
		msg.setToken(beUtils.getGennyToken().getToken());
		msg.setSend(true);  		

		String code = $message.getData().getCode();
		if(code != null && !code.isEmpty()){
		
			if(displayCodes.containsKey(code)){
		
				String displayType = displayCodes.get(code);
				
				if(displayType != null && !displayType.isEmpty()){
					
					System.out.println("DISPLAY_TYPE   ::   " + displayType);
					msg.setCode(displayType);

				}
			}
		}
		
		VertxUtils.putObject(serviceToken.getRealm(), "", "DISPLAY_CODES", displayCodes, serviceToken.getToken());
		
		/* Send cmd message */
		VertxUtils.writeMsg("webcmds",msg);
end