package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;

rule "LOGOUT_EVENT"
    ruleflow-group 'EventProcessing'
    no-loop
    salience 500
    when
		$message : QEventMessage( data.code == "QUE_LOGOUT" )
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
    then
	
		System.out.println("Processing Answer/Data LOGOUT: " + $message );
		output.setResultCode("USER_LOGOUT");
		output.setTypeOfResult("LOGOUT");
		
		retract($message);

end