package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAttributeMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.RulesUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.rule.RuleDetails;


rule "MULTI_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "MULTI_EVENT")
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		/* This is an attribute change event */
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );

		output.setTypeOfResult("NONE");


		retract( $message);
end




	