package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;
import java.util.HashMap;
import java.util.Map;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import org.apache.commons.lang3.StringUtils;

rule "FORM_SUBMIT"
	ruleflow-group 'EventProcessing'
	no-loop
	salience 9500
	when
		$message : QEventMessage((data.code == "QUE_SUBMIT"))
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
	
	then
		System.out.println(drools.getRule().getName() + " triggered");
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String code = $message.getData().getCode();

		String parentCode = $message.getData().getParentCode();
		String targetCode = $message.getData().getTargetCode();

		System.out.println("parentCode  ::  " + parentCode);
		System.out.println("targetCode  ::  " + parentCode);

		if(parentCode != null && !parentCode.isEmpty()){

			/* extract the searchCode from parentCode */
			String sbeCode = StringUtils.substringBetween(parentCode, "QUE_", "_GRP");
			System.out.println("sbeCode  :: " + sbeCode);

			if(targetCode != null && !targetCode.isEmpty()){
				TableUtils.searchTable(beUtils, sbeCode, true, "PRI_CODE", targetCode);
			}

		}else{
			System.out.println("Parent code is null in event message");
		}
		/* retract( $message); */
end