package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Edit Note"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_EDIT_NOTE") &&
						!isState("LOOP_TRIGGER_EDIT_NOTE") )
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_EDIT_NOTE");

        String noteCode = rules.getAsString("itemCode");
		if(noteCode == null) {
			rules.setState("SEND_TOAST_SOMETHING_WENT_WRONG");
			return;
		}
		
		/* send questions to edit note */
		rules.setState("SEND_EDIT_NOTE_QUESTION");
	 	rules.footer();
end


