package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Edit Note Quesiton"
	when
		rules: QRules(  isState("SEND_EDIT_NOTE_QUESTION") &&
						!isState("LOOP_SEND_EDIT_NOTE_QUESTION") )
	 then
	 	rules.header();
		rules.setState("LOOP_SEND_EDIT_NOTE_QUESTION");

        String noteCode = rules.getAsString("itemCode");
		if(noteCode == null) {
			rules.setState("SEND_TOAST_SOMETHING_WENT_WRONG");
			return;
		}
		
        /* Send Note  */
        rules.askQuestions(rules.getUser().getCode(), noteCode, "QUE_EDIT_NOTE_GRP");
	 	rules.footer();
end


