package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.QwandaUtils;

rule "NOTE_EVENT_INTERN_WF"
	ruleflow-group 'TriggeredFromWF'
	salience 2
	no-loop
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		key : String(key.equals("Intern"))
		targetBE : BaseEntity()
	then
		System.out.println(drools.getRule().getName() + " triggered");
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String targetCode = targetBE.getCode();
		System.out.println("targetCode :: " + targetCode);

		if(targetCode != null){
			try {
				String endPoint = GennySettings.projectUrl + "/v7/notes";
				System.out.println("endPoint :: " + endPoint);

				String url = endPoint + "/"+targetCode + "?tags=&pageIndex=0&pageSize=100";
				System.out.println("url :: " + url);

				String notes = QwandaUtils.sendGET(url, serviceToken.getToken());
				System.out.println("notes :: " + notes);
				
				
				/* Internship Details */	
				String internName = targetBE.getValue("PRI_NAME", null);
				System.out.println("internName: " +internName);
				
				String internImage = targetBE.getValue("PRI_IMAGE_URL", null);
				System.out.println("internImage: " +internImage);


				/* Search for Applications */
				String linkedApps = targetBE.getValue("LNK_APPLICATIONS", null);
				
				if (linkedApps != null){
					System.out.println("linkedApps: " +linkedApps);									/*["APP_AA3FEB35-FD12-49B9-A595-AA315773A37F","APP_41484401-7C82-4CD0-9B75-AA9E224B23ED"]*/
					linkedApps = linkedApps.replace("\"", "").replace("[", "").replace("]", "");	
					System.out.println("linkedApps: " +linkedApps);									/*APP_AA3FEB35-FD12-49B9-A595-AA315773A37F,APP_41484401-7C82-4CD0-9B75-AA9E224B23ED*/
					
					String[] splitApps = linkedApps.split(",");
					int length = splitApps.length;
					System.out.println("length: " +length);	
					
					BaseEntity[] beCodez = new BaseEntity[length];
					BaseEntity appBe = null;
					
					
					for (int i = 0; i < length; i++) {
						appBe = beUtils.getBaseEntityByCode(splitApps[i]);
						beCodez[i] = appBe;
						System.out.println("beCodez: " +beCodez[i]);
					}
					
					QDataBaseEntityMessage msgMatches = new QDataBaseEntityMessage(beCodez);
					msgMatches.setToken(userToken.getToken());
					msgMatches.setReplace(true);
					VertxUtils.writeMsg("webcmds", JsonUtils.toJson(msgMatches));
				}
				/*String[] tagList = {"Business Development", "Placement", "Outcome Life", "Miscellaneous"};*/
				
				
				if(notes != null){
					JsonObject json = new JsonObject(notes);
					json.put("token", userToken.getToken());
					
					JsonObject jsonIntern = new JsonObject();
					jsonIntern.put("code", targetCode);
					jsonIntern.put("title", internName);
					jsonIntern.put("image", internImage);
					json.put("Tab_Intern", jsonIntern);
					/*jsonIntern.put("tagList", tagList);*/
					
					JsonObject jsonApplication = new JsonObject();
					json.put("linkedApps", linkedApps);
					
					System.out.println("json :: " + json.toString());
					VertxUtils.writeMsg("webcmds", json.toString());
				}
				
				
				
			} catch (Exception e) {
				System.out.println("Exception :: " + e);
			}
		}

		retract(key);
	end


