package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.GennySettings;

import java.util.List;
import java.util.ArrayList;

rule "OHS_VALIDATION"
    ruleflow-group 'Validation'
    no-loop true
    salience 1000 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("OHS"))
		HCBe : BaseEntity()

	  
     then
 		System.out.println("OHS_VALIDATION: Rule fired" );
 		System.out.println("OHS_VALIDATION: HCBe = " + HCBe.getCode()); 
 		
 	    /* Construct answer with Source, Target, Attribute Code, Value */
 		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
 		
		
		/* Check Validation Status of HC */
		
		String validationStatus = HCBe.getValue("PRI_VALIDATION", "Incomplete");
		if (validationStatus != null) {
		
				Answer ohsAnswer = new Answer();
				
				if (validationStatus.equals("Incomplete")) {
						ohsAnswer = new Answer(userToken.getUserCode(), HCBe.getCode() ,"PRI_VALIDATION", "OHS");
 						beUtils.saveAnswer(ohsAnswer);
						System.out.println("PRI_VALIDATION set to : OHS");
				}
				
				if (validationStatus.equals("HCS")) {
						ohsAnswer = new Answer(userToken.getUserCode(), HCBe.getCode() ,"PRI_VALIDATION", "Ready");	
						beUtils.saveAnswer(ohsAnswer);
						System.out.println("PRI_VALIDATION set to : Ready");  
						
						/* Send Email/signal to Agent fro HC Val */	
				} 
		} else {
			System.out.println("ERROR: Null validationStatus");
		}
		
		VertxUtils.sendToFrontEnd(userToken, ohsAnswer);
		

	
end
