package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwandautils.GennySettings;

import java.util.List;
import java.util.ArrayList;

rule "SEND_VALIDATED_BE"
    ruleflow-group 'Validation'
    no-loop true
    salience 100 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		targetBe : BaseEntity()
		beUtils : BaseEntityUtils()
	  
     then
 		System.out.println("SEND_VALIDATED_BE: Rule fired" );
 		System.out.println("SEND_VALIDATED_BE: targetBe = " + targetBe.getCode()); 
 		
		BaseEntity refreshedTargetBe = beUtils.getBaseEntityByCode(targetBe.getCode());

		QDataBaseEntityMessage beMsg = new QDataBaseEntityMessage(refreshedTargetBe);
		beMsg.setToken(userToken.getToken());
		VertxUtils.writeMsg("webcmds", beMsg);
		
		retract(targetBe)
	
end
