package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
rule "ADD_NEW_INTERNSHIP_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code == "QUE_ADD_NEW_INTERNSHIP")
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
    then
	
		System.out.println("Processing Answer/Data : cyrus" + $message );
		output.setResult("FRM_QUE_ADD_NEW_INTERNSHIP");
		retract( $message);
end