package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;
import org.apache.commons.lang3.StringUtils;

rule "FORM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_.*" && data.parentCode == "QUE_OPTIONS_GRP" )
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );

		String code = $message.getData().getCode();

		if(code.matches("(.*)_MENU")) {
			System.out.println("MENU code found");
			String tempCode = StringUtils.removeEnd(code, "_MENU");
			code = tempCode + "_GRP";

		}

		output.setFormCode("FRM_"+ code,"FRM_CONTENT");
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" ->"+output);
		/* Now add the allowable answers */
		
		retract( $message);
end
