package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;

rule "FORM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_.*" && data.parentCode == "QUE_OPTIONS_GRP" )
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );

		String code = $message.getData().getCode();

		if(code.matches("(.*)_MENU_GRP")) {
			System.out.println("This is a menu question");

			String tempCode = code.split("_MENU_GRP")[0];
			String newCode = tempCode + "_GRP";
			code = newCode;
			System.out.println("newCode :: " + code);
		}

		output.setFormCode("FRM_"+ $message.getData().getCode(),"FRM_CONTENT");
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" ->"+output);
		/* Now add the allowable answers */
		
		retract( $message);
end
