package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;
import org.apache.commons.lang3.StringUtils;

rule "MERGE_DUPLICATE_EMAIL"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "merge" && data.parentCode matches "DUPLICATE_EMAILS" )
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
    then
		System.out.println("MERGE_DUPLICATE_EMAIL fired");
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String code = $message.getData().getCode();
		System.out.println("code: "+code);
		
		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = $message.getData().getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		/*
		code: merge
		parentCode: DUPLICATE_EMAILS
		sourceCode: PER_
		targetCode: PER_
		*/
		
		BaseEntity sourceBe = beUtils.getBaseEntityByCode(sourceCode);
		BaseEntity targetBe = beUtils.getBaseEntityByCode(targetCode);
		System.out.println("sourceBe :: " + sourceBe);
		System.out.println("targetBe :: " + targetBe);
		
		if (sourceBe != null && targetBe != null) {
		
			beUtils.duplicateAttributes(sourceBe, targetBe)
			
			targetBe = beUtils.getBaseEntityByCode(targetCode);
			
			QDataBaseEntityMessage msg = new QDataBaseEntityMessage(targetBe);
			msg.setToken(userToken.getToken());
			msg.setReplace(true);
			VertxUtils.writeMsg("webcmds", JsonUtils.toJson(msg));
			
			QCmdMessage toastMsg = new QCmdMessage("TOAST", "INFO");
			toastMsg.setMessage("Merging " + sourceCode + " and " + targetCode);
			toastMsg.setToken(beUtils.getGennyToken().getToken());
			toastMsg.setSend(true);
			VertxUtils.writeMsg("webcmds", toastMsg);
			
		} else {
			System.out.println("ERROR: Null sourceBe or targetBe. Merging failed");
			
			QCmdMessage msg = new QCmdMessage("TOAST", "INFO");
			msg.setMessage("Merging failed!");
			msg.setToken(beUtils.getGennyToken().getToken());
			msg.setSend(true);
			VertxUtils.writeMsg("webcmds", msg);
		}
		
		retract( $message);
end
