package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;
import org.apache.commons.lang3.StringUtils;

rule "MERGE_DUPLICATE_EMAIL"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "merge" && data.parentCode matches "DUPLICATE_EMAILS" )
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
    then
		System.out.println("MERGE_DUPLICATE_EMAIL fired");
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String code = $message.getData().getCode();
		System.out.println("code: "+code);
		
		String sourceCode = $message.getData().getSourceCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = $message.getData().getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		/*
		code: merge
		parentCode: DUPLICATE_EMAILS
		sourceCode: PER_
		targetCode: PER_
		*/
		
		BaseEntity sourceBe = beUtils.getBaseEntityByCode(sourceCode);
		BaseEntity targetBe = beUtils.getBaseEntityByCode(targetCode);
		System.out.println("sourceBe :: " + sourceBe);
		System.out.println("targetBe :: " + targetBe);
		
		if (sourceBe != null && targetBe != null) {
		
			System.out.println("Duplicating attributes");
			beUtils.duplicateAttributes(sourceBe, targetBe);
			
			targetBe = beUtils.getBaseEntityByCode(targetCode);
			System.out.println("targetBe :: " + targetBe);
			
			String type = beUtils.whoAreYou(targetCode);
			System.out.println("type :: " + type);
			
			if (targetCode.startsWith("PER_")){
					System.out.println("Deleting a Person");
					
					beUtils.saveAnswer(new Answer(userToken.getUserCode(), targetCode, type, false));
					beUtils.saveAnswer(new Answer(userToken.getUserCode(), targetCode, "PRI_IS_DELETED", true));
					beUtils.saveAnswer(new Answer(userToken.getUserCode(), targetCode, "PRI_EMAIL", "dummy@gada.io"));
					
					if (type.equals("PRI_IS_HOST_CPY_REP")) {
					
						BaseEntity hcrBe = beUtils.getBaseEntityByCode("targetCode");
						System.out.println("hcrBe = " + hcrBe);
					
						String assocHC = hcrBe.getValue("LNK_HOST_COMPANY", null);
						assocHC = assocHC.replace("\"", "").replace("[", "").replace("]", "");
						System.out.println("assocHC = " +assocHC);
					
						beUtils.removeQuantumLinkElement(userToken.getUserCode(), assocHC, targetCode, "LNK_HCRS");
					}
					
			}
			
			QDataBaseEntityMessage msg = new QDataBaseEntityMessage(targetBe);
			msg.setToken(userToken.getToken());
			msg.setReplace(true);
			VertxUtils.writeMsg("webcmds", JsonUtils.toJson(msg));
			
			QCmdMessage toastMsg = new QCmdMessage("TOAST", "INFO");
			toastMsg.setMessage("Merging " + sourceCode + " and " + targetCode);
			toastMsg.setToken(beUtils.getGennyToken().getToken());
			toastMsg.setSend(true);
			VertxUtils.writeMsg("webcmds", toastMsg);
			
		} else {
			System.out.println("ERROR: Null sourceBe or targetBe. Merging failed");
			
			QCmdMessage msg = new QCmdMessage("TOAST", "INFO");
			msg.setMessage("Merging failed!");
			msg.setToken(beUtils.getGennyToken().getToken());
			msg.setSend(true);
			VertxUtils.writeMsg("webcmds", msg);
		}
		
		retract( $message);
end
