package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;

import java.util.List;
import java.util.ArrayList;

rule "DEFS"
    ruleflow-group 'DevPortalContent'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		code : String(code == "DEFS")
     then
 		System.out.println(drools.getRule().getName() + ": Rule fired"); 

		String displayCode = "NONE";
		String searchCode = "SBE_DEFS";
		String askCode = "NONE";
		String entityCode = "NONE";
 		
		insert(displayCode);
		insert(searchCode);
		insert(askCode);
		insert(entityCode);
end
