package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
rule "ADD_ITEM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_.*" && data.parentCode == "QUE_ADD_ITEMS_GRP" )
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
    then
	
		System.out.println("Processing Answer/Data : " + $message );
		System.out.println("ADD_ITEM_CLICK_EVENT :: Parent code :  " + $message.getData().getParentCode());
		
		switch($message.getData().getCode()){
			
			case "QUE_ADD_NEW_INTERNSHIP":output.setResult("FRM_QUE_ADD_INTERNSHIP_STEP_ONE_GRP");  break;
			
			case "QUE_ADD_NEW_COMPANY": output.setResult("FRM_QUE_SELECT_COMPANY_TYPE_GRP");break;
			
			case "QUE_ADD_NEW_PERSON":output.setResult("FRM_QUE_SELECT_USER_TYPE_GRP"); break;
			
			case "QUE_ADD_NEW_INTERNSHIP_TEMPLATE": output.setResult("FRM_QUE_ADD_INTERNSHIP_TEMPLATE_AGENT_GRP"); break;
			
			default : output.setResult("FRM_" +$message.getData().getCode() + "_GRP");; break;
		}
			
		retract( $message);
end