package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "PLACED_TIMER"
    ruleflow-group 'Timer'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		bucketCode : String(bucketCode.equals("Placed"))

	  
     then
 		System.out.println("Placed Timer: Rule fired" );  		
 		
		output.setResultCode("PT1S");
		output.setTargetCode("PT2S");
		
	
		retract(bucketCode)

		
end
