package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "SHORTLIST_TIMER"
    ruleflow-group 'Timer'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		bucketCode : String(bucketCode.equals("Shortlist"))

	  
     then
 		System.out.println("Shortlist Timer: Rule fired" );  		
 		
		output.setResultCode("PT1S");
		output.setTargetCode("PT2S");
		
		/*System.out.println("Shortlist output: " + output);*/
	
		retract(userToken)
		retract(serviceToken)
		retract(bucketCode)

		
end
