package life.genny.rules;

import life.genny.utils.OutputParam;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Answer;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.TableUtils;
import life.genny.qwandautils.GennySettings;
import life.genny.jbpm.customworkitemhandlers.ShowFrame;
import life.genny.qwanda.rule.RuleDetails;

rule "QUE_TABLE_PREVIOUS_BTN"
	ruleflow-group 'EventProcessing'
	salience 2
	no-loop
	when
		$message : QEventMessage(data.code matches "QUE_TABLE_PREVIOUS_BTN" )	
		userToken : GennyToken ( code != "PER_SERVICE" ) 
		output : OutputParam( )
		ruleDetails : RuleDetails()
	then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing Answer/Data : " + $message );
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Parent code :  " + $message.getData().getParentCode());
		
		BaseEntityUtils beUtils = new BaseEntityUtils(userToken); 
		
		/* get current search */
		SearchEntity searchBE = TableUtils.getSessionSearch("SBE_SEARCHBAR",userToken);
			
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" PREV for "+searchBE.getCode()); 
		
		Integer pageIndex = searchBE.getValue("SCH_PAGE_START",0);
		Integer pageSize = searchBE.getValue("SCH_PAGE_SIZE",GennySettings.defaultPageSize); /* TODO, don't let this be 0 */
		pageIndex = pageIndex - pageSize;
		
		if (pageIndex <0) {
			pageIndex = 0;
		}
		
		Integer pageNumber = (pageIndex / pageSize) + 1;
		
		
			Answer pageAnswer = new Answer(beUtils.getGennyToken().getUserCode(),searchBE.getCode(), "SCH_PAGE_START", pageIndex+"");
			Answer pageNumberAnswer = new Answer(beUtils.getGennyToken().getUserCode(),searchBE.getCode(), "PRI_INDEX", pageNumber+"");

		searchBE = beUtils.updateBaseEntity(searchBE, pageAnswer,SearchEntity.class);
		searchBE = beUtils.updateBaseEntity(searchBE, pageNumberAnswer,SearchEntity.class);
			
			VertxUtils.putObject(beUtils.getGennyToken().getRealm(), "", searchBE.getCode(), searchBE,
				beUtils.getGennyToken().getToken());
			
	        ShowFrame.display(userToken, "FRM_TABLE_VIEW", "FRM_CONTENT", "Test");
 		    TableUtils.performSearch(userToken , beUtils, "SBE_SEARCHBAR", null);

			
  	    output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */
  	      
  	    retract( $message);
  	    update(output);
end