package life.genny.rules;

import life.genny.utils.OutputParam;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Answer;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.TableUtils;


rule "QUE_TABLE_PREVIOUS_BTN"
	ruleflow-group 'EventProcessing'
	salience 2
	no-loop
	when
		$message : QEventMessage(data.code matches "QUE_TABLE_PREVIOUS_BTN" )	
		userToken : GennyToken ( code != "PER_SERVICE" ) 
		output : OutputParam( )
	then
		System.out.println("Processing Answer/Data : " + $message );
		System.out.println("Parent code :  " + $message.getData().getParentCode());
		
		BaseEntityUtils beUtils = new BaseEntityUtils(userToken); 
		
		/* get current search */
		String searchBarCode = "SBE_SEARCHBAR";
		String sessionSearchCode = searchBarCode + "_" + beUtils.getGennyToken().getSessionCode();
		SearchEntity searchBE = VertxUtils.getObject(userToken.getRealm(), "", sessionSearchCode, SearchEntity.class,
				userToken.getToken());

		if (searchBE == null) {
			searchBE = VertxUtils.getObject(userToken.getRealm(), "", searchBarCode, SearchEntity.class,
					userToken.getToken());
		}
		
		
		System.out.println("PREVIOUS"); 
		
		Integer pageIndex = searchBE.getValue("SCH_PAGE_START",0);
		Integer pageSize = searchBE.getValue("SCH_PAGE_SIZE",10);
		pageIndex = pageIndex - pageSize;
		
		Integer pageNumber = searchBE.getValue("PRI_INDEX", 1);
		pageNumber = pageNumber - 1;

		if (pageIndex < 0) {
			pageIndex= 0;
			pageNumber = 1;
		}
		
		Answer pageAnswer = new Answer(beUtils.getGennyToken().getUserCode(),sessionSearchCode, "SCH_PAGE_START", pageIndex+"");
		Answer pageNumberAnswer = new Answer(beUtils.getGennyToken().getUserCode(),sessionSearchCode, "PRI_INDEX", pageNumber+"");

		beUtils.addAnswer(pageAnswer);
		beUtils.addAnswer(pageNumberAnswer);

		beUtils.updateBaseEntity(searchBE, pageAnswer);
		beUtils.updateBaseEntity(searchBE, pageNumberAnswer);
			
  	TableUtils.paginateTable(userToken , beUtils, "SBE_SEARCHBAR", null);
		
		retract( $message);
		output.setFormCode("FRM_TABLE_VIEW","FRM_CONTENT"); 
end