package life.genny.rules;

import life.genny.utils.OutputParam;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;

rule "QUE_TABLE_NEXT_BTN"
    ruleflow-group 'EventProcessing'
	salience 2
    no-loop
    when
    	
		$message : QEventMessage(data.code matches "QUE_TABLE_.*" )	
		userToken : GennyToken (code != "PER_SERVICE" )
		output : OutputParam( )
    then
	
		System.out.println("Processing Answer/Data : " + $message );
		System.out.println("Parent code :  " + $message.getData().getParentCode());
		
		switch($message.getData().getCode()){

			case "QUE_TABLE_NEXT_BTN" : System.out.println("NEXT"); break;

			case "QUE_TABLE_PREV_BTN" : System.out.println("PREV"); break;

			default : System.out.println("ERROR!! "+$message.getData().getCode()+" DETECTED");	break;
		}
		
		
		retract( $message);
end
