package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.utils.SessionFacts;

rule "START_UNITY_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_TREE_ITEM_MESSAGES_NOTIFICATIONS" && (data.rootCode == "QUE_TREE_ITEM_MESSAGES_GRP"))
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
		
    then
		System.out.println("Processing APPLY EVENT : " + $message );
		/*output.setFormCode("FRM_QUE_ADD_APPLICATION_GRP","FRM_CONTENT");*/
		
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		String workflowSignalCode = "UNITY_EVENT";

		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_"+workflowSignalCode);
		output.setTargetCode($message.getData().getTargetCode());
		
		/*String assIntBeCode = output.getTargetCode();
		String s1 = assIntBeCode.substring(assIntBeCode.indexOf("target=")+1);
		s1.trim();*/
		/*String s1 = assIntBeCode.split("=")[3];*/
		/*String s2 = s1.split(":")[0];
		System.out.println(s2);
		
		System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$ targetCode: " + assIntBeCode);
		System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$ targetCode: " + s2);*/
		System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$ targetCode: " + output.getTargetCode());
		
		SessionFacts facts = new SessionFacts(serviceToken, userToken, output.getTargetCode());
		/*SessionFacts facts = new SessionFacts(serviceToken, userToken, output.getTargetCode());*/
		
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("STARTING THE NEW APPLICATION WITH: " +output);
	
		retract( $message);
	end
