package life.genny.rules;

global life.genny.qwanda.message.QBulkMessage payload;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.CapabilityUtils;
import life.genny.qwanda.Answer;
import java.util.List;
import java.util.ArrayList;
import life.genny.model.OutputParamTreeSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QBulkMessage;

rule "ACTION_CACHE_LOGOUT"
    ruleflow-group 'ActionCaches'
     salience 5000
     no-loop true
    when
      beUtils : BaseEntityUtils()
	  userToken : GennyToken ( code != "PER_SERVICE" ) 
	  serviceToken : GennyToken ( code == "PER_SERVICE" )
	  not QCmdMessage( code == "LOGOUT")
    then
   		System.out.println("Rule -> "+drools.getRule().getName()+" :  user=" + userToken.getUserCode());
   		
 		QCmdMessage msg = new QCmdMessage("LOGOUT", "LOGOUT");
 		msg.setExec(false);
 		msg.setSend(true);
 		msg.setCache("QUE_OPTIONS_GRP:QUE_OPTIONS_GRP:QUE_LOGOUT"); /* trigger codes */
		msg.setToken(userToken.getToken());
  		
  		VertxUtils.writeMsg("webcmds",msg);
		/* payload.add(msg); */
				
	/*	drools.getKnowledgeRuntime().setGlobal("payload", payload); */
		insert(msg); /* to stop refire */
end
