package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;


rule "SEND_BUCKET_CODES"
	ruleflow-group 'BucketProcessing'
	salience 8
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
		/* allowed: Allowed(code == "BUCKETS" && mode == CapabilityMode.VIEW) */

	then
		System.out.println(drools.getRule().getName() + " triggered");
		Boolean cache = true;

		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);
		CapabilityUtils capabilityUtils = new CapabilityUtils(beUtils);
  
		String sessionCode = beUtils.getGennyToken().getSessionCode().toUpperCase();
		System.out.println("userCode   ::   " + userToken.getUserCode());
		System.out.println("sessionCode   ::   " + sessionCode);

		/* get BUCKET_CODES from cache */
		List<String> bucketCodes = VertxUtils.getObject(serviceToken.getRealm(), "", "BUCKET_CODES", List.class);
		List<String> sendCodes = new ArrayList<>();

		System.out.println("bucketCodes:");
		System.out.println(bucketCodes);

		if(bucketCodes!= null && bucketCodes.size() > 0){

			for (String code : bucketCodes) {
				if (capabilityUtils.hasCapabilityThroughPriIs(code, CapabilityMode.VIEW)) {
					System.out.println("Has Permission for " + code);
					sendCodes.add(code);
				}
				/* sendCodes.add(code); */
			}
			System.out.println("Adding sessionCode");

			List<String> sbeSessionCodes = sendCodes.stream().map(code -> code+"_"+sessionCode).collect(Collectors.toList());

			System.out.println("1. Sending bucketCodes !");
			System.out.println(sbeSessionCodes);

			/* Send summary arrayCodes */
			QCmdMessage msg = new QCmdMessage("BUCKET_CODES", "BUCKET_CODES");
			msg.setTargetCodes(sbeSessionCodes);
			msg.setToken(beUtils.getGennyToken().getToken());
			msg.setSend(true);  		
			VertxUtils.writeMsg("webcmds",msg);

		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		/* retract(allowed); */ 

end
