package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.QwandaUtils;

rule "NOTE_EVENT_APPLICATION_WF"
	ruleflow-group 'TriggeredFromWF'
	salience 2
	no-loop
	when
		/*userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )*/
		key : String(key.equals("Application"))
		/*targetBE : BaseEntity()*/
	then
		System.out.println("HOLY FUCK PLS WORK");
		
		
		retract(key);
	end


