package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAttributeMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.RulesUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.rule.RuleDetails;
import life.genny.utils.SessionFacts;
import org.kie.api.runtime.KieSession;
import org.kie.api.runtime.process.WorkflowProcessInstance;


rule "ADD_ITEM"
    ruleflow-group 'EventProcessing'
	salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_ADD_EDU_PROVIDER_GRP") 		
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then

		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );

		output.setTypeOfResult("SIGNAL");
		output.setResultCode("CREATE_EDU_PROVIDER");

		retract( $message);
end




	