package life.genny.rules;



import life.genny.rules.listeners.JbpmInitListener;
import life.genny.models.GennyToken;



rule "eventListenerUserSetup"
salience 10000
    no-loop true
    when
    	userToken: GennyToken(code == "userToken")
     	serviceToken: GennyToken(code == "PER_SERVICE")
    then
     System.out.println("Setup Listener for userToken!");
    kcontext.getKnowledgeRuntime().addEventListener(new JbpmInitListener(userToken)); 

end



