package life.genny.rules;


import life.genny.rules.listeners.JbpmInitListener;
/* import org.kie.api.runtime.process.WorkflowProcessInstance; */
import life.genny.models.GennyToken;




rule "eventListenerServiceSetup"
salience 10000
    no-loop true
    when
    serviceToken: GennyToken(code == "serviceToken" )

    then
     System.out.println("Setup Startup Listener for serviceToken!");
     kcontext.getKnowledgeRuntime().addEventListener(new JbpmInitListener(serviceToken)); 

end


