package life.genny.rules;

import life.genny.rules.listeners.JbpmInitListener;
import life.genny.models.GennyToken;

rule "eventListenerServiceWorkflowSetup"
salience 10000
    no-loop true
    when
 /*   	not WorkflowProcessInstance( ) */
     	serviceToken: GennyToken(code == "PER_SERVICE")
    then
    /* System.out.println("Setup Listener for serviceToken! Workflow startup"); */
    kcontext.getKnowledgeRuntime().addEventListener(new JbpmInitListener(serviceToken)); 

end