package life.genny.rules;


import life.genny.rules.listeners.JbpmInitListener;
import life.genny.rules.listeners.GennyAgendaEventListener;
import org.kie.api.runtime.process.WorkflowProcessInstance; 
import life.genny.models.GennyToken;




rule "eventListenerServiceSetup"

  salience 10000 
    when
		$process : WorkflowProcessInstance( ) 
		 not  GennyToken (code == "PER_SERVICE")
    then
    /* System.out.println("Setup Startup Listener2 for serviceToken!  in eventListenerServiceSetup"); */
     GennyToken serviceToken =  (GennyToken)$process.getVariable("serviceToken");
    /* System.out.println("ServiceToken detected ==== "+serviceToken.getCode()); */

     insert(serviceToken);
     

end