package life.genny.rules;

import org.apache.commons.lang3.StringUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import com.google.gson.reflect.TypeToken;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.VertxUtils;
import life.genny.utils.TableUtils;
import life.genny.models.TableData;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Ask;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.utils.OutputParam;
import life.genny.jbpm.customworkitemhandlers.ShowFrame;

import java.util.List;
import java.util.ArrayList;

import java.util.concurrent.Callable;
import java.util.concurrent.CompletionService;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorCompletionService;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import life.genny.utils.SearchCallable;
import life.genny.utils.TableFrameCallable;
import life.genny.utils.CacheSearchUtils;

rule "ADD_PCM"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
			message : QEventMessage( data.code == "ADD_PCM" && data.parentCode == "ADD_PCM" )
			userToken : GennyToken (code != "PER_SERVICE" )
			serviceToken : GennyToken( code == "PER_SERVICE")
			output : OutputParam( )
			ruleDetails : RuleDetails()
			beUtils : BaseEntityUtils()
    then
			System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processings : " + message );

			System.out.println("Adding PCM...");

			BaseEntity defBE = beUtils.getDEFByCode("DEF_PCM");

			BaseEntity newBe = beUtils.create(defBE, "PCM_TEST2", "PCM Test 2");

			beUtils.saveAnswer(new Answer(userToken.getUserCode(), "PCM_TEST2", "PRI_IS_PCM", "TRUE"));
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), "PCM_TEST2", "PRI_TEMPLATE_CODE", "TPL_TEST1"));
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), "PCM_TEST2", "PRI_LOC1", "PRI_FIRSTNAME"));
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), "PCM_TEST2", "PRI_LOC2", "PRI_EMAIL"));
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), "PCM_TEST2", "PRI_LOC3", "PRI_LASTNAME"));

			retract(message);
			output.setTypeOfResult("NONE");
			output.setResultCode("NONE");  /* dont display anything new */
		end
