package life.genny.rules;

import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Ask;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QMessageGennyMSG;
import life.genny.qwanda.message.QBaseMSGMessageType;
import life.genny.utils.OutputParam;
import java.util.List;
import java.util.ArrayList;

rule "MESSAGES_TEST"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
			message : QEventMessage(data.code == "MESSAGES_TEST" && data.parentCode == "MESSAGES_TEST_GRP" )
			userToken : GennyToken (code != "PER_SERVICE" )
			serviceToken : GennyToken( code == "PER_SERVICE")
			output : OutputParam( )
			ruleDetails : RuleDetails()
			beUtils : BaseEntityUtils()
    then
			System.out.println(drools.getRule().getName()+" Processings : " + message );

			/* QMessageGennyMSG msg = new QMessageGennyMSG(QBaseMSGMessageType.SMS); */
			/* msg.addContext("BODY", "This is a test SMS"); */
			/* msg.addRecipient("0468434324"); */
			/* msg.setToken(beUtils.getGennyToken().getToken()); */

			BaseEntity intern = beUtils.getBaseEntityByCode("PER_6518983B-1B29-48F1-B2BD-B2D84354B614");

			QMessageGennyMSG msg = new QMessageGennyMSG(QBaseMSGMessageType.SLACK);
			msg.setTemplateCode("MSG_TEST_SLACK");
			msg.addContext("INTERN", intern);
			msg.setToken(beUtils.getGennyToken().getToken());
			
			VertxUtils.writeMsg("messages", msg);
			System.out.println("SENT!!!");

			retract(message);
			output.setTypeOfResult("NONE");
			output.setResultCode("NONE");  /* dont display anything new */
		end
