package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;

rule "FRM_FOOTER"
    ruleflow-group 'GenerateFrames'

    when
      not  Frame3(code == "FRM_FOOTER")
      serviceToken : GennyToken( code == "PER_SERVICE")
      FRM_DUMMY : Frame3 ( code == "FRM_DUMMY" )
    then
     System.out.println("   Generate FRM_FOOTER Rule  "+serviceToken.getUserCode());

 	Frame3 frame = Frame3.builder("FRM_FOOTER")
 							.addFrame(FRM_DUMMY, FramePosition.CENTRE)
 								.end()
							.addTheme("THM_BACKGROUND_BLUE")
								.end()
							.build();
						
	frame.setRealm(serviceToken.getRealm());
						
	insert (frame);
	
	VertxUtils.putObject(serviceToken.getRealm(), "", frame.getCode(), frame, serviceToken.getToken());
	Set<QDataAskMessage> askMsgs = new HashSet<QDataAskMessage>();

	QDataBaseEntityMessage msg = FrameUtils2.toMessage(frame, serviceToken, askMsgs);
	VertxUtils.putObject(serviceToken.getRealm(), "", frame.getCode()+"-MSG", msg, serviceToken.getToken());

end
