package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.Answer;

rule "Pre Init Route Change"
    when
	  m : QEventMessage( event_type == "ROUTE_CHANGE" )
	  rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED") && !isState("ROUTE_CHANGE_LOOP"))
     then
        rules.setDrools(drools);
        rules.header();

        rules.set("m",m);
        rules.startWorkflow("com.sample.bpmn.routechange");

        rules.footer();

end
