package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init Btn Click"
    when
      m : QEventMessage( event_type == "BTN_CLICK" )
      rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED") && !isState("LOOP_PREINIT_BUTTON"))
    then
      rules.setDrools(drools);
      rules.header();
      
      rules.setState("LOOP_PREINIT_BUTTON");
      rules.println("RULE INIT BTN_CLICK: " + m);

      String code = m.getData().getCode(); 
      String parentCode = m.getData().getParentCode(); 
      String rootCode = m.getData().getRootCode();

      rules.println("code         ::   " + code);
      rules.println("parentCode   ::   " + parentCode);
      rules.println("rootCode     ::   " + rootCode);
      
      rules.println("========= STATES ===========");

      rules.println("rootCode     ::   " + "ROOT_" + rootCode);
      rules.println("parentCode   ::   " + "PARENT_" + parentCode);
      rules.println("code         ::   " + code);


      if(code != null) {
        rules.setState(code);
        rules.set("code", code);
      }

      if(parentCode != null) {
        rules.setState("PARENT_" + parentCode);
        rules.set("parentCode", parentCode);
      }

      if(rootCode != null) {
        rules.setState("ROOT_" + rootCode);
        rules.set("rootCode", rootCode);
      }
        
      rules.setState("STARTED");
      rules.setState("EVENT_BTN_CLICK");
      rules.footer();
end

