package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_INDUSTRY"
	ruleflow-group 'DataProcessing'
			salience 5000
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_INDUSTRY")
		answersToSave : Answers()
		ruleDetails : RuleDetails()
		output : OutputParam( )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println("HELPER_LNK_INDUSTRY fired");
		System.out.println("Did you actually update??");
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing Helper INDUSTRY SELECTION Answer/Data : " + answer );
		
		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		System.out.println("Did you actually update??");
		
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		System.out.println("Did you actually update??");
		
		String industryCode = answer.getValue();
		System.out.println("industryCode :: " + industryCode);
		System.out.println("Did you actually update??");
		
		String code = industryCode.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("code  :: " + code);
		System.out.println("Did you actually update??");

		answersToSave.add(answer);
		
		
		Answer occupationAnswer = new Answer(sourceCode, targetCode, "LNK_OCCUPATION", " ",false,true);
		System.out.println("occupationAnswer  :: " + occupationAnswer);
		System.out.println("Did you actually update??");

		BaseEntity baseEntity = beUtils.updateBaseEntity(targetCode,occupationAnswer);
		beUtils.updateBaseEntity(targetCode,occupationAnswer);
		System.out.println("baseEntity  :: " + baseEntity);
		
		insert(occupationAnswer);
		System.out.println("occupationAnswer  :: " + occupationAnswer);
		
		/* Update the baseenetity in frontend */
		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(baseEntity);
		msg.setToken(beUtils.getGennyToken().getToken());
		msg.setReplace(true);
		VertxUtils.writeMsg("webcmds",JsonUtils.toJson(msg));
		System.out.println("msg  :: " + msg);

		/* dropdown search here */
		DropdownUtils dropdown = new DropdownUtils(serviceToken);
		System.out.println("dropdown  :: " + dropdown);
		dropdown.setNewSearch("Dropdown", "Fetch Dropdown Items")
											.addColumn("PRI_NAME","Name")
											.setSourceCode(code)
											.setPageStart(0)
											.setPageSize(1000);
		System.out.println("dropdown  :: " + dropdown);

		dropdown.sendSearchResults("GRP_OCCUPATION_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);
		System.out.println("dropdown  :: " + dropdown);
		
		retract(answer);
		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
end
