package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;
import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_HOST_COMPANY_APP"
	ruleflow-group 'DataProcessing'
	salience 6000
	no-loop
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_HOST_COMPANY" && targetCode matches "APP_.*")
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")
	then
		System.out.println(drools.getRule().getName() + " triggered");

		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		String value = answer.getValue();
		System.out.println("value :: " + value);
		
		String code = beUtils.cleanUpAttributeValue(value);
		System.out.println("code  :: " + code);

		BaseEntity be = beUtils.getBaseEntityByCode(code);
		
		if(be !=null){
			String name = be.getValue("PRI_NAME", null);		
			if(name !=null){
				Answer assocHcrAnswer = new Answer(sourceCode, targetCode, "PRI_ASSOC_HC", name);
				beUtils.saveAnswer(assocHcrAnswer);
				VertxUtils.sendToFrontEnd(userToken, assocHcrAnswer);
			}
		}

		BaseEntity targetBe = beUtils.getBaseEntityByCode(targetCode);
		if(targetBe != null){
			String internship = targetBe.getValue("LNK_INTERNSHIP", null);
			if(internship != null){
				Answer internshipAnswer = new Answer(sourceCode, targetCode, "LNK_INTERNSHIP", "",false,true);
				Answer titleAnswer = new Answer(sourceCode, targetCode, "PRI_TITLE", "",false,true);
				beUtils.removeEntityAttribute(targetBe,"LNK_INTERNSHIP");
				beUtils.removeEntityAttribute(targetBe,"PRI_TITLE");
				VertxUtils.sendToFrontEnd(userToken, internshipAnswer, titleAnswer);
			}
		}

		/* This does not seem to be saving otherwise */
		beUtils.saveAnswer(answer);
		VertxUtils.sendToFrontEnd(userToken, answer);
		
		/* dropdown search here For internship */
		/* DropdownUtils dropdownInternship = new DropdownUtils(serviceToken); */
		/* dropdownInternship.setNewSearch("Internship Dropdown", "Fetch Internship Dropdown Items") */
		/* 									/1* Sorts *1/ */
		/* 									.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC) */
		/* 									/1* .addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC) *1/ */
		/* 									/1* .addSort("PRI_ASSOC_INDUSTRY","Industry",SearchEntity.Sort.ASC) *1/ */
		/* 									/1* .addSort("PRI_ASSOC_HC","Host Company",SearchEntity.Sort.ASC) *1/ */
		/* 									/1* .addSort("PRI_INTERNSHIP_START_DATE","Start Date",SearchEntity.Sort.ASC) *1/ */

		/* 									/1* Filters *1/ */
		/* 									.addFilter("PRI_IS_INTERNSHIP", true) */
		/* 									.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "BEG_%") */
		/* 									.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "ACTIVE") */
		/* 									.addFilter("LNK_HOST_COMPANY", SearchEntity.StringFilter.EQUAL, value) */
		/* 									.addFilter("PRI_ADDRESS_STATE", SearchEntity.StringFilter.LIKE, "%") */
		/* 									.addFilter("PRI_ASSOC_INDUSTRY", SearchEntity.StringFilter.LIKE, "%") */
											
		/* 										/1* Table Columns *1/ */
		/* 									.addColumn("PRI_IMAGE_URL", "Company Logo") */
		/* 									.addColumn("PRI_NAME", "Name") */
		/* 									.addColumn("PRI_STATUS", "Status") */
		/* 									.addColumn("PRI_ASSOC_HC", "Host Company") */
		/* 									.addColumn("PRI_ADDRESS_FULL", "Address") */
		/* 									.addColumn("PRI_INTERNSHIP_START_DATE", "Proposed Start Date") */
		/* 									.addColumn("PRI_ASSOC_INDUSTRY", "Industry") */
		/* 									.setPageStart(0) */
		/* 									.setPageSize(1000); */
		
		/* Send the dropdown options */
		/* dropdownInternship.sendSearchResults("GRP_INTERNSHIP_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false); */
end
