package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_HOST_COMPANY"
	ruleflow-group 'DataProcessing'
			salience 5000
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_HOST_COMPANY")
		answersToSave : Answers()
		ruleDetails : RuleDetails()
		output : OutputParam( )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+"Processing Helper HOST COMPANY SELECTION Answer/Data : " + answer );

		String sourceCode = beUtils.getGennyToken().getUserCode();
		String targetCode = answer.getTargetCode();
		String hostCompanyCode = answer.getValue();

		System.out.println("hostCompanyCode :: " + hostCompanyCode);
		String code = hostCompanyCode.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("hostCompanyCode after  :: " + code);

		/* clear the associated attribute's answer here */

		Answer repAnswer = new Answer(sourceCode, targetCode, "LNK_HOST_COMPANY_REP", " ",false,true);
		Answer supervisorAnswer = new Answer(sourceCode, targetCode, "LNK_INTERN_SUPERVISOR", " ",false,true);
		answersToSave.add(repAnswer);
		answersToSave.add(supervisorAnswer);

		BaseEntity baseEntity = beUtils.updateBaseEntity(targetCode,repAnswer);
		beUtils.updateBaseEntity(targetCode,repAnswer);

		baseEntity = beUtils.updateBaseEntity(targetCode,supervisorAnswer);
		beUtils.updateBaseEntity(targetCode,supervisorAnswer);

		insert(repAnswer);
		insert(supervisorAnswer);

		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(baseEntity);
		msg.setToken(beUtils.getGennyToken().getToken());
		msg.setReplace(true);
		VertxUtils.writeMsg("webcmds",JsonUtils.toJson(msg));

		update(answersToSave);

		/* do the search here */
		DropdownUtils dropdown = new DropdownUtils(serviceToken);

		dropdown.setNewSearch("Dropdown", "Fetch Dropdown Items")
											.addFilter("PRI_IS_HOST_CPY_REP", true)
											.setSourceCode(code)
											.setPageStart(0)
											.setPageSize(1000);

		dropdown.sendSearchResults("GRP_HOST_COMPANY_REP_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
end
