package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_SUPER_EDIT_AG_DOC"
	ruleflow-group 'DataProcessing'
			salience 6000
	when 
		$message : QEventMessage(data.code matches "ACT_PRI_EVENT_EDIT_AGREEMENT")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()

	then
		/*
		code: "ACT_PRI_EVENT_EDIT_AGREEMENT"
		parentCode: "SBE_OFFERED_APPLICATIONS_A1F5B232-3984-43E3-A2DF-1506E2AA859D"
		targetCode: "APP_E30617D8-1D8F-4F81-B9E7-F3887830437E"
		*/

		
		System.out.println("HELPER_SUPER_EDIT_AG_DOC fired");
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = $message.getData().getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		/* get the company baseentity */
		BaseEntity appBe = beUtils.getBaseEntityByCode(targetCode);
		System.out.println("appBe :: " + appBe);
		
		String hostCompanyCode = "";
		
		if(appBe != null) {
				String lnkHC = appBe.getValue("LNK_HOST_COMPANY", null);	
				System.out.println("lnkHC :: " + lnkHC);
				
				if(lnkHC != null) {
						hostCompanyCode = lnkHC.replace("\"", "").replace("[", "").replace("]", "");
						System.out.println("hostCompanyCode  :: " + hostCompanyCode);
				} else {
					System.out.println("ERROR: Null lnkHC");
				}
				
		} else {
			System.out.println("ERROR: Null appBe");
		}
		
		

		/* dropdown search here For companyRep */
		DropdownUtils dropdown = new DropdownUtils(serviceToken);
		dropdown.setNewSearch("HCR Dropdown", "Fetch HCR Dropdown Items")
											.addFilter("PRI_IS_HOST_CPY_REP", true)
											.addFilter("LNK_HOST_COMPANY", SearchEntity.StringFilter.EQUAL, hostCompanyCode)
											.setPageStart(0)
											.setPageSize(1000);

		/* Send the dropdown options */
		dropdown.sendSearchResults("GRP_HOST_COMPANY_REP_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);
		
		retract($message);

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		update(output);
end
