package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;
import java.util.List;
import java.util.ArrayList;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;

rule "HELPER_LNK_PREV_PERIOD"
	ruleflow-group 'DataProcessing'
	salience 5000
	no-loop
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_PREV_PERIOD")
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")
	then
		System.out.println(drools.getRule().getName() + " triggered");

		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);

		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);

		String value = answer.getValue();
		System.out.println("value :: " + value);

		BaseEntity be = beUtils.getBaseEntityByCode(targetCode);

		/*if(be != null){
			String prevPeriodStr = be.getValue("LNK_PREV_PERIOD", null);

			if(prevPeriodStr != null) {
				prevPeriodStr = beUtils.extractTenureDates(prevPeriodStr);
				System.out.println("prevPeriodStr  :: " + prevPeriodStr);
				Answer ans = new Answer(sourceCode, targetCode, "PRI_PREV_PERIOD", prevPeriodStr);
				beUtils.saveAnswer(ans);
				VertxUtils.sendToFrontEnd(userToken, ans);

			} else {
				System.out.println("prevPeriodStr is empty.");
			}
		} else {
			System.out.println("ERROR! be is null.");
		}*/

		if(be != null) {
			String prevPeriodStr = be.getValue("LNK_PREV_PERIOD", null);
			String startDate = null;
			String endDate = null;
			JsonObject tenureJson = null;
			DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd-MMM-yy");

			if(prevPeriodStr != null) {
				System.out.println("prevPeriodStr is:: " + prevPeriodStr);

				tenureJson = new JsonObject(prevPeriodStr);
				startDate = (String) tenureJson.getString("startDate");
				endDate = (String) tenureJson.getString("endDate");

				System.out.println("HELPER_LNK_PREV_PERIOD tenureJson is:: " + tenureJson);
				System.out.println("HELPER_LNK_PREV_PERIOD startDate is:: " + startDate);
				System.out.println("HELPER_LNK_PREV_PERIOD endDate is:: " + endDate);

				if (startDate != null) {
					String[] startDateSplit = startDate.split("T");
					startDate = startDateSplit[0];
					startDate = startDate.replace("-","");
					System.out.println("HELPER_LNK_PREV_PERIOD startDate from startDateSplit[0] is:: " + startDate);
					startDate = (LocalDate.parse(startDate, DateTimeFormatter.ofPattern("dd-MMM-yy"))).toString();
				} else {
					startDate = "";
					System.out.println("startDate is empty!");
				}

				if (endDate != null) {
					String[] endDateSplit = endDate.split("T");
					endDate = endDateSplit[0];
					endDate = (LocalDate.parse(endDate, dateFormat)).toString();
				} else {
					endDate = "";
					System.out.println("endDate is empty!");
				}

				prevPeriodStr = startDate + " - " + endDate;
				System.out.println("prevPeriodStr:: " + prevPeriodStr);


				System.out.println("prevPeriodStr  :: " + prevPeriodStr);
				Answer ans = new Answer(sourceCode, targetCode, "PRI_PREV_PERIOD", prevPeriodStr);
				beUtils.saveAnswer(ans);
				VertxUtils.sendToFrontEnd(userToken, ans);

			} else {
				System.out.println("prevPeriodStr is empty.");
			}
		} else {
			System.out.println("ERROR! be is null.");
		}
end