package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;
import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_INTERN_SUPERVISOR"
	ruleflow-group 'DataProcessing'
	salience 5000
	no-loop
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_INTERN_SUPERVISOR")
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")
	then
		System.out.println(drools.getRule().getName() + " triggered");
		
		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		String value = answer.getValue();
		System.out.println("value :: " + value);
		
		String code = beUtils.cleanUpAttributeValue(value);
		System.out.println("code  :: " + code);

		List<Answer> answers = new ArrayList<Answer>();

		/* get the supervisor baseentity */
		BaseEntity be = beUtils.getBaseEntityByCode(code);
		if(be != null){

			/* get the name attribute of the supervisor */
			String name = be.getValue("PRI_NAME", null);	
			if(name != null)	{
				Answer assocSupervisorAnswer = new Answer(sourceCode, targetCode, "PRI_ASSOC_SUPERVISOR", name,false,true);
				Answer assocSupervisorNameAnswer = new Answer(sourceCode, targetCode, "PRI_SUPER_NAME", name,false,true);
				answers.add(assocSupervisorAnswer);
				answers.add(assocSupervisorNameAnswer);
				VertxUtils.sendToFrontEnd(userToken, assocSupervisorAnswer, assocSupervisorNameAnswer);
			}

			String mobile = be.getValue("PRI_MOBILE", null);
			if(mobile != null){
				Answer assocSupervisorMobileAnswer = new Answer(sourceCode, targetCode, "PRI_SUPER_MOBILE", mobile,false,true);
				answers.add(assocSupervisorMobileAnswer);
				VertxUtils.sendToFrontEnd(userToken, assocSupervisorMobileAnswer);
			}

			String email = be.getValue("PRI_EMAIL", null);		
			if(email != null){
				Answer assocSupervisorEmailAnswer = new Answer(sourceCode, targetCode, "PRI_SUPER_EMAIL", email,false,true);
				answers.add(assocSupervisorEmailAnswer);
				VertxUtils.sendToFrontEnd(userToken, assocSupervisorEmailAnswer);
			}
		}

		beUtils.saveAnswers(answers);
end
