package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_AGENCY"
	ruleflow-group 'DataProcessing'
	salience 5000
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_AGENCY")
		answersToSave : Answers()
		ruleDetails : RuleDetails()
		output : OutputParam( )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println("HELPER_LNK_AGENCY fired");
		System.out.println(ruleDetails+" "+drools.getRule().getName()+"Processing Helper AGENCY SELECTION Answer/Data : " + answer );

		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		String agencyCode = answer.getValue();
		System.out.println("agencyCode :: " + agencyCode);
		
		String code = agencyCode.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("code  :: " + code);

		/* Save the actual LNK_AGENCY answer */
		answersToSave.add(answer);

		/* get the company baseentity */
		BaseEntity companyBe = beUtils.getBaseEntityByCode(code);
		if(companyBe != null){

			/* get the name attribute of the company */
			String name = companyBe.getValue("PRI_NAME", null);		

			/* save the company's name as PRI_ASSOC_HC attribute for person baseentity */
			if(name != null){
				Answer assocHcAnswer = new Answer(sourceCode, targetCode, "PRI_ASSOC_AGENCY", name);
				answersToSave.add(assocHcAnswer);

				VertxUtils.sendToFrontEnd(userToken, assocHcAnswer);

			}

		}

		update(answersToSave);
		retract(answer);

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		update(output);
end
