package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_INTERNSHIP_DURATION"
	ruleflow-group 'DataProcessing'
			salience 5000
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_INTERNSHIP_DURATION")
		answersToSave : Answers()
		ruleDetails : RuleDetails()
		output : OutputParam( )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println("HELPER_LNK_NO_OF_INTERNS fired");
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing Helper INTERNSHIP DURATION SELECTION Answer/Data : " + answer );
		
		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		String value = answer.getValue();
		System.out.println("hcCode :: " + value);
		
		String code = industryCode.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("code  :: " + code);

		

		BaseEntity getTheBe = beUtils.getBaseEntityByCode(code);
		String name = getTheBe.getValue("PRI_NAME", null);		
		System.out.println("##################################### DUDE: name = " +name);		
 		Answer answer = new Answer(sourceCode, targetCode, "PRI_ASSOC_DURATION", name);
 		beUtils.saveAnswer(answer);	


		/* Retract the answer message so the rule doesn't fire again */
		retract(answer);

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		update(output);
end