package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_CURRENT_COURSE"
	ruleflow-group 'DataProcessing'
			salience 5000
			no-loop
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_CURRENT_COURSE" )
		answersToSave : Answers()
		ruleDetails : RuleDetails()
		output : OutputParam( )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println("HELPER_LNK_EDU_PROVIDER fired");
		System.out.println(drools.getRule().getName());

		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		String courseCode = answer.getValue();
		System.out.println("courseCode :: " + courseCode);
		
		String code = courseCode.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("code  :: " + code);

		/* Save the actual answer */
		answersToSave.add(answer);

		/* get the associated baseentity */
		BaseEntity associatedBe = beUtils.getBaseEntityByCode(code);
		if(associatedBe != null){
		
			/* get the name attribute of the associatedBe */
			String name = associatedBe.getValue("PRI_NAME", null);		

			/* save the company's name as PRI_ASSOC_EP attribute for application baseentity */
			Answer newAnswer = new Answer(sourceCode, targetCode, "PRI_CURRENT_COURSE", name,false,true);
			
			answersToSave.add(newAnswer);
			VertxUtils.sendToFrontEnd(userToken, newAnswer);

		}

 		
 	/*	update(answersToSave);	
		retract(answer); */

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		/* update(output); */
end
