package life.genny.rules;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.utils.TaskUtils;
import java.util.List;
import java.util.ArrayList;
import life.genny.utils.QuestionUtils;

rule "HELPER_LNK_SELECT_COUNTRY_ABN"
	ruleflow-group 'DataProcessing'
	salience 500
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		answer : Answer( attributeCode == "LNK_SELECT_COUNTRY" && ( targetCode.startsWith("CPY_") ) )
		output : OutputParam()
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName()+": Rule fired");
 		
		/* Get Target User BE */
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		String value = answer.getValue();
		System.out.println("value :: " + value);
		
		String countryCode = beUtils.cleanUpAttributeValue(value);
		System.out.println("countryCode  :: " + countryCode);

		boolean enabled = false;
		if (countryCode.equals("SEL_AUSTRALIA")) {
			enabled = true;
		}

		QDataAskMessage askMsg = QuestionUtils.getAsks(userToken.getUserCode(), targetCode, "QUE_HOST_CPY_GRP", userToken.getToken());

		if (askMsg != null) {
			/* SET REPLACE TRUE */
			for (Ask ask : askMsg.getItems()[0].getChildAsks()) {
				if (ask.getQuestionCode().equals("QUE_COMPANY_ABN")) {
					/* Disable and send the ask */
					System.out.println("Setting ABN field to enabled = " + enabled);
					TaskUtils.enableTaskQuestion(ask, enabled, userToken);
				}
			}
		} else {
			System.out.println("Could not fetch ask from cache: QUE_HOST_CPY_GRP"); 
		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");
end
