package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_LNK_INDUSTRY"
	ruleflow-group 'DataProcessing'
			salience 5000
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "LNK_INDUSTRY")
		answersToSave : Answers()
		ruleDetails : RuleDetails()
		output : OutputParam( )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println("HELPER_LNK_INDUSTRY fired");
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing Helper INDUSTRY SELECTION Answer/Data : " + answer );
		
		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
		
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		
		String industryCode = answer.getValue();
		System.out.println("industryCode :: " + industryCode);
		
		String code = industryCode.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("code  :: " + code);

		Answer occupationAnswer = new Answer(sourceCode, targetCode, "LNK_OCCUPATION", " ",false,true);
		System.out.println("occupationAnswer  :: " + occupationAnswer);

		System.out.println("Saving industry and occupation answers !");
		List<Answer> answers = new ArrayList<Answer>();
		answers.add(occupationAnswer);
		answers.add(answer);
		beUtils.saveAnswers(answers);

		/* BaseEntity baseEntity = beUtils.saveAnswer(occupationAnswer);
		baseEntity = beUtils.saveAnswer(answer); */
		
		/* Send the updated baseenttity to the frontend */
		/* QDataBaseEntityMessage msg = new QDataBaseEntityMessage(baseEntity);
		msg.setToken(beUtils.getGennyToken().getToken());
		msg.setReplace(true);
		VertxUtils.writeMsg("webcmds",JsonUtils.toJson(msg)); */

		/* dropdown search here */
		DropdownUtils dropdown = new DropdownUtils(serviceToken);
		dropdown.setNewSearch("Dropdown", "Fetch Dropdown Items")
											.addColumn("PRI_NAME","Name")
											.setSourceCode(code)
											.setPageStart(0)
											.setPageSize(1000);

		/* Send the dropdown options */
		dropdown.sendSearchResults("GRP_OCCUPATION_SELECTION", "LNK_ITEM", "ITEM", true, false, userToken, false);


		/* Retract the answer message so the rule doesn't fire again */
		retract(answer);

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		update(output);
end