package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.text.WordUtils;

import java.util.List;
import java.util.ArrayList;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.text.WordUtils;


rule "PRI_FIRSTNAME_LASTNAME"
    ruleflow-group 'DataProcessing'
        salience 3 
    when
      beUtils : BaseEntityUtils()
	  $firstnameAnswer : Answer( attributeCode == "PRI_IMPORT_FIRSTNAME" )
	  lastnameAnswer : Answer( attributeCode == "PRI_IMPORT_LASTNAME" && targetCode == $firstnameAnswer.targetCode)
	  answersToSave : Answers()
	  output : OutputParam( )
     then
 		System.out.println("Rule -> PRI_FIRSTNAME_LASTNAME :  user=" + beUtils.getGennyToken().getUserCode()+" : "); 
		String sourceCode = beUtils.getGennyToken().getUserCode();
		String targetCode = $firstnameAnswer.getTargetCode();
		
		/* Parse json answer and save the individual answers */
		String lastname = lastnameAnswer.getValue();
		String firstname = $firstnameAnswer.getValue();
		lastname = lastname.toLowerCase().trim();
		lastname = StringUtils.capitalize(lastname);
		firstname = firstname.toLowerCase().trim();
		firstname = StringUtils.capitalize(firstname);

		answersToSave.add(new Answer(sourceCode, targetCode, "PRI_FIRSTNAME", firstname,false,true));
		answersToSave.add(new Answer(sourceCode, targetCode, "PRI_LASTNAME", lastname,false,true));

			
		String name = firstname + " "+lastname;
		name = name.trim();	
		name = WordUtils.capitalizeFully(name);
		System.out.println("Rule -> PRI_FIRSTNAME_LASTNAME 2 Name="+name);
		answersToSave.add(new Answer(sourceCode, targetCode, "PRI_NAME", name,false,true));
			
		String initials = 	WordUtils.initials(name).toUpperCase();
		System.out.println("Rule -> PRI_FIRSTNAME_LASTNAME 3 initials="+initials);
		answersToSave.add(new Answer(sourceCode, targetCode, "PRI_INITIALS", initials,false,true));
		
			
		output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */
		
		

		retract($firstnameAnswer);
		retract(lastnameAnswer);
		update(answersToSave);
	
end
