package life.genny.rules;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.JsonUtils;
import org.apache.commons.lang3.StringUtils;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;
import life.genny.utils.DropdownUtils;


import java.util.List;
import java.util.ArrayList;

rule "HELPER_ABN_LEGAL_NAME"
	ruleflow-group 'DataProcessing'
			salience 5000
	when
		beUtils : BaseEntityUtils()
		answer : Answer( attributeCode == "PRI_ABN")
		answersToSave : Answers()
		ruleDetails : RuleDetails()
		output : OutputParam( )
		serviceToken : GennyToken( code == "PER_SERVICE")
		userToken : GennyToken( code != "PER_SERVICE")

	then
		System.out.println("HELPER_ABN_LEGAL_NAME fired");
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing Helper ABN LEGAL NAME Answer/Data : " + answer );
		
		String sourceCode = beUtils.getGennyToken().getUserCode();
		System.out.println("sourceCode :: " + sourceCode);
	
		String targetCode = answer.getTargetCode();
		System.out.println("targetCode :: " + targetCode);
		    	
		
		
		String abn_legal = answer.getValue();
		System.out.println("abn_legal :: " + abn_legal);
		
		/* "{"ABN": "1234", "legal_name": "ABC"}" */
		
		
		System.out.println(abn_legal);
 		   
   		String abnLegal = abn_legal.replace("{\"ABN\": \"", "").replace(" \"legal_name\": \"", "").replace("\"", "").replace("}", "");
    	System.out.println(abnLegal);
    
    	String[] splt = abnLegal.split(",");
    
   		String abn = splt[0];
    	String legalName = splt[1];
    
    	System.out.println(abn);
    	System.out.println(legalName);
    	
    	Answer answerABN = new Answer(sourceCode, targetCode, "PRI_ABN", abn,false,true);
    	beUtils.saveAnswer(answerABN);
    	System.out.println("answerABN  :: " + answerABN);
    	
    	Answer answerLN = new Answer(sourceCode, targetCode, "PRI_LEGAL_NAME", legalName,false,true);
    	beUtils.saveAnswer(answerLN);
    	System.out.println("answerLN  :: " + answerLN);
    	
		

		retract(answer);

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
end