package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;


rule "CACHE_BUCKETS"
	ruleflow-group 'BucketCaching'
	salience 8
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
		beUtils : BaseEntityUtils()

	then
		System.out.println("Rule -> "+drools.getRule().getName()+" :  user=" + beUtils.getGennyToken().getUserCode()+ " , rule triggered");

		CapabilityUtils capabilityUtils = new CapabilityUtils(beUtils);
  
		String sessionCode = beUtils.getGennyToken().getJTI().toUpperCase();
		System.out.println("userCode   ::   " + userToken.getUserCode());
		System.out.println("sessionCode   ::   " + sessionCode);
	
		/* get BUCKET_CODES from cache */
		List<String> bucketCodes = VertxUtils.getObject(serviceToken.getRealm(), "", "BUCKET_CODES", List.class);
		List<String> sendCodes = new ArrayList<>();

		System.out.println("bucketCodes:"+bucketCodes);
		System.out.println(bucketCodes);

		if(bucketCodes!= null && bucketCodes.size() > 0){

			for (String code : bucketCodes) {
				if (capabilityUtils.hasCapabilityThroughPriIs(code, CapabilityMode.VIEW)) {
					System.out.println(drools.getRule().getName()+ "Has Permission for " + code);
					sendCodes.add(code);
				}
			}
			System.out.println("Adding sessionCode");

			List<String> sbeSessionCodes = sendCodes.stream().map(code -> code+"_"+sessionCode).collect(Collectors.toList());


			/* Send summary arrayCodes */
			if (!sbeSessionCodes.isEmpty()) {
				VertxUtils.sendCmdMsg(beUtils, "BUCKET_CODES", "BUCKET_CODES", sbeSessionCodes);
			}

			for (String code : sendCodes) {
				long totalTime = TableUtils.searchTable(beUtils, code, true);
				System.out.println("total took " + (totalTime) + " ms"); 
			}

		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		/* retract(allowed); */ 

end
