package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;


rule "SEND_APPLIED_APPLICATIONS_INTERNS"
	ruleflow-group 'BucketProcessing'
	salience 6
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
		beUtils : BaseEntityUtils()
		allowed : Allowed(code == "INTERN")

	then
		System.out.println("SEND_APPLIED_APPLICATIONS_INTERNS triggered");

		Boolean cache = true;
		String code ="APPLIED_APPLICATIONS";
		System.out.println("SBE_CODE   ::   " +code);

		long totalTime = TableUtils.searchTable(beUtils,code, cache, "PRI_INTERN_CODE", userToken.getCode());
		System.out.println("total took " + (totalTime) + " ms"); 

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
end
