package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "EPR_SIGNATURE"
    ruleflow-group 'ReceiveSignatures'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity()

	  
     then
 		System.out.println("EPR_SIGNATURE: Rule fired" ); 
 		System.out.println("EPR_SIGNATURE: newApplication = " + newApplication.getCode());
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		Answer answer = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_EPR_SIGNATURE", "true");
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);
 		beUtils.saveAnswer(answer);
		
		System.out.println("EPR_SIGNATURE: Answer = " + answer);
		System.out.println("EPR_SIGNATURE: newApplication = " + newApplication); 
		
	

		retract(newApplication)

		
end
