package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import java.util.List;
import java.util.ArrayList;

rule "PRI_FILTER_VALUE"
    ruleflow-group 'DataProcessing'
    salience 500 
    no-loop true
    when
		beUtils : BaseEntityUtils()
		serviceToken : GennyToken( code == "PER_SERVICE")
		answer : Answer( attributeCode matches "PRI_FILTER_VALUE_.*" && targetCode matches "SBE_.*" )
		output : OutputParam( )
		answersToSave : Answers()
	then
		System.out.println("Rule -> PRI_FILTER_VALUE : "+answer); 

		String targetCode = answer.getTargetCode();
		System.out.println("targetCode = " + targetCode);
		String value = answer.getValue();
		System.out.println("value = " + value);

		/* Get filter array from cache */
		String[] newFilterArray = VertxUtils.getObject(serviceToken.getRealm(), "", "FLT_"+targetCode, String[].class, serviceToken.getToken());

		/* Save the new filter items in cache */
		newFilterArray[2] = value;

		VertxUtils.putObject(serviceToken.getRealm(), "", "FLT_"+targetCode, newFilterArray, serviceToken.getToken());

		/* Disable Submit */
		Ask filterGrpAsk = VertxUtils.getObject(serviceToken.getRealm(), "", "QUE_FILTER_GRP_"+targetCode, Ask.class, serviceToken.getToken());
		filterGrpAsk.getChildAsks()[0].getChildAsks()[4].setDisabled(false);

		/* Cache changes */
		VertxUtils.putObject(beUtils.getGennyToken().getRealm(), "", filterGrpAsk.getQuestionCode(), filterGrpAsk, serviceToken.getToken());

		/* Send Asks to FE */
		QDataAskMessage askMsg = new QDataAskMessage(filterGrpAsk);
		askMsg.setToken(beUtils.getGennyToken().getToken());
		askMsg.setReplace(true);
		VertxUtils.writeMsg("webcmds", askMsg);
		System.out.println("Asks sent to FE");

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */

		retract(answer);
		update(output);

end
