package life.genny.rules;










import life.genny.rules.QRules;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;

rule "RulesNotificaitonTemplate_Shortlist_Default_1"
    ruleflow-group 'RulesNotificaitonHubGroup'
    no-loop true
    when
		userToken : GennyToken ( )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( output.getResultCode() == "TEMPLATE_GROUP_SHORTLIST" )
    then
		JsonObject jsonTemplates = new JsonObject();
		jsonTemplates.put("1", "EMAIL_TEMPLATE_SHORTLIST_STUDENT");
		System.out.println("Notitificaitons Template Json: " + jsonTemplates.toString());

		output.setTypeOfResult("NotificationHubTemplateFound");
		output.setResultCode(jsonTemplates.toString());
		retract(output);
end
