package life.genny.rules;










import life.genny.rules.QRules;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;

rule "RulesNotificaitonCode_Shortlist_Default_1"
    ruleflow-group 'RulesNotificaitonHubGroup'
    no-loop true
    when
		userToken : GennyToken ( )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		localSignalMessage : String ( localSignalMessage == "SHORTLIST" )
    then
		System.out.println("Notitificaitons Code exec 2: " + localSignalMessage);
		output.setTypeOfResult("NotificationHubAccessGranted");
		output.setResultCode("TEMPLATE_GROUP_SHORTLIST");
		retract(localSignalMessage);
end
