package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;

rule "RulesNotificaitonTemplate_Offer_Default_1"
    ruleflow-group 'RulesNotificaitonHubGroup'
    no-loop true
    when
		userToken : GennyToken ( )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( output.getResultCode() == "TEMPLATE_GROUP_OFFER" )
    then
		JsonObject jsonTemplates = new JsonObject();
		jsonTemplates.put("1", "EMAIL_TEMPLATE_OFFER_STUDENT");
		jsonTemplates.put("2", "EMAIL_TEMPLATE_OFFER_SCHOOL");
		jsonTemplates.put("3", "EMAIL_TEMPLATE_OFFER_SALESTEAM");
		jsonTemplates.put("4", "SMS_TEMPLATE_OFFER_STUDENT");
		System.out.println("Notitificaitons Template Json: " + jsonTemplates.toString());
		
		output.setTypeOfResult("NotificationHubTemplateFound");
		output.setResultCode(jsonTemplates.toString());
		retract(output);
end
