package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.Layout.LayoutPosition;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.entity.SearchEntity.StringFilter;
import java.io.IOException;

rule "Ask User Role"
    when
        rules: QRules( 	isState("ASK_USER_ROLE") &&
						!isState("LOOP_ASK_USER_ROLE")	)
     then
     	rules.header();
        rules.setState("LOOP_ASK_USER_ROLE");
              
        rules.sendQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_BUYER_GRP");
        
        rules.navigateTo("/registration/role");
        
    	rules.footer();
end
