package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.Layout.LayoutPosition;
import life.genny.qwanda.message.QDataBaseEntityMessage;

rule "Send Logo Questions"
    when
        rules: QRules(  isState("SEND_LOGO_QUESTIONS") && 
                        !isState("LOOP_SEND_LOGO_QUESTIONS")  ) 
     then

        rules.header();
        rules.setState("LOOP_SEND_LOGO_QUESTIONS");

        
        /* sends questions for LOGO and positions it in the sidebar frame */
		rules.askQuestions(rules.getUser().getCode(), rules.getProject().getCode(), "QUE_PROJECT_SIDEBAR_GRP", false, "FRM_SIDEBAR", LayoutPosition.NORTH);
  		       	    	
		rules.setState("SEND_TREEVIEW_QUESTIONS");
	    rules.footer();     		      
end
