package life.genny.rules;
import life.genny.rules.QRules;
import java.util.Iterator;

rule "Send Main Frame To Frontend"
    when
        rules: QRules(  isState("SEND_MAIN_FRAME") && 
                        !isState("LOOP_SEND_MAIN_FRAME")  ) 
     then

        rules.header();
        rules.setState("LOOP_SEND_MAIN_FRAME");
  		
        /* get the root frame base entity */
        BaseEntity rootFrame = rules.baseEntity.getBaseEntityByCode("FRM_ROOT");

        /* get its children (frames) */
        List<BaseEntity> children = rules.baseEntity.getLinkedBaseEntities(rootFrame.getCode(), null, null, 3);

        /* create message */
        QDataBaseEntityMessage message = new QDataBaseEntityMessage(children);

        /* add parent as an item */
        message.add(rootFrame);

        /* set parent */
        message.setParentCode(rootFrame.getCode());
        
        /* send message */
        rules.publishCmd(message);

		rules.setState("TRIGGER_SEND_SYSTEM_LAYOUTS");
	    rules.footer();     		      
end
