package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.Layout.LayoutPosition;

rule "Send User Profile Selection Questions"
    when
        rules: QRules(  isState("SEND_USER_PROFILE_SELECTION_QUESTIONS") && 
                        !isState("LOOP_SEND_USER_PROFILE_SELECTION_QUESTIONS")  ) 
     then

        rules.header();
        rules.setState("LOOP_SEND_USER_PROFILE_SELECTION_QUESTIONS");
        
        /* getting user */
        BaseEntity user = rules.getUser();
        
        /* send required data */
        List<BaseEntity> userOptions = rules.baseEntity.getLinkedBaseEntities("GRP_USER_OPTIONS", "LNK_CORE");
        rules.println("userOptions size :: "+userOptions.size());
        rules.publishBaseEntityByCode("GRP_USER_OPTIONS");
              
        /* sending user profile selection questions */
        rules.askQuestions(user.getCode(), rules.getProject().getCode(), "QUE_PROJECT_USER_OPTIONS_GRP", false, "FRM_HEADER", LayoutPosition.EAST);
  		       	    	
		rules.setState("TRIGGER_SEND_SYSTEM_LAYOUTS");
	    rules.footer();     		      
end
