package life.genny.rules;
import life.genny.rules.QRules;

rule "Send TreeView Questions"
    when
        rules: QRules(  isState("SEND_TREEVIEW_QUESTIONS") && 
                        !isState("LOOP_SEND_TREEVIEW_QUESTIONS")  ) 
     then

        rules.header();
        rules.setState("LOOP_SEND_TREEVIEW_QUESTIONS");
        
        /* sending tree-data */
        rules.sendTreeData();
  		       	    	
	    rules.footer();     		      
end
