package life.genny.rules;

import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.utils.OutputParam;

rule "TREE_ITEM_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "QUE_.*" && (data.parentCode == "QUE_DASHBOARD_VIEW" || data.parentCode == "QUE_TAB_VIEW"))
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		System.out.println("Parent code :  " + $message.getData().getParentCode());
		output.setFormCode("FRM_"+ code,"FRM_CONTENT");
		retract( $message);
		
	end
