package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "TWO"
    ruleflow-group 'StatusChange'
    no-loop true
    salience 1 
    when
	  
     then
 		System.out.println("SUCCESS -> Fired change status rules" ); 


end
