package life.genny.rules;



import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Theme;



rule "THM_LOGO"
    ruleflow-group 'GenerateThemes'
    no-loop true
    
    when
      not  Theme (code == "THM_LOGO")
      serviceToken : GennyToken( code == "PER_SERVICE")
      
    then
    
     	System.out.println("   Generate THM_LOGO Rule ");
 
			/*Theme theme = Theme.builder("THM_LOGO")
								.addAttribute()
									.fit("contain")
									.height(100)
									.width(100)
								.end()
								.build();*/
			
			Theme theme = Theme.builder("THM_LOGO")
								.addAttribute()	
									.imageHeight(100)
									.imageWidth(170)
									.showName(false)
								.end()
								.build();
													
			theme.setRealm(serviceToken.getRealm());
			
			insert(theme);

			VertxUtils.putObject(serviceToken.getRealm(), "", theme.getCode(), theme, serviceToken.getToken());
end
