package life.genny.rules;
import life.genny.rules.QRules;

rule "Search In Table"
    when
        rules : QRules( isState("EVENT_ANSWER")  &&
			            isState("SBE_ANSWER") &&
                        !getAsString("attributeCode").equals("QUE_TABLE_ACTIONS_GRP") &&
                        !isState("SCH_PAGE_SIZE") && /* Don't trigger if it's pageSize change */
			            !isState("LOOP_SEARCH_IN_TABLE") )
     then
      	rules.header();
		rules.setState("LOOP_SEARCH_IN_TABLE");

		String searchCode = rules.getAsString("targetCode");
		String attributeCode = rules.getAsString("attributeCode");
		String value = rules.getAsString("value");

        rules.println("searchCode  ::  " + searchCode);
        rules.println("attributeCode  ::  " + attributeCode);
        rules.println("value  ::  " + value);

        SearchEntity searchBe = rules.baseEntity.getSearchEntityByCode(searchCode);
        rules.println("search" + searchBe.getCode());

        searchBe.addFilter(attributeCode, SearchEntity.StringFilter.LIKE, "%" + value + "%");

        rules.set("searchBe", searchBe);

        /* create a bulk msg */
        QBulkMessage bulkMsg = new QBulkMessage();
        rules.set("bulkMsg", bulkMsg);

        rules.setState("GENERATE_TABLE_CONTENT");
        rules.setState("LOOP_GENERATE_TABLE_FOOTER");
        rules.setState("SEND_SEARCH_RESULTS");
        rules.footer();
end

