package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Delete Note"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_DELETE_NOTE") &&
						!isState("LOOP_TRIGGER_DELETE_NOTE") )
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_DELETE_NOTE");

        String noteCode = rules.getAsString("itemCode");
		if(noteCode == null) {
			rules.setState("SEND_TOAST_SOMETHING_WENT_WRONG");
			return;
		}
	
		rules.setState("UNLINK_NOTE_FROM_GRP_NOTES");
	 	rules.footer();
end


