package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.Layout.LayoutPosition;
import java.util.HashMap;
import life.genny.qwanda.Context;

rule "Send User Profile Selection Questions"
    when
        rules: QRules(  isState("SEND_USER_PROFILE_SELECTION_QUESTIONS") && 
                        !isState("LOOP_SEND_USER_PROFILE_SELECTION_QUESTIONS")  ) 
     then

        rules.header();
        rules.setState("LOOP_SEND_USER_PROFILE_SELECTION_QUESTIONS");
      
        /* sending user profile selection questions */
    /*    rules.askQuestions(rules.getUser().getCode(), rules.getProject().getCode(), "QUE_PROJECT_USER_OPTIONS_GRP", false, "FRM_HEADER", LayoutPosition.EAST); */
  		       	    	
		rules.setState("EXIT_APPLICATION_SETUP");
	    rules.footer();     		      
end
