package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "GREEN"
    ruleflow-group 'CommonEnter'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity()
		output : OutputParam()
		colourCode : String(colourCode.equals("Green"))

	  
     then
 		System.out.println("Green: Rule fired" ); 
 		System.out.println("Green: newApplication = " + newApplication.getCode());
 		
 	/*  green: '#5cb85c' */
	/*  orange: '#FFCC00' */
	/*  red: '#cc0000' */
 		
 	/*  Construct answer with Source, Target, Attribute Code, Value */
 	/* Answer answer = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_BUCKET_CODE","SHORTLIST"); */
 		Answer answer = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_STATUS_COLOR","#5cb85c");
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);
 		beUtils.saveAnswer(answer);

	/* insert(answer); */
		
		System.out.println("Green: Answer = " + answer);
		System.out.println("Green: newApplication = " + newApplication); 
		
		
	/* System.out.println("GREEN: Answer Source Code = " + answer.getSourceCode()); */
	/* System.out.println("GREEN: Answer Target Code = " + answer.getTargetCode()); */
	/* System.out.println("GREEN: Answer Attribute Code = " + answer.getAttributeCode()); */
	/* System.out.println("GREEN: Answer Value = " + answer.getValue());  */
		
	/*  Set the attribute code and value to output */
		output.setResultCode(answer.getAttributeCode());
		output.setTargetCode(answer.getValue());
	
		retract(userToken)
		retract(serviceToken)
		retract(colourCode)
		retract(newApplication)
		
end
