package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Send Table"
	when
		rules: QRules(  isState("TRIGGER_SEND_TABLE") &&
						!isState("LOOP_TRIGGER_SEND_TABLE"))
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_SEND_TABLE");

		/* we get the SearchEntity  */
		SearchEntity searchBe = rules.getAsSearchEntity("searchBe");
		if(searchBe == null){
			rules.println("searchBe not in the state");
			return;
		}
        rules.println("searchEntity :: " + JsonUtils.toJson(searchBe));

		/* we publish the searchEntity code as baseentity */
		rules.publishBaseEntityByCode(searchBe.getCode());

		/* we set the SearchEntity in state */
		rules.set("searchBe", searchBe);

		/* generate table frames */
		rules.setState("GENERATE_TABLE_FRAMES");
		rules.footer();
end
