package life.genny.rules;
import life.genny.rules.QRules;

rule "Pre Init - Init"
    when
        rules: QRules( !isState("LOOP_PREINIT") )
     then

	    rules.setDrools(drools);
		rules.header();

		rules.setState("LOOP_PREINIT");
		rules.setState("TRIGGER_ROLE_CHECK");
        rules.setState("PRE_INIT_READY");

	/* 	BaseEntity cards = rules.baseEntity.create("GRP_CARDS", "Cards");
		rules.baseEntity.createLink("GRP_ROOT", cards.getCode(), "LNK_CORE", "LINK", 20.0);
        rules.baseEntity.saveAnswer(
			new Answer("GRP_ROOT", "GRP_ROOT", cards.getCode(), "PRI_IS_AGENT,PRI_IS_SELLER,PRI_IS_BUYER,PRI_IS_EDU_PROVIDER_STAFF")
		);  */


		rules.footer();
end
